// Angular/corporate/src/app/pages/apps/jobs/job-categories/job-categories.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { DecimalPipe } from '@angular/common';

import { jobcategories } from 'src/app/core/data';

@Component({
  selector: 'app-job-categories',
  templateUrl: './job-categories.component.html',
  styleUrls: ['./job-categories.component.scss']
})
export class JobCategoriesComponent implements OnInit {

  // bread crumb items
  breadCrumbItems!: Array<{}>;
  categories: any;
  allcategory: any;
  searchTerm: any;
  searchResults: any;

  constructor() {
  }

  ngOnInit(): void {
    /**
* BreadCrumb
*/
    this.breadCrumbItems = [
      { label: 'Jobs' },
      { label: 'Job Categories', active: true }
    ];

    // Fetch Data
    setTimeout(() => {
      this.categories = jobcategories;
      this.allcategory = jobcategories;
      document.getElementById('elmLoader')?.classList.add('d-none')
      document.getElementById('loadmore')?.classList.remove('d-none')
    }, 1200)
  }

   // Search Data
   performSearch(): void {
    this.searchResults = this.allcategory.filter((item: any) => {
      return (
        item.name.toLowerCase().includes(this.searchTerm.toLowerCase()) || 
        item.position.toLowerCase().includes(this.searchTerm.toLowerCase())
      );
    });
    this.categories = this.searchResults
  }
  
}

<!-- Start Breadcrumbs -->
<app-breadcrumbs title="Job Categories" [breadcrumbItems]="breadCrumbItems"></app-breadcrumbs>
<!-- End Breadcrumbs -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="row justify-content-between gy-3">
                    <div class="col-lg-3">
                        <div class="search-box">
                            <input type="text" class="form-control search" placeholder="Search for job categories..."
                            [(ngModel)]="searchTerm" (ngModelChange)="performSearch()">
                            <i class="ri-search-line search-icon"></i>
                        </div>
                    </div>
                    <div class="col-lg-auto">
                        <div ngbDropdown class="d-md-flex gap-2 flex-wrap">
                            <button class="btn btn-primary"><i class=" ri-add-fill me-1 align-bottom"></i> Add
                                Categories</button>
                            <button class="btn btn-secondary"><i class="ri-filter-2-line me-1 align-bottom"></i>
                                Filters</button>
                            <button ngbDropdownToggle type="button" id="dropdownMenuLink1" data-bs-toggle="dropdown"
                                aria-expanded="false" class="btn btn-soft-info arrow-none"><i
                                    class="ri-more-2-fill"></i></button>
                            <ul ngbDropdownMenu class="dropdown-menu" aria-labelledby="dropdownMenuLink1">
                                <li><a class="dropdown-item" href="javascript:void(0);">All</a></li>
                                <li><a class="dropdown-item" href="javascript:void(0);">Last Week</a></li>
                                <li><a class="dropdown-item" href="javascript:void(0);">Last Month</a></li>
                                <li><a class="dropdown-item" href="javascript:void(0);">Last Year</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end col-->
</div>
<!--end row-->

<div class="row row-cols-xxl-5 row-cols-lg-3 row-cols-md-2 row-cols-1">
    @for(category of categories;track $index){
    <div class="col">
        <div class="card">
            <div class="card-body text-center py-4">
                <lord-icon src="{{category.icon}}" trigger="hover" colors="primary:#405189" target="div"
                    style="width:50px;height:50px"></lord-icon>
                <a href="javascript:void(0);" class="stretched-link">
                    <h5 class="mt-4">{{category.name}}</h5>
                </a>
                <p class="text-muted mb-0">{{category.position}} Position</p>
            </div>
        </div>
    </div>
}
    <div id="elmLoader">
        <div class="spinner-border text-primary avatar-sm" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
</div>

<div class="row d-none" id="loadmore">
    <div class="col-lg-12">
        <div class="text-center mb-3">
            <button class="btn btn-link text-success mt-2" id="loadmore"><i
                    class="mdi mdi-loading mdi-spin fs-20 align-middle me-2"></i> Load More </button>
        </div>
    </div>
</div>

// Svelte/corporate/src/routes/Jobs/jobcategories/+page.svelte
<svelte:head>
  <title>Job Categories | Velzon - Svelte Admin & Dashboard Template</title>
</svelte:head>
<script>
    import {
  Card,
  CardBody,
  CardHeader,
  Col,
  Container,
  DropdownItem,
  DropdownMenu,
  DropdownToggle,
  Input,
  Row,
  Dropdown,
} from "sveltestrap";
import jobCategories from "../../../common/data/appsJobs";
import BreadCrumb from "../../../Components/Common/BreadCrumb.svelte";
import Link from 'svelte-link'
</script>
<div class="page-content">
    <Container fluid class="container-fluid">
      <BreadCrumb title="Job Categories" pageTitle="Jobs" />
      <Row>
        <Col lg={12}>
          <Card>
            <CardHeader>
              <Row class="justify-content-between gy-3">
                <Col lg={3}>
                  <div class="search-box">
                    <Input
                      type="text"
                      class="form-control search"
                      placeholder="Search for job categories..."
                    />
                    <i class="ri-search-line search-icon"></i>
                  </div>
                </Col>
                <Col class="col-lg-auto">
                  <div class="d-md-flex text-nowrap gap-2">
                    <button
                      class="btn btn-primary"
                      data-bs-toggle="modal"
                      data-bs-target="#showModal"
                    >
                      <i class="ri-add-fill me-1 align-bottom"></i> Add
                      Categories
                    </button>
                    <button class="btn btn-secondary">
                      <i class="ri-filter-2-line me-1 align-bottom"></i>{" "}
                      Filters
                    </button>
                    <Dropdown>
                      <DropdownToggle
                        type="button"
                        role="button"
                        tag="button"
                        id="dropdownMenuLink1"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                        class="btn btn-soft-info"
                      >
                        <i class="ri-more-2-fill"></i>
                      </DropdownToggle>
                      <DropdownMenu
                        class="dropdown-menu"
                        aria-labelledby="dropdownMenuLink1"
                      >
                        <li>
                          <DropdownItem class="dropdown-item" href={null}>
                            All
                          </DropdownItem>
                        </li>
                        <li>
                          <DropdownItem class="dropdown-item" href={null}>
                            Last Week
                          </DropdownItem>
                        </li>
                        <li>
                          <DropdownItem class="dropdown-item" href={null}>
                            Last Month
                          </DropdownItem>
                        </li>
                        <li>
                          <DropdownItem class="dropdown-item" href={null}>
                            Last Year
                          </DropdownItem>
                        </li>
                      </DropdownMenu>
                    </Dropdown>
                  </div>
                </Col>
              </Row>
            </CardHeader>
          </Card>
        </Col>
      </Row>

      <Row class="row-cols-xxl-5 row-cols-lg-3 row-cols-md-2 row-cols-1">
        {#each jobCategories.jobCategories as item}
            <Col>
                <Card>
                    <CardBody class="text-center py-4">
                        <lord-icon
                            src={item.icon}
                            trigger="hover"
                            colors="primary:#405189"
                            target="div"
                            style="width: 50px; height: 50px"></lord-icon>
                        <Link href={null} class="stretched-link">
                            <h5 class="mt-4">{item.lable}</h5>
                        </Link>
                        <p class="text-muted mb-0">{item.position}</p>
                    </CardBody>
                </Card>
            </Col>
        {/each}
      </Row>

      <Row>
        <Col lg={12}>
          <div class="text-center mb-3">
            <button
              class="btn btn-link text-success mt-2"
              id="loadmore"
            >
              <i class="mdi mdi-loading mdi-spin fs-20 align-middle me-2"></i>{" "}
              Load More{" "}
            </button>
          </div>
        </Col>
      </Row>
    </Container>
  </div>
