// React+Inertia/Minimal/resources/js/Pages/Crypto/BuySell/index.tsx
import React from 'react';
import { Container, Row } from 'react-bootstrap';
import BreadCrumb from '../../../Components/Common/BreadCrumb';
import MarketGraph from './MarketGraph';
import Widgets from './Widgets';
import BuySellCoin from './BuySellCoin';
import Market from './Market';

import { Head } from '@inertiajs/react';
import Layout from '../../../Layouts';

const BuySell = () => {
    return (
        <React.Fragment>
              <Head title="Buy & Sell | Velzon - React Admin & Dashboard Template"/>
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="Buy & Sell" pageTitle="Crypto" />
                    <Row>
                        <Widgets />
                    </Row>
                    <Row>
                        <MarketGraph dataColors='["--vz-primary", "--vz-success"]'/>
                        <BuySellCoin />
                    </Row>
                    <Market />
                </Container>
            </div>
        </React.Fragment>
    );
};
BuySell.layout =(page:any) => <Layout children={page}/>
export default BuySell;

// Svelte/minimal/src/routes/crypto/buysell/+page.svelte
<script>
	import { Container, Row } from "sveltestrap";
	import BreadCrumb from "../../../Components/Common/BreadCrumb.svelte";
	import MarketGraph from "./MarketGraph.svelte";
	import Widgets from "./Widgets.svelte";
	import BuySellCoin from "./BuySellCoin.svelte";
	import Market from "./Market.svelte";
</script>

<svelte:head>
	<title>Buy & Sell | Velzon - Svelte Admin & Dashboard Template</title>
</svelte:head>

<div class="page-content">
	<Container fluid>
		<BreadCrumb title="Buy & Sell" pageTitle="Crypto" />
		<Row>
			<Widgets />
		</Row>
		<Row>
			<MarketGraph dataColors={["--vz-primary", "--vz-success"]}/>
			<BuySellCoin />
		</Row>
		<Market />
	</Container>
</div>
