// Svelte/corporate/src/routes/landing/OnePage/footer.svelte
<script>
    import Link from 'svelte-link';
import { Col, Container, Row } from 'sveltestrap';

// Import Images
import logolight from "../../../assets/images/logo-light.png";
</script>
<footer class="custom-footer bg-dark py-5 position-relative">
    <Container>
        <Row>
            <Col lg={4} class="mt-4">
                <div>
                    <div>
                        <img src={logolight} alt="logo light" height="17" />
                    </div>
                    <div class="mt-4 fs-13">
                        <p>Premium Multipurpose Admin & Dashboard Template</p>
                        <p class="ff-secondary">You can build any type of web application like eCommerce, CRM, CMS, Project
                            management apps, Admin Panels, etc using Velzon.</p>
                    </div>
                </div>
            </Col>

            <Col lg={7} class="ms-lg-auto">
                <Row>
                    <Col sm={4} class="mt-4">
                        <h5 class="text-white mb-0">Company</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list">
                                <li><Link href="/pages/profile/simple">About Us</Link></li>
                                <li><Link href="/pages/gallery/pages-gallery">Gallery</Link></li>
                                <li><Link href="/projects/apps-projects-overview">Projects</Link></li>
                                <li><Link href="/pages/timeline/timeline">Timeline</Link></li>
                            </ul>
                        </div>
                    </Col>
                    <Col sm={4} class="mt-4">
                        <h5 class="text-white mb-0">Apps Pages</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list">
                                <li><Link href="/pages/pricing/pages-pricing">Calendar</Link></li>
                                <li><Link href="/emailInbox/apps-mailbox">Mailbox</Link></li>
                                <li><Link href="/apps-chat">Chat</Link></li>
                                <li><Link href="/crm/apps-crm-deals">Deals</Link></li>
                                <li><Link href="/tasks/apps-tasks-kanban">Kanban Board</Link></li>
                            </ul>
                        </div>
                    </Col>
                    <Col sm={4} class="mt-4">
                        <h5 class="text-white mb-0">Support</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list">
                                <li><Link href="/pages/faqs">FAQ</Link></li>
                                <li><Link href="/crm/apps-crm-contacts">Contact</Link></li>
                            </ul>
                        </div>
                    </Col>
                </Row>
            </Col>

        </Row>

        <Row class="text-center text-sm-start align-items-center mt-5">
            <Col sm={6}>

                <div>
                    <p class="copy-rights mb-0">
                        {new Date().getFullYear()} © Velzon - Themesbrand
                    </p>
                </div>
            </Col>
            <Col sm={6}>
                <div class="text-sm-end mt-3 mt-sm-0">
                    <ul class="list-inline mb-0 footer-social-link">
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-facebook-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-github-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-linkedin-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-google-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-dribbble-line"></i>
                                </div>
                            </Link>
                        </li>
                    </ul>
                </div>
            </Col>
        </Row>
    </Container>
</footer>

// Angular/galaxy/src/app/shared/landing/index/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})

/**
 * Footer Component
 */
export class FooterComponent implements OnInit {

    // set the currenr year
  year: number = new Date().getFullYear();
  
  constructor() { }

  ngOnInit(): void {
  }

}

<!-- Start footer -->
<footer class="custom-footer bg-dark py-5 position-relative">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mt-4">
                <div>
                    <div>
                        <img src="assets/images/logo-light.png" alt="logo light" height="17">
                    </div>
                    <div class= "mt-4 fs-14">
                        <p>Premium Multipurpose Admin & Dashboard Template</p>
                        <p class="ff-secondary">You can build any type of web application like eCommerce, CRM, CMS, Project
                            management apps, Admin Panels, etc using Velzon.</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-7 ms-lg-auto">
                <div class="row">
                    <div class="col-sm-4 mt-4">
                        <h5 class="text-white mb-0">Company</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list">
                                <li><a href="/pages/profile">About Us</a></li>
                                <li><a href="/pages/gallery">Gallery</a></li>
                                <li><a href="/projects/overview">Projects</a></li>
                                <li><a href="/pages/timeline">Timeline</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-4 mt-4">
                        <h5 class="text-white mb-0">Apps Pages</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list">
                                <li><a href="/pages/pricing">Calendar</a></li>
                                <li><a href="/mailbox">Mailbox</a></li>
                                <li><a href="/chat">Chat</a></li>
                                <li><a href="/crm/deals">Deals</a></li>
                                <li><a href="/tasks/kanban">Kanban Board</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-4 mt-4">
                        <h5 class="text-white mb-0">Support</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list">
                                <li><a href="/pages/faqs">FAQ</a></li>
                                <li><a href="/pages/faqs">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="row text-center text-sm-start align-items-center mt-5">
            <div class="col-sm-6">

                <div>
                    <p class="copy-rights mb-0">
                      {{year}} © Velzon - Themesbrand
                    </p>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end mt-3 mt-sm-0">
                    <ul class="list-inline mb-0 footer-social-link">
                        <li class="list-inline-item">
                            <a href="javascript: void(0);" class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-facebook-fill"></i>
                                </div>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="javascript: void(0);" class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-github-fill"></i>
                                </div>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="javascript: void(0);" class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-linkedin-fill"></i>
                                </div>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="javascript: void(0);" class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-google-fill"></i>
                                </div>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="javascript: void(0);" class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                <i class="ri-dribbble-line"></i>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end footer -->
