// Svelte/master/src/Components/Common/LanguageDropdown.svelte
<script>
	import {
		Dropdown,
		DropdownToggle,
		DropdownMenu,
		DropdownItem,
	} from "sveltestrap";
	import { setupI18n } from "./../../services/i18n";
	import languages from "../../common/data/languages";
	import { browser } from "$app/environment";
	import usimg from '../../assets/images/flags/us.svg'

	export let selectedLang = browser
		? localStorage.getItem("I18N_LANGUAGE") || "en"
		: "en";

	let isOpen = false;

	function handleLocaleChange(lang) {
		setupI18n({ withLocale: lang });
		if (browser) {
			localStorage.setItem("I18N_LANGUAGE", lang);
		}
	}
</script>

<Dropdown class="ms-1 topbar-head-dropdown header-item">
	<DropdownToggle
		tag="button"
		color=""
		class="btn btn-icon btn-topbar material-shadow-none btn-ghost-secondary rounded-circle p-0"
	>
		<img
			id="header-lang-img"
			src={usimg}
			alt="Header Language"
			height="20"
			class="rounded"
		/>
	</DropdownToggle>
	<DropdownMenu class="dropdown-menu-end" end>
		{#each languages as language}
			<DropdownItem
				key={language.value}
				on:click={() => handleLocaleChange(language.value)}
				class={`notify-item language py-2 ${
					selectedLang === language.value ? "active" : "none"
				}`}
			>
				<img
					src={language.flag}
					alt="Skote"
					class="me-2 rounded"
					height="18"
				/>
				<span class="align-middle">
					{language.label}
				</span>
			</DropdownItem>
		{/each}
	</DropdownMenu>
</Dropdown>

// React+TS/Corporate/src/Components/Common/LanguageDropdown.tsx
import React, { useEffect, useState } from 'react';
import { Dropdown, DropdownItem, DropdownMenu, DropdownToggle } from 'reactstrap';
import { get } from "lodash";

//i18n
import i18n from "../../i18n";
import languages from "../../common/languages";


const LanguageDropdown = () => {
    // Declare a new state variable, which we'll call "menu"
    const [selectedLang, setSelectedLang] = useState<any>("");

    useEffect(() => {
        const currentLanguage = localStorage.getItem("I18N_LANGUAGE");
        setSelectedLang(currentLanguage);
    }, []);

    const changeLanguageAction = (lang:any) => {
        //set language as i18n
        i18n.changeLanguage(lang);
        localStorage.setItem("I18N_LANGUAGE", lang);
        setSelectedLang(lang);
    };


    const [isLanguageDropdown, setIsLanguageDropdown] = useState<boolean>(false);
    const toggleLanguageDropdown = () => {
        setIsLanguageDropdown(!isLanguageDropdown);
    };
    return (
        <React.Fragment>
            <Dropdown isOpen={isLanguageDropdown} toggle={toggleLanguageDropdown} className="ms-1 topbar-head-dropdown header-item">
                <DropdownToggle className="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle" tag="button">
                    <img
                        src={get(languages, `${selectedLang}.flag`)}
                        alt="Header Language"
                        height="20"
                        className="rounded"
                    />
                </DropdownToggle>
                <DropdownMenu className="notify-item language py-2">
                    {Object.keys(languages).map(key => (
                        <DropdownItem
                            key={key}
                            onClick={() => changeLanguageAction(key)}
                            className={`notify-item ${selectedLang === key ? "active" : "none"
                                }`}
                        >
                            <img
                                src={get(languages, `${key}.flag`)}
                                alt="Skote"
                                className="me-2 rounded"
                                height="18"
                            />
                            <span className="align-middle">
                                {get(languages, `${key}.label`)}
                            </span>
                        </DropdownItem>
                    ))}
                </DropdownMenu>
            </Dropdown>
        </React.Fragment>
    );
};

export default LanguageDropdown;
