// React+TS/Saas/src/pages/Ecommerce/EcommerceSellers/Revenue.tsx
import React from "react";
import { Card, CardBody, CardHeader, Col, Row } from "reactstrap";
import RevenueCharts from "./RevenueCharts";
import CountUp from "react-countup";

const Revenue = () => {
  return (
    <React.Fragment>
      <Card>
        <CardHeader className="border-0 align-items-center d-flex">
          <h4 className="card-title mb-0 flex-grow-1">Revenue</h4>
          <div className="d-flex gap-1">
            <button type="button" className="btn btn-soft-dark btn-sm">
              ALL
            </button>
            <button type="button" className="btn btn-soft-dark btn-sm">
              1M
            </button>
            <button type="button" className="btn btn-soft-dark btn-sm">
              6M
            </button>
            <button type="button" className="btn btn-soft-primary btn-sm">
              1Y
            </button>
          </div>
        </CardHeader>

        <CardHeader className="p-0 border-0 bg-light-subtle">
          <Row className="g-0 text-center">
            <Col xs={6} sm={3}>
              <div className="p-3 border border-dashed border-start-0">
                <h5 className="mb-1">
                  <CountUp start={0} end={7585} duration={3} separator="," />
                </h5>
                <p className="text-muted mb-0">Orders</p>
              </div>
            </Col>
            <Col xs={6} sm={3}>
              <div className="p-3 border border-dashed border-start-0">
                <h5 className="mb-1">
                  <CountUp
                    suffix="k"
                    prefix="$"
                    start={0}
                    decimals={2}
                    end={22.89}
                    duration={3}
                  />
                </h5>
                <p className="text-muted mb-0">Earnings</p>
              </div>
            </Col>
            <Col xs={6} sm={3}>
              <div className="p-3 border border-dashed border-start-0">
                <h5 className="mb-1">
                  <CountUp start={0} end={367} duration={3} />
                </h5>
                <p className="text-muted mb-0">Refunds</p>
              </div>
            </Col>
            <Col xs={6} sm={3}>
              <div className="p-3 border border-dashed border-start-0 border-end-0">
                <h5 className="mb-1 text-success">
                  <CountUp
                    start={0}
                    end={18.92}
                    decimals={2}
                    duration={3}
                    suffix="%"
                  />
                </h5>
                <p className="text-muted mb-0">Conversation Ratio</p>
              </div>
            </Col>
          </Row>
        </CardHeader>

        <CardBody className="p-0 pb-2">
          <div className="w-100">
            <div dir="ltr">
              <RevenueCharts dataColors='["--vz-success", "--vz-primary", "--vz-danger"]' />
            </div>
          </div>
        </CardBody>
      </Card>
    </React.Fragment>
  );
};

export default Revenue;

// Svelte/interactive/src/routes/dashboard/Revenue.svelte
<script>
	import { Card, CardHeader, Row, Col, CardBody } from 'sveltestrap';

	import RevenueCharts from './DashboardEcommerceCharts.svelte';

</script>

<Card>
	<CardHeader class="border-0 align-items-center d-flex">
		<h4 class="card-title mb-0 flex-grow-1">Revenue</h4>
		<div>
			<button type="button" class="btn btn-soft-secondary btn-sm"> ALL </button>
			<button type="button" class="btn btn-soft-secondary btn-sm"> 1M </button>
			<button type="button" class="btn btn-soft-secondary btn-sm"> 6M </button>
			<button type="button" class="btn btn-soft-primary btn-sm"> 1Y </button>
		</div>
	</CardHeader>

	<CardHeader class="p-0 border-0 bg-light-subtle">
		<Row class="g-0 text-center">
			<Col xs={6} sm={3}>
			<div class="p-3 border border-dashed border-start-0">
				<h5 class="mb-1"><span class="counter-value" data-target="7585">0</span></h5>
				<p class="text-muted mb-0">Orders</p>
			</div>
			</Col>
			<Col xs={6} sm={3}>
			<div class="p-3 border border-dashed border-start-0">
				<h5 class="mb-1">$<span class="counter-value" data-target="22.89">0</span>k</h5>
				<p class="text-muted mb-0">Earnings</p>
			</div>
			</Col>
			<Col xs={6} sm={3}>
			<div class="p-3 border border-dashed border-start-0">
				<h5 class="mb-1"><span class="counter-value" data-target="367">0</span></h5>
				<p class="text-muted mb-0">Refunds</p>
			</div>
			</Col>
			<Col xs={6} sm={3}>
			<div class="p-3 border border-dashed border-start-0 border-end-0">
				<h5 class="mb-1 text-success">
					<span class="counter-value" data-target="18.92">0</span>%
				</h5>
				<p class="text-muted mb-0">Conversation Ratio</p>
			</div>
			</Col>
		</Row>
	</CardHeader>

	<CardBody class="p-0 pb-2">
		<div class="w-100">
			<div dir="ltr">
				<RevenueCharts dataColors={["--vz-info", "--vz-primary" , "--vz-danger" ]} />
			</div>
		</div>
	</CardBody>
</Card>
