// Svelte/corporate/src/Layouts/HorizontalLayout.svelte
<script>
	import { onMount } from "svelte";
	import { Col, Collapse, Row } from "sveltestrap";
	import data from "./LayoutMenuData";
	import Link from "svelte-link";
	import { _ } from "svelte-i18n";
	import { browser } from "$app/environment";
	import { page } from "$app/stores";

	const navData = data.Navdata;
	let pathName = "";
	let menuItems = [];
	let splitMenuItems = [];
	let menuSplitContainer = 6;
	navData.forEach(function (value, key) {
		if (value["isHeader"]) {
			menuSplitContainer++;
		}
		if (key >= menuSplitContainer) {
			let val = value;
			val.childItems = value.subItems;
			val.isChildItem = value.subItems ? true : false;
			delete val.subItems;
			splitMenuItems.push(val);
		} else {
			menuItems.push(value);
		}
	});
	menuItems.push({
		id: "more",
		label: "More",
		icon: "ri-briefcase-2-line",
		link: "/#",
		stateVariables: "isMoreMenu",
		subItems: splitMenuItems,
	});

	const initMenu = () => {
		pathName = $page.url.pathname;

		const ul = document.getElementById("navbar-nav");
		const items = ul.getElementsByTagName("a");
		let itemsArray = [...items];
		removeActivation(itemsArray);

		let matchingMenuItem = itemsArray.find((x) => {
			return x.pathname === pathName;
		});

		if (matchingMenuItem) {
			activateParentDropdown(matchingMenuItem);
		}
	};

	onMount(async () => {
		if (browser) {
			window.scrollTo({ top: 0, behavior: "smooth" });
			pathName = $page.url.pathname;

			const initMenu = () => {
				pathName = $page.url.pathname;

				const ul = document.getElementById("navbar-nav");
				const items = ul.getElementsByTagName("a");
				let itemsArray = [...items];
				removeActivation(itemsArray);

				let matchingMenuItem = itemsArray.find((x) => {
					return x.pathname === pathName;
				});

				if (matchingMenuItem) {
					activateParentDropdown(matchingMenuItem);
				}
			};
			initMenu();
		}
	});

	function callInitMenu() {
		initMenu();
	}

	function activateParentDropdown(item) {
		item.classList.add("active");
		let parentCollapseDiv = item.closest(".menu-dropdown");

		if (parentCollapseDiv) {
			// to set aria expand true remaining
			parentCollapseDiv.classList.add("show");
			parentCollapseDiv.parentElement.children[0].classList.add("active");
			parentCollapseDiv.parentElement.children[0].setAttribute(
				"aria-expanded",
				"true"
			);
			if (parentCollapseDiv.parentElement.closest(".menu-dropdown")) {
				parentCollapseDiv.parentElement.closest(".collapse")
					? parentCollapseDiv.parentElement
							.closest(".collapse")
							.classList.add("show")
					: "";
				var parentElementDiv = parentCollapseDiv.parentElement.closest(
					".collapse"
				)
					? parentCollapseDiv.parentElement.closest(".collapse")
							.previousElementSibling
					: "";
				if (parentElementDiv) {
					parentElementDiv.classList.add("active");
					var parentElementSibling =
						parentElementDiv.parentElement.parentElement
							.parentElement.previousElementSibling;
					if (parentElementSibling)
						parentElementSibling.classList.add("active");
				}
				parentCollapseDiv.parentElement
					.closest(".menu-dropdown")
					.parentElement.children[0].classList.add("active");
			}
			return false;
		}
		return false;
	}

	const removeActivation = (items) => {
		let actiItems = items.filter((x) => x.classList.contains("active"));

		actiItems.forEach((item) => {
			if (item.classList.contains("menu-link")) {
				if (!item.classList.contains("active")) {
					item.setAttribute("aria-expanded", false);
				}
				if (item.nextElementSibling) {
					item.nextElementSibling.classList.remove("show");
				}
			}
			if (item.classList.contains("nav-link")) {
				if (item.nextElementSibling) {
					item.nextElementSibling.classList.remove("show");
				}
				item.setAttribute("aria-expanded", false);
			}
			item.classList.remove("active");
		});
	};
</script>
<svelte:head>
	<script src="//unpkg.com/simplebar@latest/dist/simplebar.min.js"></script>
	<script src="//cdn.jsdelivr.net/npm/simplebar@latest/dist/simplebar.min.js"></script>
</svelte:head>

{#each menuItems as item}
	{#if !item.isHeader}
		{#if item.subItems}
			<li class="nav-item">
				<a
					class="nav-link menu-link"
					href={item.link ? item.link : "/#"}
					data-bs-toggle="collapse"
					id={item.stateVariables}
				>
					<i class={item.icon} />
					<span data-key="t-apps">{$_(item.label)}</span>
				</a>
				<Collapse
					class={item.subItems.length > 16
						? "menu-dropdown mega-dropdown-menu"
						: "menu-dropdown"}
					toggler="#{item.stateVariables}"
					isOpen={item.stateVariables}
				>
					{#if item.subItems.length > 16}
						<Row>
							{#each item.subItems as subItem, index (index)}
								{#if index % 2 === 0}
									<Col lg={4}>
										<ul class="nav nav-sm flex-column">
											<li class="nav-item">
												<a
													href={subItem.link}
													class="nav-link"
													on:click={callInitMenu}
													>{$_(subItem.label)}</a
												>
											</li>
										</ul>
									</Col>
								{:else}
									<Col lg={4}>
										<ul class="nav nav-sm flex-column">
											<li class="nav-item">
												<a
													href={subItem.link}
													class="nav-link"
													on:click={callInitMenu}
													>{$_(subItem.label)}</a>
											</li>
										</ul>
									</Col>
								{/if}
							{/each}
						</Row>
					{:else}
						<ul class="nav nav-sm flex-column">
							{#each item.subItems as subItem, index (index)}
								{#if !subItem.isChildItem}
									<li class="nav-item">
										<a
											on:click={callInitMenu}
											href={subItem.link
												? subItem.link
												: "/#"}
											class="nav-link"
										>
											{$_(subItem.label)}
										</a>
									</li>
								{:else}
									<li class="nav-item">
										<a
											class="nav-link not"
											href="{null}"
											id={subItem.stateVariables}
											data-bs-toggle="collapse"
											on:click={callInitMenu}
										>
											{$_(subItem.label)}
										</a>
										<Collapse
											class="menu-dropdown"
											toggler="#{subItem.stateVariables}"
											isOpen={subItem.stateVariables}
										>
											<ul class="nav nav-sm flex-column">
												{#if subItem.childItems}
													{#each subItem.childItems as subChildItem}
														{#if !subChildItem.isChildItem}
															<li
																class="nav-item"
															>
																<a
																	href={subChildItem.link
																		? subChildItem.link
																		: "/#"}
																	on:click={callInitMenu}
																	class="nav-link not open"
																>
																	{$_(
																		subChildItem.label
																	)}
																</a>
															</li>
														{:else}
															<li
																class="nav-item"
															>
																<a
																	class="nav-link iopen"
																	href="{null}"
																	data-bs-toggle="collapse"
																	id={subChildItem.stateVariables}
																	on:click={callInitMenu}
																>
																	{$_(
																		subChildItem.label
																	)}
																</a>
																<Collapse
																	class="menu-dropdown"
																	toggler="#{subChildItem.stateVariables}"
																	isOpen={subChildItem.stateVariables}
																>
																	<ul
																		class="nav nav-sm flex-column"
																	>
																		{#if subChildItem.childItems}
																			{#each subChildItem.childItems as subSubChildItem}
																				<li
																					class="nav-item apex"
																				>
																					<a
																						on:click={callInitMenu}
																						href={subSubChildItem.link
																							? subSubChildItem.link
																							: "/#"}
																						class="nav-link"
																					>
																						{$_(
																							subSubChildItem.label
																						)}
																					</a>
																				</li>
																			{/each}
																		{/if}
																	</ul>
																</Collapse>
															</li>
														{/if}
													{/each}
												{/if}
											</ul>
										</Collapse>
									</li>
								{/if}
							{/each}
						</ul>
					{/if}
				</Collapse>
			</li>
		{:else}
			<li class="nav-item">
				<a
					class="nav-link menu-link"
					href={item.link ? item.link : "/#"}
				>
					<i class={item.icon} /> <span>{$_(item.label)}</span>
				</a>
			</li>
		{/if}
	{:else}
		<li class="menu-title">
			<span data-key="t-menu">{$_(item.label)}</span>
		</li>
	{/if}
{/each}

// React+Inertia/Saas/resources/js/Layouts/HorizontalLayout/index.tsx
import React, { useEffect, useState } from 'react';
import PropTypes from "prop-types";
import { Col, Collapse, Row } from 'react-bootstrap';

// Import Data
import navdata from "../LayoutMenuData";
//i18n
import { withTranslation } from "react-i18next";
import { Link } from '@inertiajs/react';

const HorizontalLayout = (props: any) => {
    const [isMoreMenu, setIsMoreMenu] = useState<boolean>(false);
    const navData = navdata().props.children;
    let menuItems: any = [];
    let splitMenuItems: Array<any> = [];
    let menuSplitContainer = 6;
    navData.forEach(function (value: any, key: number) {
        if (value['isHeader']) {
            menuSplitContainer++;
        }
        if (key >= menuSplitContainer) {
            let val = value;
            val.childItems = value.subItems;
            val.isChildItem = (value.subItems) ? true : false;
            delete val.subItems;
            splitMenuItems.push(val);
        } else {
            menuItems.push(value);
        }
    });
    menuItems.push({ id: 'more', label: 'More', icon: 'ri-briefcase-2-line', link: "/#", stateVariables: isMoreMenu, subItems: splitMenuItems, click: function (e: any) { e.preventDefault(); setIsMoreMenu(!isMoreMenu); }, });

    const path = window.location.pathname;

    useEffect(() => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
        const initMenu = () => {
            const pathName = path;
            const ul = document.getElementById("navbar-nav") as HTMLElement;
            const items: any = ul.getElementsByTagName("a");
            let itemsArray = [...items]; // converts NodeList to Array
            removeActivation(itemsArray);
            let matchingMenuItem = itemsArray.find((x) => {
                return x.pathname === pathName;
            });
            if (matchingMenuItem) {
                activateParentDropdown(matchingMenuItem);
            }
        };
        initMenu();
    }, [path, props.layoutType]);

    function activateParentDropdown(item: any) {
        item.classList.add("active");
        let parentCollapseDiv = item.closest(".collapse.menu-dropdown");

        if (parentCollapseDiv) {

            // to set aria expand true remaining
            parentCollapseDiv.classList.add("show");
            parentCollapseDiv.parentElement.children[0].classList.add("active");
            parentCollapseDiv.parentElement.children[0].setAttribute("aria-expanded", "true");
            if (parentCollapseDiv.parentElement.closest(".collapse.menu-dropdown")) {
                parentCollapseDiv.parentElement.closest(".collapse").classList.add("show");
                var parentElementDiv = parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling;
                if (parentElementDiv)
                    if (parentElementDiv.closest(".collapse"))
                        parentElementDiv.closest(".collapse").classList.add("show");
                parentElementDiv.classList.add("active");
                var parentElementSibling = parentElementDiv.parentElement.parentElement.parentElement.previousElementSibling;
                if (parentElementSibling) {
                    parentElementSibling.classList.add("active");
                }
            }
            return false;
        }
        return false;
    }

    const updatedMenu = (item: any) => (event: any) => {
        event.preventDefault();
        const anchorTag = event.target.closest('a');
        anchorTag.classList.add("active");

        let parentCollapseDiv = anchorTag.nextElementSibling;
        if (parentCollapseDiv) {
            // Add 'show' class to the clicked menu's parent collapse div
            parentCollapseDiv.classList.toggle("show");

            // Set aria-expanded attribute
            const isExpanded = parentCollapseDiv.classList.contains("show");
            anchorTag.setAttribute("aria-expanded", isExpanded ? "true" : "false");

            // Add 'active' class to the clicked menu's parent element
            parentCollapseDiv.parentElement.children[0].classList.add("active");

            // Additional logic to handle parent collapses
            if (parentCollapseDiv.parentElement.closest(".collapse.menu-dropdown")) {
                parentCollapseDiv.parentElement.closest(".collapse").classList.add("show");
                if (parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling)
                    parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling.classList.add("active");
                if (parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling.closest(".collapse")) {
                    parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling.closest(".collapse").classList.add("show");
                    parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling.closest(".collapse").previousElementSibling.classList.add("active");
                }
            }
            return false;
        }
        return false;
    };

    const removeActivation = (items: any) => {
        let actiItems = items.filter((x: any) => x.classList.contains("active"));

        actiItems.forEach((item: any) => {
            if (item.classList.contains("menu-link")) {
                if (!item.classList.contains("active")) {
                    item.setAttribute("aria-expanded", false);
                }
                if (item.nextElementSibling) {
                    item.nextElementSibling.classList.remove("show");
                }
            }
            if (item.classList.contains("nav-link")) {
                if (item.nextElementSibling) {
                    item.nextElementSibling.classList.remove("show");
                }
                item.setAttribute("aria-expanded", false);
            }
            item.classList.remove("active");
        });
    };
    return (
        <React.Fragment>
            {(menuItems || []).map((item: any, key: number) => {
                return (
                    <React.Fragment key={key}>
                        {/* Main Header */}
                        {!item['isHeader'] ?
                            (item.subItems ? (
                                <li className="nav-item">
                                    <Link
                                        onClick={updatedMenu(item)}
                                        className="nav-link menu-link"
                                        href={item.link ? item.link : "/#"}
                                        data-bs-toggle="collapse"
                                    >
                                        <i className={item.icon}></i> <span data-key="t-apps">{props.t(item.label)}</span>
                                    </Link>
                                    <Collapse
                                        className={item.id === "baseUi" && item.subItems.length > 13 ? "menu-dropdown mega-dropdown-menu" : "menu-dropdown"}
                                        in={item.stateVariables}
                                    >
                                        {/* subItms  */}
                                        {item.id === "baseUi" && item.subItems.length > 13 ? (
                                            <React.Fragment>
                                                <div className='menu-dropdown mega-dropdown-menu'>
                                                    <Row>
                                                        {item.subItems && ((item.subItems || []).map((subItem: any, key: number) => (
                                                            <React.Fragment key={key}>
                                                                {key % 2 === 0 ? (
                                                                    <Col lg={4}>
                                                                        <ul className="nav nav-sm flex-column">
                                                                            <li className="nav-item">
                                                                                <Link href={item.subItems[key].link} className="nav-link">{item.subItems[key].label}</Link>
                                                                            </li>
                                                                        </ul>
                                                                    </Col>
                                                                ) : (
                                                                    <Col lg={4}>
                                                                        <ul className="nav nav-sm flex-column">
                                                                            <li className="nav-item">
                                                                                <Link href={item.subItems[key].link} className="nav-link">{item.subItems[key].label}</Link>
                                                                            </li>
                                                                        </ul>
                                                                    </Col>
                                                                )
                                                                }
                                                            </React.Fragment>
                                                        ))
                                                        )}
                                                    </Row>
                                                </div>
                                            </React.Fragment>
                                        ) : (
                                            <ul className="nav nav-sm flex-column test">
                                                {item.subItems && ((item.subItems || []).map((subItem: any, key: number) => (
                                                    <React.Fragment key={key}>
                                                        {!subItem.isChildItem ? (
                                                            <li className="nav-item">
                                                                <Link
                                                                    href={subItem.link ? subItem.link : "/#"}
                                                                    className="nav-link"
                                                                >
                                                                    {props.t(subItem.label)}
                                                                </Link>
                                                            </li>
                                                        ) : (
                                                            <li className="nav-item">
                                                                <Link
                                                                    onClick={updatedMenu(subItem)}
                                                                    className="nav-link"
                                                                    href="/#"
                                                                    data-bs-toggle="collapse"
                                                                > {props.t(subItem.label)}
                                                                </Link>
                                                                <Collapse className="menu-dropdown" in={subItem.stateVariables} >
                                                                    <ul className="nav nav-sm flex-column" id="sidebarEcommerce">
                                                                        {/* child subItms  */}
                                                                        {subItem.childItems && (
                                                                            (subItem.childItems || []).map((subChildItem: any, key: number) => (
                                                                                <React.Fragment key={key}>
                                                                                    {!subChildItem.isChildItem ? (
                                                                                        <li className="nav-item">
                                                                                            <Link
                                                                                                href={subChildItem.link ? subChildItem.link : "/#"}
                                                                                                className="nav-link"
                                                                                            >
                                                                                                {props.t(subChildItem.label)}
                                                                                            </Link>
                                                                                        </li>
                                                                                    ) : (
                                                                                        <li className="nav-item">
                                                                                            <Link
                                                                                                onClick={updatedMenu(subChildItem)}
                                                                                                className="nav-link"
                                                                                                href="/#"
                                                                                                data-bs-toggle="collapse"
                                                                                            > {props.t(subChildItem.label)}
                                                                                            </Link>
                                                                                            <Collapse className="menu-dropdown" in={subChildItem.stateVariables} >
                                                                                                <ul className="nav nav-sm flex-column" id="sidebarEcommerce">
                                                                                                    {/* child subItms  */}
                                                                                                    {subChildItem.childItems && (
                                                                                                        (subChildItem.childItems || []).map((subSubChildItem: any, key: number) => (
                                                                                                            <li className="nav-item apex" key={key}>
                                                                                                                <Link
                                                                                                                    href={subSubChildItem.link ? subSubChildItem.link : "/#"}
                                                                                                                    className="nav-link"
                                                                                                                >
                                                                                                                    {props.t(subSubChildItem.label)}
                                                                                                                </Link>
                                                                                                            </li>
                                                                                                        ))
                                                                                                    )}
                                                                                                </ul>
                                                                                            </Collapse>
                                                                                        </li>
                                                                                    )}
                                                                                </React.Fragment>
                                                                            ))
                                                                        )}
                                                                    </ul>
                                                                </Collapse>
                                                            </li>
                                                        )}
                                                    </React.Fragment>
                                                ))
                                                )}
                                            </ul>
                                        )}
                                    </Collapse>
                                </li>
                            ) : (
                                <li className="nav-item">
                                    <Link
                                        className="nav-link menu-link"
                                        href={item.link ? item.link : "/#"}>
                                        <i className={item.icon}></i> <span>{props.t(item.label)}</span>
                                    </Link>
                                </li>
                            ))
                            : (<li className="menu-title"><span data-key="t-menu">{props.t(item.label)}</span></li>)}
                    </React.Fragment>
                );
            })}
            {/* menu Items */}
        </React.Fragment >
    );
};

HorizontalLayout.propTypes = {
    location: PropTypes.object,
    t: PropTypes.any,
};

export default withTranslation()(HorizontalLayout);
