// Angular/interactive/src/app/pages/nft-marketplace/creators/creators.component.ts
import { Component } from '@angular/core';
import { creatorsModel, creatorsListModel } from './creators.model';
import { PaginationService } from 'src/app/core/services/pagination.service';
import { creatorsData, creatorsListData } from 'src/app/core/data';


@Component({
  selector: 'app-creators',
  templateUrl: './creators.component.html',
  styleUrls: ['./creators.component.scss'],
})

/**
 * Creators Component
 */
export class CreatorsComponent {
  // bread crumb items
  breadCrumbItems!: Array<{}>;
  creatorsData!: creatorsModel[];
  searchResults!: any[];
  searchTerm: any;
  creatorsListData!: any[];
  allcreatorsListData!: any[]

  constructor(public service: PaginationService) {
    this.service.pageSize = 10;
  }


  ngOnInit(): void {
    /**
    * BreadCrumb
    */
    this.breadCrumbItems = [
      { label: 'NFT Marketplace' },
      { label: 'Creators', active: true }
    ];
    // FetchData
    this.creatorsData = creatorsData;
    this.creatorsListData = creatorsListData;
    this.allcreatorsListData = creatorsListData;
  }
  // Pagination
  changePage() {
    this.creatorsListData = this.service.changePage(this.allcreatorsListData)
  }

  // Search Data
  performSearch(): void {
    this.searchResults = creatorsListData.filter((item: any) => {
      return (
        item.title.toLowerCase().includes(this.searchTerm.toLowerCase())
      );
    });
    this.creatorsListData = this.service.changePage(this.searchResults)
  }
}

<!-- Start Breadcrumbs -->
<app-breadcrumbs title="Creators" [breadcrumbItems]="breadCrumbItems"></app-breadcrumbs>
<!-- End Breadcrumbs -->

<div class="row g-4 mb-3 justify-content-between">
    <div class="col-sm-auto">
        <div>
            <a routerLink="/projects/create" class="btn btn-success"><i class="ri-add-line align-bottom me-1"></i> Add
                New</a>
        </div>
    </div>
    <div class="col-sm-auto">
        <div class="d-flex justify-content-sm-end gap-2">
            <div class="search-box ms-2">
                <input type="text" class="form-control search" placeholder="Search..." [(ngModel)]="searchTerm">
                <i class="ri-search-line search-icon"></i>
            </div>

            <select class="form-control w-md" data-choices data-choices-search-false>
                <option value="All">All</option>
                <option value="Today">Today</option>
                <option value="Yesterday" selected>Yesterday</option>
                <option value="Last 7 Days">Last 7 Days</option>
                <option value="Last 30 Days">Last 30 Days</option>
                <option value="This Month">This Month</option>
                <option value="Last Year">Last Year</option>
            </select>
        </div>
    </div>
    <!--end col-->
</div>
<!--end row-->

<div class="row">
    @for(data of creatorsData;track $index){
    <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="card">
            <div class="card-body">
                <div class="d-flex">
                    <div class="flex-shrink-0">
                        <img src="{{data.img}}" alt="" class="avatar-sm object-fit-cover rounded">
                    </div>
                    <div class="ms-3 flex-grow-1">
                        <a routerLink="/pages/profile">
                            <h5 class="mb-1">{{data.title}}</h5>
                        </a>
                        <p class="text-muted mb-0"><i class="mdi mdi-ethereum text-primary fs-14"></i> {{data.price}}
                        </p>
                    </div>
                    <div>
                        <div class="dropdown float-end" ngbDropdown>
                            <button class="btn btn-ghost-primary btn-icon dropdown arrow-none" type="button" data-bs-toggle="dropdown" aria-expanded="false" ngbDropdownToggle>
                                <i class="ri-more-fill align-middle fs-16"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end" ngbDropdownMenu>
                                <li><a class="dropdown-item view-item-btn" href="javascript:void(0);">Share</a></li>
                                <li><a class="dropdown-item edit-item-btn" href="javascript:void(0);" data-bs-toggle="modal">Report</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    }
    <!--end col-->
</div>
<!--end row-->

<div class="row">
    <div class="col-lg-12">
        <h5 class="card-title mb-4 fw-semibold fs-16">Creators Grid Lists</h5>
    </div>
</div>

<div class="row row-cols-xl-5 row-cols-lg-3 row-cols-md-2 row-cols-1">
    @for ( data of creatorsListData; track $index) {
    <div class="col">
        <div class="card">
            <img src="{{data.cardImg}}" alt="" class="object-fit-cover card-img-top" height="120">
            <div class="card-body text-center">
                <img src="{{data.img}}" alt="" class="avatar-md rounded-circle object-fit-cover mt-n5 img-thumbnail border-light mx-auto d-block">
                <a routerLink="/pages/profile">
                    <h5 class="mt-2 mb-1">{{data.title}}</h5>
                </a>
                <p class="text-muted mb-2">{{data.products}} Products</p>
                <p class="text-muted">{{data.content}}</p>
                <button class="btn w-100" [ngClass]="{'btn-success': data.isFollowBtn === true, 'btn-soft-success': data.isFollowBtn !== true}">{{data.followbtn}}</button>
            </div>
        </div>
    </div>}
    <!--end col-->
</div>
<!--end row-->

<div class="row g-0 text-center text-sm-start align-items-center mb-4">
    <div class="col-sm-6">
        <div>
            <p class="mb-sm-0 text-muted">
                Showing
                1 to
                10 of {{allcreatorsListData.length}}
                entries
            </p>
        </div>
    </div>
    <!-- end col -->
    <div class="col-sm-6">
        <!-- Pagination -->
        <div class="text-sm-right float-sm-end listjs-pagination">
            <ngb-pagination [collectionSize]="allcreatorsListData.length" [(page)]="service.page" [pageSize]="service.pageSize" (pageChange)="changePage()"></ngb-pagination>
        </div>
        <!-- End Pagination -->
    </div><!-- end col -->
</div>

// React+Inertia/Corporate/resources/js/Pages/NFTMarketplace/Creators/index.tsx
import React, { Children } from "react";
import { Button, Card, Col, Container, Dropdown, Row,} from "react-bootstrap";
import BreadCrumb from "../../../Components/Common/BreadCrumb";

import { creatorsData, creatorsListData } from "../../../common/data/index";
import { Head, Link } from "@inertiajs/react";
import Layout from "../../../Layouts";

const Creators = () => {
    return (
        <React.Fragment>
            <Head title = "Creators | Velzon - React Admin & Dashboard Template"/>
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="Creators" pageTitle="NFT Marketplace" />
                    <Row className="g-4 mb-3">
                        <Col className="col-sm-auto">
                            <div>
                                <Link href="/apps-projects-create" className="btn btn-secondary"><i className="ri-add-line align-bottom me-1"></i> Add New</Link>
                            </div>
                        </Col>
                        <Col className="col-sm">
                            <div className="d-flex justify-content-sm-end gap-2">
                                <div className="search-box ms-2">
                                    <input type="text" className="form-control" placeholder="Search..." />
                                    <i className="ri-search-line search-icon"></i>
                                </div>
                                <div className="choices">
                                    <select className="form-control w-md" data-choices data-choices-search-false>
                                        <option value="All">All</option>
                                        <option value="Today">Today</option>
                                        <option value="Yesterday" defaultValue=''>Yesterday</option>
                                        <option value="Last 7 Days">Last 7 Days</option>
                                        <option value="Last 30 Days">Last 30 Days</option>
                                        <option value="This Month">This Month</option>
                                        <option value="Last Year">Last Year</option>
                                    </select>
                                </div>
                            </div>
                        </Col>
                    </Row>

                    <Row>
                        {creatorsData.map((item, key) => (
                            <Col key={key} xl={3} lg={4} md={6}>
                                <Card>
                                    <Card.Body>
                                        <div className="d-flex">
                                            <div className="flex-shrink-0">
                                                <img src={item.img} alt="" className="avatar-sm object-fit-cover rounded" />
                                            </div>
                                            <div className="ms-3 flex-grow-1">
                                                <Link href="/pages-profile">
                                                    <h5 className="mb-1">{item.title}</h5>
                                                </Link>
                                                <p className="text-muted mb-0"><i className="mdi mdi-ethereum text-primary fs-14"></i> {item.price}</p>
                                            </div>
                                            <div>
                                                <Dropdown dir="start" className="float-end">
                                                    <Dropdown.Toggle as="button" className="btn btn-ghost-primary btn-icon arrow-none">
                                                        <i className="ri-more-fill align-middle fs-16"></i>
                                                    </Dropdown.Toggle>
                                                    <Dropdown.Menu className="dropdown-menu-end">
                                                        <Dropdown.Item className="view-item-btn">Share</Dropdown.Item>
                                                        <Dropdown.Item className="edit-item-btn">Report</Dropdown.Item>
                                                    </Dropdown.Menu>
                                                </Dropdown>
                                            </div>
                                        </div>
                                    </Card.Body>
                                </Card>
                            </Col>
                        ))}
                    </Row>

                    <Row>
                        <Col lg={12}>
                            <h5 className="card-title mb-4 fw-semibold fs-16">Creators Grid Lists</h5>
                        </Col>
                    </Row>

                    <Row className="row-cols-xl-5 row-cols-lg-3 row-cols-md-2 row-cols-1">
                        {creatorsListData.map((item, key) => (
                            <Col key={key}>
                                <Card>
                                    <img src={item.cardImg} alt="" className="object-fit-cover card-img-top" height="120" />
                                    <div className="card-body text-center">
                                        <img src={item.img} alt="" className="avatar-md rounded-circle object-fit-cover mt-n5 img-thumbnail border-light mx-auto d-block" />
                                        <Link href="/pages-profile">
                                            <h5 className="mt-2 mb-1">{item.title}</h5>
                                        </Link>
                                        <p className="text-muted mb-2">{item.products} Products</p>
                                        <p className="text-muted">You can make an NFT of a digital painting, a text, a piece of music, a video.</p>
                                        <button className={item.isFollowBtn ? "btn btn-primary w-100" : "btn btn-soft-primary w-100"}>{item.isFollowBtn ? "Follow" : "UnFollow"} </button>
                                    </div>
                                </Card>
                            </Col>
                        ))}
                    </Row>


                    <Row className="g-0 text-center text-sm-start align-items-center mb-4">
                        <Col sm={6}>
                            <div>
                                <p className="mb-sm-0 text-muted">Showing <span className="fw-semibold">1</span> to <span className="fw-semibold">10</span> of <span className="fw-semibold text-decoration-underline">12</span> entries</p>
                            </div>
                        </Col>

                        <Col sm={6}>
                            <ul className="pagination pagination-separated justify-content-center justify-content-sm-end mb-sm-0">
                                <li className="page-item disabled">
                                    <Button variant="link" className="page-link">Previous</Button>
                                </li>
                                <li className="page-item active">
                                    <Button variant="link" className="page-link">1</Button>
                                </li>
                                <li className="page-item ">
                                    <Button variant="link" className="page-link">2</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">3</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">4</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">5</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">Next</Button>
                                </li>
                            </ul>
                        </Col>
                    </Row>
                </Container>
            </div>
        </React.Fragment>
    );
};
Creators.layout = (page:any) => <Layout children={page}/>
export default Creators;
