// Svelte/interactive/src/routes/crypto/mywallet/+page.svelte
<script>
	import BreadCrumb from "../../../Components/Common/BreadCrumb.svelte";
	import { Col, Container, Row } from "sveltestrap";
	import Watchlist from "./Watchlist.svelte";
	import PortfolioStatistics from "./PortfolioStatistics.svelte";
	import MarketStatus from "./MarketStatus.svelte";
	import Widgets from "./Widgets.svelte";
	import RecentTransaction from "./RecentTransaction.svelte";
</script>

<svelte:head>
	<title>My Wallet | Velzon - Svelte Admin & Dashboard Template</title>
</svelte:head>

<div class="page-content">
	<Container fluid>
		<BreadCrumb title="My Wallet" pageTitle="Crypto" />
		<Row>
			<Col xxl={9}>
				<PortfolioStatistics dataColors={["--vz-primary"]} />
				<Watchlist />
				<MarketStatus />
			</Col>
			<Col xxl={3}>
				<Widgets />
				<RecentTransaction />
			</Col>
		</Row>
	</Container>
</div>

// React+Inertia/Minimal/resources/js/Pages/Crypto/MyWallet/index.tsx
import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';
import BreadCrumb from '../../../Components/Common/BreadCrumb';
import Watchlist from './Watchlist';
import PortfolioStatistics from './PortfolioStatistics';
import MarketStatus from './MarketStatus';
import Widgets from './Widgets';
import RecentTransaction from './RecentTransaction';
import { Head } from '@inertiajs/react';
import Layout from '../../../Layouts';


const MyWallet = () => {
    return (
        <React.Fragment>
            <Head title="My Wallet | Velzon - React Admin & Dashboard Template"/>
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="My Wallet" pageTitle="Crypto" />
                    <Row>
                        <Col xxl={9}>
                            <PortfolioStatistics dataColors='["--vz-primary"]' />
                            <Watchlist />
                            <MarketStatus />
                        </Col>
                        <Col xxl={3}>
                            <Widgets />
                            <RecentTransaction />
                        </Col>
                    </Row>
                </Container>
            </div>
        </React.Fragment>
    );
};
MyWallet.layout = (page:any) => <Layout children={page}/>
export default MyWallet;
