// Svelte/creative/src/routes/landing/NFTLanding/footer.svelte
<script>
    import Link from 'svelte-link';
import { Col, Container, Row } from 'sveltestrap';

// Import Images
import logolight from "../../../assets/images/logo-light.png";
</script>
<footer class="custom-footer bg-dark py-5 position-relative">
    <Container>
        <Row>
            <Col lg={4} class="mt-4">
                <div>
                    <div>
                        <img src={logolight} alt="logo light" height="17" />
                    </div>
                    <div class="mt-4">
                        <p>Premium Multipurpose Admin & Dashboard Template</p>
                        <p>You can build any type of web application like eCommerce, CRM, CMS, Project management apps, Admin Panels, etc using Velzon.</p>
                    </div>
                </div>
            </Col>

            <Col lg={7} class="ms-lg-auto">
                <Row>
                    <Col sm={4} class="mt-4">
                        <h5 class="text-white mb-0">Company</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list fs-15">
                                <li><Link href="/pages/profile/simple">About Us</Link></li>
                                <li><Link href="/pages/gallery/pages-gallery">Gallery</Link></li>
                                <li><Link href="/projects/apps-projects-overview">Projects</Link></li>
                                <li><Link href="/pages/timeline/timeline">Timeline</Link></li>
                            </ul>
                        </div>
                    </Col>
                    <Col sm={4} class="mt-4">
                        <h5 class="text-white mb-0">Apps Pages</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list fs-15">
                                <li><Link href="/pages/pricing/pages-pricing">Calendar</Link></li>
                                <li><Link href="/emailInbox/apps-mailbox">Mailbox</Link></li>
                                <li><Link href="/apps-chat">Chat</Link></li>
                                <li><Link href="/crm/apps-crm-deals">Deals</Link></li>
                                <li><Link href="/tasks/apps-tasks-kanban">Kanban Board</Link></li>
                            </ul>
                        </div>
                    </Col>
                    <Col sm={4} class="mt-4">
                        <h5 class="text-white mb-0">Support</h5>
                        <div class="text-muted mt-3">
                            <ul class="list-unstyled ff-secondary footer-list fs-15">
                                <li><Link href="/pages/faqs">FAQ</Link></li>
                                <li><Link href="/crm/apps-crm-contacts">Contact</Link></li>
                            </ul>
                        </div>
                    </Col>
                </Row>
            </Col>

        </Row>

        <Row class="text-center text-sm-start align-items-center mt-5">
            <Col sm={6}>

                <div>
                    <p class="copy-rights mb-0">
                        {new Date().getFullYear()} © Velzon - Themesbrand
                    </p>
                </div>
            </Col>
            <Col sm={6}>
                <div class="text-sm-end mt-3 mt-sm-0">
                    <ul class="list-inline mb-0 footer-social-link">
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-facebook-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-github-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-linkedin-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-google-fill"></i>
                                </div>
                            </Link>
                        </li>
                        <li class="list-inline-item">
                            <Link href={null} class="avatar-xs d-block">
                                <div class="avatar-title rounded-circle">
                                    <i class="ri-dribbble-line"></i>
                                </div>
                            </Link>
                        </li>
                    </ul>
                </div>
            </Col>
        </Row>
    </Container>
</footer>

// React+Inertia/Interactive/resources/js/Pages/Landing/OnePage/footer.tsx
import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';

// Import Images
import logolight from "../../../../images/logo-light.png";
import { Link } from '@inertiajs/react';


const Footer = () => {
    return (
        <React.Fragment>
            <footer className="custom-footer bg-dark py-5 position-relative">
                <Container>
                    <Row>
                        <Col lg={4} className="mt-4">
                            <div>
                                <div>
                                    <img src={logolight} alt="logo light" height="17" />
                                </div>
                                <div className="mt-4">
                                    <p>Premium Multipurpose Admin & Dashboard Template</p>
                                    <p className="ff-secondary">You can build any type of web application like eCommerce, CRM, CMS, Project
                                        management apps, Admin Panels, etc using Velzon.</p>
                                </div>
                            </div>
                        </Col>

                        <Col lg={7} className="ms-lg-auto">
                            <Row>
                                <Col sm={4} className="mt-4">
                                    <h5 className="text-white mb-0">Company</h5>
                                    <div className="text-muted mt-3">
                                        <ul className="list-unstyled ff-secondary footer-list">
                                            <li><Link href="/pages-profile">About Us</Link></li>
                                            <li><Link href="/pages-gallery">Gallery</Link></li>
                                            <li><Link href="/apps-projects-overview">Projects</Link></li>
                                            <li><Link href="/pages-timeline">Timeline</Link></li>
                                        </ul>
                                    </div>
                                </Col>
                                <Col sm={4} className="mt-4">
                                    <h5 className="text-white mb-0">Apps Pages</h5>
                                    <div className="text-muted mt-3">
                                        <ul className="list-unstyled ff-secondary footer-list">
                                            <li><Link href="/pages-pricing">Calendar</Link></li>
                                            <li><Link href="/apps-mailbox">Mailbox</Link></li>
                                            <li><Link href="/apps-chat">Chat</Link></li>
                                            <li><Link href="/apps-crm-deals">Deals</Link></li>
                                            <li><Link href="#">Kanban Board</Link></li>
                                        </ul>
                                    </div>
                                </Col>
                                <Col sm={4} className="mt-4">
                                    <h5 className="text-white mb-0">Support</h5>
                                    <div className="text-muted mt-3">
                                        <ul className="list-unstyled ff-secondary footer-list">
                                            <li><Link href="/pages-faqs">FAQ</Link></li>
                                            <li><Link href="/pages-faqs">Contact</Link></li>
                                        </ul>
                                    </div>
                                </Col>
                            </Row>
                        </Col>

                    </Row>

                    <Row className="text-center text-sm-start align-items-center mt-5">
                        <Col sm={6}>

                            <div>
                                <p className="copy-rights mb-0">
                                    {new Date().getFullYear()} © Velzon - Themesbrand
                                </p>
                            </div>
                        </Col>
                        <Col sm={6}>
                            <div className="text-sm-end mt-3 mt-sm-0">
                                <ul className="list-inline mb-0 footer-social-link">
                                    <li className="list-inline-item">
                                        <Link href="#" className="avatar-xs d-block">
                                            <div className="avatar-title rounded-circle">
                                                <i className="ri-facebook-fill"></i>
                                            </div>
                                        </Link>
                                    </li>
                                    <li className="list-inline-item">
                                        <Link href="#" className="avatar-xs d-block">
                                            <div className="avatar-title rounded-circle">
                                                <i className="ri-github-fill"></i>
                                            </div>
                                        </Link>
                                    </li>
                                    <li className="list-inline-item">
                                        <Link href="#" className="avatar-xs d-block">
                                            <div className="avatar-title rounded-circle">
                                                <i className="ri-linkedin-fill"></i>
                                            </div>
                                        </Link>
                                    </li>
                                    <li className="list-inline-item">
                                        <Link href="#" className="avatar-xs d-block">
                                            <div className="avatar-title rounded-circle">
                                                <i className="ri-google-fill"></i>
                                            </div>
                                        </Link>
                                    </li>
                                    <li className="list-inline-item">
                                        <Link href="#" className="avatar-xs d-block">
                                            <div className="avatar-title rounded-circle">
                                                <i className="ri-dribbble-line"></i>
                                            </div>
                                        </Link>
                                    </li>
                                </ul>
                            </div>
                        </Col>
                    </Row>
                </Container>
            </footer>
        </React.Fragment >
    );
};

export default Footer;
