// Angular/creative/src/app/pages/nft-marketplace/ranking/ranking.component.ts
import { Component } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { UntypedFormBuilder } from '@angular/forms';

import { rankingModel } from './ranking.model';
import { rankingData } from 'src/app/core/data';
import { PaginationService } from 'src/app/core/services/pagination.service';

@Component({
  selector: 'app-ranking',
  templateUrl: './ranking.component.html',
  styleUrls: ['./ranking.component.scss'],
})

/**
 * Ranking Component
 */
export class RankingComponent {
  // bread crumb items
  breadCrumbItems!: Array<{}>;

  // Table data
  rankingData!: rankingModel[];
  searchResults: any;
  searchTerm: any;
  allrankingData!: any[];
  constructor(private modalService: NgbModal, public service: PaginationService, private formBuilder: UntypedFormBuilder) {
  }

  ngOnInit(): void {
    /**
   * BreadCrumb
   */
    this.breadCrumbItems = [
      { label: 'NFT Marketplace' },
      { label: 'Ranking', active: true }
    ];
    // FetchData
    this.allrankingData = rankingData
    this.rankingData = this.service.changePage(rankingData)
  }

  // Pagination
  changePage() {
    this.rankingData = this.service.changePage(this.rankingData)
  }

  // Sort Data
  onSort(column: any) {
    this.rankingData = this.service.onSort(column, this.rankingData)
  }

  // Search Data
  performSearch(): void {
    this.searchResults = rankingData.filter((item: any) => {
      return (
        item.ranking.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        item.collection.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        item.volume_price.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        item.item.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        item.floor_price.toLowerCase().includes(this.searchTerm.toLowerCase())
      );
    });
    this.rankingData = this.service.changePage(this.searchResults)
  }

}

<!-- Start Breadcrumbs -->
<app-breadcrumbs title="Ranking" [breadcrumbItems]="breadCrumbItems"></app-breadcrumbs>
<!-- End Breadcrumbs -->

<div class="row">
    <div class="col-lg-12">
        <div class="card" id="contactList">
            <div class="card-header">
                <div class="d-flex align-items center">
                    <h5 class="card-title mb-0 flex-grow-1">The top NFTs ranking on Velzon</h5>
                    <p class="text-muted mb-0">Updated: 28 April, 2022 08:05:00</p>
                </div>
            </div>
            <div class="card-body">
                <div class="row justify-content-between g-3">
                    <div class="col-xxl-3 col-sm-6">
                        <div class="search-box">
                            <input type="text" class="form-control search" placeholder="Search for ..." [(ngModel)]="searchTerm" (ngModelChange)="performSearch()">
                            <i class="ri-search-line search-icon"></i>
                        </div>
                    </div>
                    <!--end col-->
                    <div class="col-xxl-2 col-sm-4">
                        <div>
                            <select class="form-control" data-choices data-choices-search-false name="choices-single-default" id="idStatus">
                                <option value="All Time" selected>All Time</option>
                                <option value="1 Day">1 Day</option>
                                <option value="7 Days">7 Days</option>
                                <option value="15 Days">15 Days</option>
                                <option value="1 Month">1 Month</option>
                                <option value="6 Month">6 Month</option>
                            </select>
                        </div>
                    </div>
                    <!--end col-->
                </div><!--end row-->
            </div>
            <div class="card-body">
                <div class="table-responsive table-card">
                    <table class="table align-middle table-nowrap table-hover" id="customerTable">
                        <thead class="table-light text-muted">
                            <tr>
                                <th class="sort" (click)="onSort('ranking')" style="width: 98px;">Ranking</th>
                                <th class="sort" (click)="onSort('collection')">Collection</th>
                                <th class="sort" (click)="onSort('volume_price')">Volume (USD)</th>
                                <th class="sort">24h%</th>
                                <th class="sort">7d%</th>
                                <th class="sort" (click)="onSort('item')">Item</th>
                                <th class="sort">Floor Price</th>
                            </tr>
                            <!--end tr-->
                        </thead>
                        <tbody class="list form-check-all">
                            @for(data of rankingData;track $index){
                            <tr>
                                <td class="ranking text-info fw-semibold">
                                    {{data.ranking}}
                                </td>
                                <td class="collection">
                                    <div class="d-flex align-items-center">
                                        <img src="{{data.img}}" alt="" class="avatar-xs rounded-circle object-fit-cover me-2"> <a routerLink="/marletplace/item-details" class="text-body">{{data.collection}}</a>
                                    </div>
                                </td>
                                <td class="volume_price">{{data.volume_price}}</td>
                                <td>
                                    <h6 class="text-success mb-1 24h" [ngClass]=" {'text-danger': data.hours < 0}">{{data.hours}} ETH</h6>
                                </td>
                                <td>
                                    <h6 class="text-success mb-1 7d" [ngClass]=" {'text-danger': data.day < 0}">{{data.day}} ETH</h6>
                                </td>
                                <td class="item">{{data.item}}</td>
                                <td class="floor-price">{{data.floor_price}}</td>
                            </tr>
                            }
                            <!--end tr-->
                        </tbody>
                    </table>
                    <!--end table-->

                </div>
                <div class="d-flex justify-content-end mt-3">
                    <!-- Pagination -->
                    <div class="text-sm-right float-sm-end listjs-pagination">
                        <ngb-pagination [collectionSize]="allrankingData.length" [(page)]="service.page" [pageSize]="service.pageSize" (pageChange)="changePage()"></ngb-pagination>
                    </div>
                    <!-- End Pagination -->
                </div>
            </div>
        </div>
    </div><!--end col-->
</div><!--end row-->

// React+Inertia/Galaxy/resources/js/Pages/NFTMarketplace/Ranking/index.tsx
import React, { useMemo } from "react";
import { Container } from "react-bootstrap";
import BreadCrumb from "../../../Components/Common/BreadCrumb";
import TableContainer from "../../../Components/Common/TableContainer";

import { NFTRanking } from "../../../common/data";
import { Head, Link } from "@inertiajs/react";
import Layout from "../../../Layouts";

const Ranking = () => {

    // Ranking Column
    const columns = useMemo(
        () => [
            {
                header: "Ranking",
                accessorKey: "ranking",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    if (cell.getValue() < 4) {
                        return (<div className="ranking text-info fw-semibold">#{cell.getValue()}</div>);
                    } else {
                        return (<div className="ranking">#{cell.getValue()}</div>);
                    }
                }
            },
            {
                header: "Collection",
                enableColumnFilter: false,
                cell: (collection: any) => (
                    <>
                        <div className="collection">
                            <div className="d-flex align-items-center">
                                <img src={collection.row.original.img} alt="" className="avatar-xs rounded-circle object-fit-cover me-2" /> <Link href="/apps-nft-item-details" className="text-body">{collection.row.original.collection}</Link>
                            </div>
                        </div>
                    </>
                ),
            },
            {
                header: "Volume",
                accessorKey: "volume_price",
                enableColumnFilter: false,
            },
            {
                header: "24h%",
                accessorKey: "hours",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    if (cell.getValue() > 0) {
                        return (<h6 className="text-success mb-1 24h" > {cell.getValue()} ETH</h6 >);
                    } else {
                        return (<h6 className="text-danger mb-1 24h">{cell.getValue()} ETH</h6>);
                    }
                }
            },
            {
                header: "7d%",
                accessorKey: "day",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    if (cell.getValue() > 0) {
                        return (<h6 className="text-success mb-1 7d" > {cell.getValue()} ETH</h6 >);
                    } else {
                        return (<h6 className="text-danger mb-1 7d">{cell.getValue()} ETH</h6>);
                    }
                }
            },
            {
                header: "Item",
                accessorKey: "item",
                enableColumnFilter: false,
            },
            {
                header: "Floor Price",
                accessorKey: "floor_price",
                enableColumnFilter: false,
            },
        ],
        []);


    return (
        <React.Fragment>
            <Head title="Ranking | Velzon - React Admin & Dashboard Template" />
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="Ranking" pageTitle="NFT Marketplace" />
                    <div className="row">
                        <div className="col-lg-12">
                            <div className="card" id="contactList">
                                <div className="card-header border-0">
                                    <div className="d-flex align-items center">
                                        <h5 className="card-title mb-0 flex-grow-1">The top NFTs ranking on Velzon</h5>
                                        <p className="text-muted mb-0">Updated: 28 April, 2022 08:05:00</p>
                                    </div>
                                </div>
                                <div className="card-body">
                                    {NFTRanking && NFTRanking.length > 0 ? (
                                        <TableContainer
                                            columns={columns}
                                            data={(NFTRanking || [])}
                                            isGlobalFilter={true}
                                            customPageSize={10}
                                            divClass="table-responsive table-card mb-1"
                                            tableClass="align-middle table-nowrap"
                                            theadClass="table-light text-muted"
                                            isNFTRankingFilter={true}
                                            SearchPlaceholder='Search for...'
                                        />
                                    ) : (
                                        <div className="noresult">
                                            <div className="text-center">
                                                <i className="ri-search-line display-5 text-success"></i>
                                                <h5 className="mt-2">Sorry! No Result Found</h5>
                                                <p className="text-muted mb-0">We've searched more than 150+ ranking We did not find any ranking for you search.</p>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </Container>
            </div>
        </React.Fragment>
    );
};
Ranking.layout = (page: any) => <Layout children={page} />
export default Ranking;
