// React+TS/Master/src/pages/Crypto/MyWallet/MarketStatus.tsx
import React, { useMemo } from 'react';
import { Card, CardBody, CardHeader } from 'reactstrap';
import TableContainer from '../../../Components/Common/TableContainer';
import { marketStatus } from "../../../common/data";
import { Link } from "react-router-dom";

import { Quantity, AvgPrice, CurrentValue, Returns } from "./MarketStatusCol";

const MarketStatus = () => {
    const columns = useMemo(
        () => [
            {
                header: "Name",
                accessorKey: "coinName",
                enableColumnFilter: false,
                cell: (cell: any) => (
                    <>
                        <div className="d-flex align-items-center fw-medium">
                            <img src={cell.row.original.img} alt="" className="avatar-xxs me-2 material-shadow" />
                            <Link to="#" className="currency_name">{cell.getValue()}</Link>
                        </div>
                    </>
                ),
            },
            {
                header: "Quantity",
                accessorKey: "quantity",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <Quantity {...cell} />;
                },
            },
            {
                header: "Avg Price",
                accessorKey: "avgPrice",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <AvgPrice {...cell} />;
                },
            },
            {
                header: "Current Value",
                accessorKey: "value",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <CurrentValue {...cell} />;
                },
            },
            {
                header: "Returns",
                accessorKey: "returns",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <Returns {...cell} />;
                },
            },
            {
                header: "Returns %x",
                accessorKey: "percentage",
                enableColumnFilter: false,
                cell: (cell: any) => (
                    <>
                        <h6 className={"text-" + cell.row.original.percentageClass + " fs-13 mb-0"}>
                            <i className={cell.row.original.icon + " align-middle me-1"}></i>
                            {cell.getValue()}
                        </h6>
                    </>
                ),
            },
        ],
        []
    );
    return (
        <React.Fragment>
            <Card>
                <CardHeader className="border-bottom-dashed d-flex align-items-center">
                    <h4 className="card-title mb-0 flex-grow-1">Market Status</h4>
                    <div className="flex-shrink-0">
                        <div className="btn-group" role="group" aria-label="Basic example">
                            <button type="button" className="btn btn-primary btn-sm">Today</button>
                            <button type="button" className="btn btn-outline-primary btn-sm">Overall</button>
                        </div>
                    </div>
                </CardHeader>
                <CardBody>
                    <TableContainer
                        columns={columns}
                        data={(marketStatus || [])}
                        customPageSize={6}
                        divClass="table-responsive table-card mb-3"
                        tableClass="align-middle table-nowrap"
                        theadClass="table-light text-muted"
                    />
                </CardBody>
            </Card>
        </React.Fragment>
    );
};

export default MarketStatus;

// Svelte/master/src/routes/crypto/mywallet/MarketStatus.svelte
<script>
	import { Card, CardBody, CardHeader } from "sveltestrap";
	import { html } from "gridjs";
	import Grid from "gridjs-svelte";
	import cryptoData from "../../../common/data/cryptoPage";

	const data = cryptoData.marketStatus;
	const columns = [
		{
			id: "img",
			hidden: true,
		},
		{
			id: "coinName",
			name: "Name",
			formatter: (cell, row) =>
				html(`
            <div class="d-flex align-items-center fw-medium">
                <img src=${row.cells[0].data} alt="" class="avatar-xxs me-2 material-shadow" />
                <a href={null} class="currency_name">${cell}</a>
            </div>
            `),
		},
		{
			id: "quantity",
			name: "Quantity",
		},
		{
			id: "avgPrice",
			name: "Avg. Price",
		},
		{
			id: "value",
			name: "Current Value",
		},
		{
			id: "returns",
			name: "Returns",
		},
		{
			id: "icon",
			hidden: true,
		},
		{
			id: "percentageClass",
			hidden: true,
		},
		{
			id: "percentage",
			name: "Returns %",
			formatter: (cell, row) =>
				html(`<h6 class="text-${row.cells[7].data} fs-13 mb-0">
                <i class="${row.cells[6].data} align-middle me-1"></i>
                ${cell}
            </h6> `),
		},
	];
</script>

<Card>
	<CardHeader class="border-bottom-dashed d-flex align-items-center">
		<h4 class="card-title mb-0 flex-grow-1">Market Status</h4>
		<div class="flex-shrink-0">
			<div class="btn-group" role="group" aria-label="Basic example">
				<button type="button" class="btn btn-primary btn-sm"
					>Today</button
				>
				<button type="button" class="btn btn-outline-primary btn-sm"
					>Overall</button
				>
			</div>
		</div>
	</CardHeader>
	<CardBody>
		<div class="table-card gridjs-border-none">
			<Grid {data} {columns} pagination={{ enabled: true, limit: 6 }} />
		</div>
	</CardBody>
</Card>
