// React+Inertia/Master/resources/js/Pages/Auth/Login.tsx
import React, { useEffect, useState } from 'react';
import GuestLayout from '../../Layouts/GuestLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import logoLight from "../../../images/logo-light.png";
import { Container, Row, Col, Card, Form, Button } from 'react-bootstrap';

export default function Login({ status, canResetPassword }: any) {

    const [passwordShow, setPasswordShow] = useState<boolean>(false);
    const { data, setData, post, processing, errors, reset } = useForm({
        email: 'admin@themesbrand.com' || '',
        password: '12345678' || '',
        remember: false,
    });

    useEffect(() => {
        return () => {
            reset('password');
        };
    }, []);

    const submit = (e: any) => {
        e.preventDefault();
        post(route('login'));
    };

    return (
        <React.Fragment>
            <GuestLayout>
                <Head title="Basic SignIn | Velzon - React Admin & Dashboard Template" />
                <div className="auth-page-content mt-lg-5">
                    <Container>
                        <Row>
                            <Col lg={12}>
                                <div className="text-center mt-sm-5 mb-4 text-white-50">
                                    <div>
                                        <Link href='/' className="d-inline-block auth-logo">
                                            <img src={logoLight} alt="" height="20" />
                                        </Link>
                                    </div>
                                    <p className="mt-3 fs-15 fw-medium">Premium Admin & Dashboard Template</p>
                                </div>
                            </Col>
                        </Row>

                        <Row className="justify-content-center">
                            <Col md={8} lg={6} xl={5}>
                                <Card className="mt-4">
                                    <Card.Body className='p-4'>
                                        <div className="text-center mt-2">
                                            <h5 className="text-primary">Welcome Back !</h5>
                                            <p className="text-muted">Sign in to continue to Velzon.</p>
                                        </div>
                                        {status && <div className="mb-4 font-medium text-sm text-green-600">{status}</div>}
                                        <div className='p-2 mt-4'>
                                            <Form onSubmit={submit}>
                                                <div className='mb-3'>
                                                    <Form.Label className='form-label' htmlFor="email" value="Email" > Email </Form.Label>
                                                    <span className="text-danger ms-1">*</span>
                                                    <Form.Control
                                                        id="email"
                                                        type="email"
                                                        name="email"
                                                        placeholder="Enter email"
                                                        value={data.email}
                                                        className={'mb-1 ' + (errors.email ? 'is-invalid' : ' ')}
                                                        autoComplete="username"
                                                        autoFocus
                                                        required
                                                        onChange={(e: any) => setData('email', e.target.value)}
                                                    />

                                                    <Form.Control.Feedback type="invalid" className='d-block mt-2'> {errors.email} </Form.Control.Feedback>
                                                </div>

                                                <div className="mb-3">
                                                    <div className="float-end">

                                                        {canResetPassword && (
                                                            <Link href={route('password.request')} className="text-muted">Forgot password?</Link>
                                                        )}
                                                    </div>

                                                    <Form.Label className='form-label' htmlFor="password" value="Password" > Password </Form.Label>
                                                    <span className="text-danger ms-1">*</span>
                                                    <div className="position-relative auth-pass-inputgroup mb-3">

                                                        <Form.Control
                                                            id="password"
                                                            type={passwordShow ? "text" : "password"}
                                                            name="password"
                                                            value={data.password}
                                                            placeholder="Enter Password"
                                                            required
                                                            className={'mt-1 ' + (errors.password ? 'is-invalid' : ' ')}
                                                            autoComplete="current-password"
                                                            onChange={(e: any) => setData('password', e.target.value)}
                                                        />
                                                       
                                                        <Form.Control.Feedback type="invalid" className='d-block mt-2'> {errors.password} </Form.Control.Feedback>
                                                        <button className="btn btn-link position-absolute end-0 top-0 text-decoration-none text-muted material-shadow-none" type="button" id="password-addon" onClick={() => setPasswordShow(!passwordShow)}><i className="ri-eye-fill align-middle"></i></button>
                                                    </div>
                                                </div>

                                                <div className="block mt-4">
                                                    <label className="flex items-center">
                                                        <Form.Check.Input
                                                            className='form-check-input'
                                                            name="remember"
                                                            checked={data.remember}
                                                            onChange={(e: any) => setData('remember', e.target.checked)}
                                                        />
                                                        <Form.Check.Label className="form-check-label" htmlFor="auth-remember-check">
                                                            <span className='ms-2'>Remember me</span>
                                                        </Form.Check.Label>
                                                    </label>
                                                </div>

                                                <div className="mt-4">

                                                    <Button type="submit" className="btn btn-success w-100" disabled={processing}>
                                                        Sign In
                                                    </Button>
                                                </div>

                                                <div className="mt-4 text-center">
                                                    <div className="signin-other-title">
                                                        <h5 className="fs-13 mb-4 title">Sign In with</h5>
                                                    </div>
                                                    <div>
                                                        <Link
                                                            href="#"
                                                            className="btn btn-primary btn-icon me-1"

                                                        >
                                                            <i className="ri-facebook-fill fs-16" />
                                                        </Link>
                                                        <Link
                                                            href="#"
                                                            className="btn btn-danger btn-icon me-1"

                                                        >
                                                            <i className="ri-google-fill fs-16" />
                                                        </Link>
                                                        <Button variant="dark" className="btn-icon btn-dark">
                                                            <i className="ri-github-fill fs-16"></i>
                                                        </Button>{" "}
                                                        <Button variant="info" className="btn-icon btn-info">
                                                            <i className="ri-twitter-fill fs-16"></i>
                                                        </Button>
                                                    </div>
                                                </div>
                                            </Form>
                                        </div>
                                    </Card.Body>
                                </Card>
                                <div className="mt-4 text-center">
                                    <p className="mb-0">Don't have an account ? <Link href={route('register')} className="fw-semibold text-primary text-decoration-underline"> Signup </Link> </p>
                                </div>
                            </Col>
                        </Row>
                    </Container>
                </div>

            </GuestLayout>
        </React.Fragment>
    );
}

// Laravel+Vue/galaxy/resources/js/Pages/Auth/Login.vue
<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import Checkbox from '@/Components/Checkbox.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import TextInput from '@/Components/TextInput.vue';

defineProps({
    canResetPassword: Boolean,
    status: String,
});

const form = useForm({
    email: '',
    password: '',
    remember: false,
});

const submit = () => {
    form.transform(data => ({
        ...data,
        remember: form.remember ? 'on' : '',
    })).post(route('login'), {
        onFinish: () => form.reset('password'),
    });
};
</script>

<script>
export default {
    data() {
        return {
            togglePassword: false,
        }
    }
}
</script>

<template>
    <Head title="Log in" />

    <div class="auth-page-wrapper pt-5">
        <div class="auth-page-content">
            <BContainer>
                <BRow>
                    <BCol lg="12">
                        <div class="text-center mt-sm-5 mb-4 text-white-50">
                            <div>
                                <Link href="/" class="d-inline-block auth-logo">
                                    <img src="@assets/images/logo-light.png" alt="" height="20">
                                </Link>
                            </div>
                            <p class="mt-3 fs-15 fw-medium">Premium Admin & Dashboard Template</p>
                        </div>
                    </BCol>
                </BRow>
    
                <BRow class="justify-content-center">
                    <BCol md="8" lg="6" xl="5">
                        <BCard no-body class="mt-4 card-bg-fill">
    
                            <BCardBody class="p-4">
                                <div class="text-center mt-2">
                                    <h5 class="text-primary">Welcome Back !</h5>
                                    <p class="text-muted">Sign in to continue to Velzon.</p>
                                </div>
                                <div v-if="status" class="alert alert-success text-success">
                                    {{ status }}
                                </div>
                                <div class="p-2 mt-3">
                                    <form @submit.prevent="submit">
    
                                        <div class="mb-3">
                                            <InputLabel for="email" value="Email" />
                                            <TextInput id="email" v-model="form.email" type="email" class="form-control" autofocus placeholder="Please enter email" autocomplete="email" required :class="{ 'is-invalid' : form.errors.email}" />
                                            <InputError :message="form.errors.email" />
                                        </div>
    
                                        <div class="mb-3">
                                            <div class="float-end">
                                                <Link v-if="canResetPassword" :href="route('password.request')" class="text-muted">Forgot
                                                password?</Link>
                                            </div>
                                            <InputLabel for="password" value="Password" />
                                            <div class="position-relative auth-pass-inputgroup mb-3">
                                                <input :type="togglePassword ? 'text' : 'password'" class="form-control pe-5" placeholder="Enter password" id="password-input" v-model="form.password" autocomplete="password" required :class="{ 'is-invalid' : form.errors.password}">
                                                <BButton variant="link" class="position-absolute end-0 top-0 text-decoration-none text-muted" type="button" id="password-addon" @click="togglePassword = !togglePassword">
                                                    <i class="ri-eye-fill align-middle"></i>
                                                </BButton>
                                                <InputError :message="form.errors.password" />
                                            </div>
                                        </div>
    
                                        <div class="form-check">
                                            <Checkbox v-model:checked="form.remember" name="remember" class="form-check-input" id="auth-remember-check" />
                                            <label class="form-check-label" for="auth-remember-check">Remember
                                                me</label>
                                        </div>
    
                                        <div class="mt-4">
                                            <BButton variant="primary" class="w-100" type="submit" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">Sign In</BButton>
                                        </div>
    
                                        <div class="mt-4 text-center">
                                            <div class="signin-other-title">
                                                <h5 class="fs-13 mb-4 title">Sign In with</h5>
                                            </div>
                                            <div>
                                                <BButton type="button" variant="primary" class="btn-icon"><i class="ri-facebook-fill fs-16"></i></BButton>
                                                <BButton type="button" variant="danger" class="btn-icon ms-1"><i class="ri-google-fill fs-16"></i></BButton>
                                                <BButton type="button" variant="dark" class="btn-icon ms-1"><i class="ri-github-fill fs-16"></i></BButton>
                                                <BButton type="button" variant="info" class="btn-icon ms-1"><i class="ri-twitter-fill fs-16"></i></BButton>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </BCardBody>
                        </BCard>
    
                        <div class="mt-4 text-center">
                            <p class="mb-0">Don't have an account ? <Link :href="route('register')" class="fw-semibold text-primary text-decoration-underline"> Signup </Link>
                            </p>
                        </div>
    
                    </BCol>
                </BRow>
            </BContainer>
        </div>
    
        <footer class="footer">
            <BContainer>
                <BRow>
                    <BCol lg="12">
                        <div class="text-center">
                            <p class="mb-0 text-muted">&copy; {{ new Date().getFullYear() }} Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                        </div>
                    </BCol>
                </BRow>
            </BContainer>
        </footer>
    </div>
</template>
