// Svelte/minimal/src/routes/Jobs/JobList/Overview/RelatedJobs.svelte
<script>
  import Link from "svelte-link";
  import { Card, CardBody, Col, Row } from "sveltestrap";
  import overviewJobs from "../../../../common/data/appsJobs";
</script>

<Row>
  <Col lg={12}>
    <div class="d-flex align-items-center mb-4">
      <div class="flex-grow-1">
        <h5 class="mb-0">Related Jobs</h5>
      </div>
      <div class="flex-shrink-0">
        <Link href={null} class="btn btn-ghost-success">
          View All{" "}
          <i class="ri-arrow-right-line ms-1 align-bottom" />
        </Link>
      </div>
    </div>
  </Col>
  {#each overviewJobs.overviewJobs as item}
    <Col xl={4}>
      <Card>
        <CardBody>
          <button
            type="button"
            class="btn btn-icon btn-soft-primary float-end"
            data-bs-toggle="button"
            aria-pressed="true"
          >
            <i class="mdi mdi-cards-heart fs-16" />
          </button>
          <div class="avatar-sm mb-4">
            <div class="avatar-title bg-secondary-subtle rounded">
              <img src={item.companyLogo} alt="" class="avatar-xxs" />
            </div>
          </div>
          <Link href={null}>
            <h5>{item.jobTitle}</h5>
          </Link>
          <p class="text-muted">{item.companyName}</p>

          <div class="d-flex gap-4 mb-3">
            <div>
              <i
                class="ri-map-pin-2-line text-primary me-1 align-bottom"
              />{" "}
              {item.location}
            </div>

            <div>
              <i class="ri-time-line text-primary me-1 align-bottom" />{" "}
              {item.time}
            </div>
          </div>

          <p class="text-muted">{item.description}</p>

          <div class="hstack gap-2">
            <span class="badge bg-warning-subtle text-warning">{item.s1}</span>
            <span class="badge bg-primary-subtle text-primary">{item.s2}</span>
            <span class="badge bg-danger-subtle text-danger">{item.s3}</span>
          </div>

          <div class="mt-4 hstack gap-2">
            <Link href={null} class="btn btn-soft-primary w-100">Apply Job</Link>
            <Link href={null} class="btn btn-soft-success w-100">Overview</Link>
          </div>
        </CardBody>
      </Card>
    </Col>
  {/each}
</Row>

// React+Inertia/Default/resources/js/Pages/Jobs/JobList/Overview/RelatedJobs.tsx
import React from "react";
import { Card, CardBody, Col, Row } from "react-bootstrap";
import { overviewJobs } from "../../../../common/data/appsJobs";
import { Link } from "@inertiajs/react";

const RelatedJobs = () => {
  return (
    <React.Fragment>
      <Row>
        <Col lg={12}>
          <div className="d-flex align-items-center mb-4">
            <div className="flex-grow-1">
              <h5 className="mb-0">Related Jobs</h5>
            </div>
            <div className="flex-shrink-0">
              <Link href="#" className="btn btn-ghost-secondary">
                View All{" "}
                <i className="ri-arrow-right-line ms-1 align-bottom"></i>
              </Link>
            </div>
          </div>
        </Col>
        {overviewJobs.map((item, key) => (
          <Col xl={4} key={key}>
            <Card>
              <CardBody>
                <button
                  type="button"
                  className="btn btn-icon btn-soft-primary float-end"
                  data-bs-toggle="button"
                  aria-pressed="true"
                >
                  <i className="mdi mdi-cards-heart fs-16"></i>
                </button>
                <div className="avatar-sm mb-4">
                  <div className={`avatar-title bg-${item.color}-subtle rounded`}>
                    <img src={item.companyLogo} alt="" className="avatar-xxs" />
                  </div>
                </div>
                <Link href="#">
                  <h5>{item.jobTitle}</h5>
                </Link>
                <p className="text-muted">{item.companyName}</p>

                <div className="d-flex gap-4 mb-3">
                  <div>
                    <i className="ri-map-pin-2-line text-primary me-1 align-bottom"></i>{" "}
                    {item.location}
                  </div>

                  <div>
                    <i className="ri-time-line text-primary me-1 align-bottom"></i>{" "}
                    {item.time}
                  </div>
                </div>

                <p className="text-muted">{item.description}</p>

                <div className="hstack gap-2">
                  <span className="badge bg-warning-subtle text-warning">{item.s1}</span>
                  <span className="badge bg-primary-subtle text-primary">{item.s2}</span>
                  <span className="badge bg-danger-subtle text-danger">{item.s3}</span>
                </div>

                <div className="mt-4 hstack gap-2">
                  <Link href="#" className="btn btn-soft-primary w-100">
                    Apply Job
                  </Link>
                  <Link href="#" className="btn btn-soft-info w-100">
                    Overview
                  </Link>
                </div>
              </CardBody>
            </Card>
          </Col>
        ))}
      </Row>
    </React.Fragment>
  );
};

export default RelatedJobs;
