// Svelte/interactive/src/Components/Common/MyCartDropdown.svelte
<script>
	import {
		Row,
		Col,
		Dropdown,
		DropdownToggle,
		DropdownMenu,
	} from "sveltestrap";

	import img1 from '../../assets/images/products/img-1.png';
	import img2 from '../../assets/images/products/img-2.png';
	import img3 from '../../assets/images/products/img-3.png';
	import img5 from '../../assets/images/products/img-5.png';
	import img6 from '../../assets/images/products/img-6.png';

	const removecartitem = (e) => {
		var dropdownItemCart = document.querySelectorAll(".dropdown-item-cart").length;
		dropdownItemCart--;
		e.target.closest(".dropdown-item-cart").remove()
		Array.from(document.getElementsByClassName("cartitem-badge")).forEach(function (e) {
			e.innerHTML = dropdownItemCart;
		});
		if (dropdownItemCart <= 0) {
			document.getElementById("empty-cart").classList.remove("d-none");
			document.getElementById("checkout-elem").style.display = "none";
		} else {
			document.getElementById("empty-cart").classList.add("d-none");
			document.getElementById("checkout-elem").style.display = "block";
		}
		updateCartPrice();
		function updateCartPrice() {
			var currencySign = "$";
			var subtotal = 0;
			Array.from(document.getElementsByClassName("cart-item-price")).forEach(function (e) {
				subtotal += parseFloat(e.innerHTML);
			});
			if (document.getElementById("cart-item-total")) {
				document.getElementById("cart-item-total").innerHTML = currencySign + subtotal.toFixed(2);
			}
		}
	}

</script>

<Dropdown class="topbar-head-dropdown ms-1 header-item">
	<DropdownToggle type="button" color="" class="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle p-0">
		<i class="bx bx-shopping-bag fs-22" />
		<span class="position-absolute topbar-badge cartitem-badge fs-10 translate-middle badge rounded-pill bg-info">
			5
			<span class="visually-hidden">unread messages</span>
		</span>
	</DropdownToggle>
	<DropdownMenu class="dropdown-menu-xl dropdown-menu-end p-0 dropdown-menu-cart" end>
		<div class="p-3 border-top-0 border-start-0 border-end-0 border-dashed border">
			<Row class="align-items-center">
				<Col>
				<h6 class="m-0 fs-16 fw-semibold">My Cart</h6>
				</Col>
				<div class="col-auto">
					<span class="badge bg-warning-subtle text-warning fs-13"><span class="cartitem-badge"> 5 </span>
						items</span>
				</div>
			</Row>
		</div>
		<div data-simplebar style="max-height: 300px;">
			<div class="p-2">
				<div class="text-center empty-cart d-none" id="empty-cart">
					<div class="avatar-md mx-auto my-3">
						<div class="avatar-title bg-info-subtle text-info fs-36 rounded-circle">
							<i class="bx bx-cart" />
						</div>
					</div>
					<h5 class="mb-3">Your Cart is Empty!</h5>
					<a href="{null}" class="btn btn-success w-md mb-3">Shop Now</a>
				</div>
				<div class="d-block dropdown-item dropdown-item-cart text-wrap px-3 py-2">
					<div class="d-flex align-items-center">
						<img src={img1} class="me-3 rounded-circle avatar-sm p-2 bg-light" alt="user-pic" />
						<div class="flex-grow-1">
							<h6 class="mt-0 mb-1 fs-14">
								<a href="/ecommerce/apps-ecommerce-product-details" class="text-reset">Branded
									T-Shirts</a>
							</h6>
							<p class="mb-0 fs-12 text-muted">
								Quantity: <span>10 x $32</span>
							</p>
						</div>
						<div class="px-2">
							<h5 class="m-0 fw-normal">
								$<span class="cart-item-price">320</span>
							</h5>
						</div>
						<div class="ps-2">
							<button type="button" class="btn btn-icon btn-sm btn-ghost-secondary remove-item-btn"
								on:click={removecartitem}><i class="ri-close-fill fs-16" /></button>
						</div>
					</div>
				</div>

				<div class="d-block dropdown-item dropdown-item-cart text-wrap px-3 py-2 w-100 h-auto">
					<div class="d-flex align-items-center">
						<img src={img2} class="me-3 rounded-circle avatar-sm p-2 bg-light" alt="user-pic" />
						<div class="flex-grow-1">
							<h6 class="mt-0 mb-1 fs-14">
								<a href="/ecommerce/apps-ecommerce-product-details" class="text-reset">Bentwood
									Chair</a>
							</h6>
							<p class="mb-0 fs-12 text-muted">
								Quantity: <span>5 x $18</span>
							</p>
						</div>
						<div class="px-2">
							<h5 class="m-0 fw-normal">
								$<span class="cart-item-price">89</span>
							</h5>
						</div>
						<div class="ps-2">
							<button type="button" class="btn btn-icon btn-sm btn-ghost-secondary remove-item-btn"
								on:click={removecartitem}><i class="ri-close-fill fs-16" /></button>
						</div>
					</div>
				</div>

				<div class="d-block dropdown-item dropdown-item-cart text-wrap px-3 py-2">
					<div class="d-flex align-items-center">
						<img src={img3} class="me-3 rounded-circle avatar-sm p-2 bg-light" alt="user-pic" />
						<div class="flex-grow-1">
							<h6 class="mt-0 mb-1 fs-14">
								<a href="/ecommerce/apps-ecommerce-product-details" class="text-reset">
									Borosil Paper Cup</a>
							</h6>
							<p class="mb-0 fs-12 text-muted">
								Quantity: <span>3 x $250</span>
							</p>
						</div>
						<div class="px-2">
							<h5 class="m-0 fw-normal">
								$<span class="cart-item-price">750</span>
							</h5>
						</div>
						<div class="ps-2">
							<button type="button" class="btn btn-icon btn-sm btn-ghost-secondary remove-item-btn"
								on:click={removecartitem}><i class="ri-close-fill fs-16" /></button>
						</div>
					</div>
				</div>

				<div class="d-block dropdown-item dropdown-item-cart text-wrap px-3 py-2">
					<div class="d-flex align-items-center">
						<img src={img6} class="me-3 rounded-circle avatar-sm p-2 bg-light" alt="user-pic" />
						<div class="flex-grow-1">
							<h6 class="mt-0 mb-1 fs-14">
								<a href="/ecommerce/apps-ecommerce-product-details" class="text-reset">Gray Styled
									T-Shirt</a>
							</h6>
							<p class="mb-0 fs-12 text-muted">
								Quantity: <span>1 x $1250</span>
							</p>
						</div>
						<div class="px-2">
							<h5 class="m-0 fw-normal">
								$<span class="cart-item-price">1250</span>
							</h5>
						</div>
						<div class="ps-2">
							<button type="button" class="btn btn-icon btn-sm btn-ghost-secondary remove-item-btn"
								on:click={removecartitem}><i class="ri-close-fill fs-16" /></button>
						</div>
					</div>
				</div>

				<div class="d-block dropdown-item dropdown-item-cart text-wrap px-3 py-2">
					<div class="d-flex align-items-center">
						<img src={img5} class="me-3 rounded-circle avatar-sm p-2 bg-light" alt="user-pic" />
						<div class="flex-grow-1">
							<h6 class="mt-0 mb-1 fs-14">
								<a href="/ecommerce/apps-ecommerce-product-details" class="text-reset">Stillbird
									Helmet</a>
							</h6>
							<p class="mb-0 fs-12 text-muted">
								Quantity: <span>2 x $495</span>
							</p>
						</div>
						<div class="px-2">
							<h5 class="m-0 fw-normal">
								$<span class="cart-item-price">990</span>
							</h5>
						</div>
						<div class="ps-2">
							<button type="button" class="btn btn-icon btn-sm btn-ghost-secondary remove-item-btn"
								on:click={removecartitem}><i class="ri-close-fill fs-16" /></button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="p-3 border-bottom-0 border-start-0 border-end-0 border-dashed border" id="checkout-elem">
			<div class="d-flex justify-content-between align-items-center pb-3">
				<h5 class="m-0 text-muted">Total:</h5>
				<div class="px-2">
					<h5 class="m-0" id="cart-item-total">$3399.00</h5>
				</div>
			</div>

			<a href="/ecommerce/apps-ecommerce-checkout" class="btn btn-success text-center w-100">
				Checkout
			</a>
		</div>
	</DropdownMenu>
</Dropdown>

// React+Inertia/Modern/resources/js/Components/Common/MyCartDropdown.tsx
import React, { useState } from 'react';
import { Col, Dropdown, Row } from 'react-bootstrap';

//SimpleBar
import SimpleBar from "simplebar-react";

//import images
import image1 from "../../../images/products/img-1.png";
import image2 from "../../../images/products/img-2.png";
import image3 from "../../../images/products/img-3.png";
import image6 from "../../../images/products/img-6.png";
import image5 from "../../../images/products/img-5.png";
import { Link } from '@inertiajs/react';

const MyCartDropdown = () => {

    const cartData = [
        { id: 1, img: image1, product: "Branded T-Shirts", quantity: 10, price: 32 },
        { id: 2, img: image2, product: "Bentwood Chair", quantity: 5, price: 18 },
        { id: 3, img: image3, product: "Borosil Paper Cup", quantity: 3, price: 250 },
        { id: 4, img: image6, product: "Gray Styled T-Shirt", quantity: 1, price: 1250 },
        { id: 5, img: image5, product: "Stillbird Helmet", quantity: 2, price: 495 },
    ];

    const [isCartDropdown, setIsCartDropdown] = useState<boolean>(false);

    const [cartItem, setCartItem] = useState(cartData.length);

    const toggleCartDropdown = () => {
        setIsCartDropdown(!isCartDropdown);
        setCartItem(cartData.length);
    };

    const removeItem = (ele: HTMLElement | null): void => {
        if (ele) {
            const priceElement = ele.closest(".dropdown-item-cart")?.querySelector('.cart-item-price');
            const subTotalElement = document.getElementById('cart-item-total');

            if (priceElement && subTotalElement) {
                const price = parseFloat(priceElement.innerHTML);
                const subTotal = parseFloat(subTotalElement.innerHTML);
                const newTotal = subTotal - price;

                subTotalElement.innerHTML = newTotal.toFixed(2);
            }

            ele.closest(".dropdown-item-cart")?.remove();

            const element = document.querySelectorAll(".dropdown-item-cart").length;
            const ecart = document.getElementById("empty-cart");

            if (ecart) {
                ecart.style.display = element === 0 ? 'block' : 'none';
            }

            setCartItem(element);
        }
    };


    return (
        <React.Fragment>
            <Dropdown show={isCartDropdown} onClick={toggleCartDropdown} className="topbar-head-dropdown ms-1 header-item">
                <Dropdown.Toggle type="button" as="button" className="arrow-none btn btn-icon btn-topbar btn-ghost-secondary rounded-circle">
                    <i className='bx bx-shopping-bag fs-22'></i>
                    <span
                        className="position-absolute cartitem-badge topbar-badge fs-10 translate-middle badge rounded-pill bg-info">{cartItem}<span
                            className="visually-hidden">unread messages</span></span>
                </Dropdown.Toggle>
                <Dropdown.Menu className="dropdown-menu-xl dropdown-menu-end p-0 dropdown-menu-cart"
                    aria-labelledby="page-header-cart-dropdown">
                    <div className="p-3 border-top-0 border-start-0 border-end-0 border-dashed border">
                        <Row className="align-items-center">
                            <Col>
                                <h6 className="m-0 fs-16 fw-semibold"> My Cart</h6>
                            </Col>
                            <div className="col-auto">
                                <span className="badge bg-warning-subtle  text-warning fs-13"><span className="cartitem-badge"> {cartItem} </span> items</span>
                            </div>
                        </Row>
                    </div>
                    <SimpleBar style={{ maxHeight: "300px" }}>
                        <div className="p-2">
                            <div className="text-center empty-cart" id="empty-cart" style={{ display: "none" }}>
                                <div className="avatar-md mx-auto my-3">
                                    <div className="avatar-title bg-info-subtle text-info fs-36 rounded-circle">
                                        <i className='bx bx-cart'></i>
                                    </div>
                                </div>
                                <h5 className="mb-3">Your Cart is Empty!</h5>
                                <Link href="/apps-ecommerce-products" className="btn btn-success w-md mb-3">Shop Now</Link>
                            </div>

                            {cartData.map((item, key) => (<div className="d-block dropdown-item text-wrap dropdown-item-cart px-3 py-2" key={key}>
                                <div className="d-flex align-items-center">
                                    <img src={item.img}
                                        className="me-3 rounded-circle avatar-sm p-2 bg-light" alt="user-pic" />
                                    <div className="flex-grow-1">
                                        <h6 className="mt-0 mb-1 fs-14">
                                            <Link href="/apps-ecommerce-product-details" className="text-reset">{item.product}</Link>
                                        </h6>
                                        <p className="mb-0 fs-12 text-muted">
                                            Quantity: <span>{item.quantity} x ${item.price}</span>
                                        </p>
                                    </div>
                                    <div className="px-2">
                                        <h5 className="m-0 fw-normal">$<span className="cart-item-price">{item.quantity * item.price}</span></h5>
                                    </div>
                                    <div className="ps-2">
                                        <button type="button" className="btn btn-icon btn-sm btn-ghost-secondary remove-item-btn" onClick={(e: any) => { removeItem(e.target); }}><i
                                            className="ri-close-fill fs-16"></i></button>
                                    </div>
                                </div>
                            </div>))}
                        </div>
                    </SimpleBar>
                    <div className="p-3 border-bottom-0 border-start-0 border-end-0 border-dashed border" id="checkout-elem">
                        <div className="d-flex justify-content-between align-items-center pb-3">
                            <h5 className="m-0 text-muted">Total:</h5>
                            <div className="px-2">
                                <h5 className="m-0">$<span id="cart-item-total">3400</span></h5>
                            </div>
                        </div>

                        <Link href="/apps-ecommerce-checkout" className="btn btn-success text-center w-100">
                            Checkout
                        </Link>
                    </div>
                </Dropdown.Menu>
            </Dropdown>
        </React.Fragment>
    );
};

export default MyCartDropdown;
