// Svelte/creative/src/routes/calendar/+page.svelte
<script>
	import { onMount } from "svelte";
	import * as FullCalendar from "fullcalendar"; // Import FullCalendar
	import { CalendarIcon } from "svelte-feather-icons";
	import Flatpickr from "svelte-flatpickr";
	import {
		Card,
		Button,
		CardBody,
		Container,
		ModalBody,
		ModalHeader,
		Row,
		Col,
		Label,
		Alert,
	} from "sveltestrap";

	import UpcommingEvents from "./UpcommingEvents.svelte";

	import BreadCrumb from "../../Components/Common/BreadCrumb.svelte";
	import CalendarEventsList from "../../common/data/calender";
	import Modal from "../../Components/Common/Modal.svelte";
	import "overlayscrollbars/overlayscrollbars.css";

	let isOpen = false;
	let calendar;
	let calendarComponentRef;
	let modalcategory = false;
	let setEvent = {};
	let isedit = false;
	let setSelectedDay = new Date();
	let eventsList = CalendarEventsList;

	let deleteModal = false;

	const toggle = () => {
		isOpen = !isOpen;
		if (!isOpen) {
			setTimeout(() => {
				setEvent = {};

				isedit = false;
			}, 500);
		}
	};

	const eventData1 = {
		id: Math.floor(Math.random() * 100),
		title: "New Event Planning",
		start: new Date(),
		allDay: false,
		className: "bg-success-subtle",
	};

	const eventData2 = {
		id: Math.floor(Math.random() * 100),
		title: "Meeting",
		start: new Date(),
		allDay: false,
		className: "bg-info-subtle",
	};

	const eventData3 = {
		id: Math.floor(Math.random() * 100),
		title: "Generating Reports",
		start: new Date(),
		allDay: false,
		className: "bg-warning-subtle",
	};

	const eventData4 = {
		id: Math.floor(Math.random() * 100),
		title: "Create New theme",
		start: new Date(),
		allDay: false,
		className: "bg-danger-subtle",
	};

	function handleDateClick(arg) {
		setSelectedDay = new Date(arg);;
		toggle();
	}

	let options;
	let calendarEl;
	let externalEventContainerEl;

	function getInitialView() {
		if (window.innerWidth >= 768 && window.innerWidth < 1200) {
			return "timeGridWeek";
		} else if (window.innerWidth <= 768) {
			return "listMonth";
		} else {
			return "dayGridMonth";
		}
	}

	onMount(() => {
		var Draggable = FullCalendar.Draggable;
		externalEventContainerEl = document.getElementById("external-events");
		// init draggable
		new Draggable(externalEventContainerEl, {
			itemSelector: ".external-event",
			eventData: function (eventEl) {
				return {
					id: Math.floor(Math.random() * 11000),
					title: eventEl.innerText,
					allDay: true,
					start: new Date(),
					className: eventEl.getAttribute("data-class"),
				};
			},
		});

		calendarEl = document.getElementById("calendar");
		options = {
			timeZone: "local",
			editable: true,
			droppable: true,
			selectable: true,
			navLinks: true,
			initialView: getInitialView(),
			themeSystem: "bootstrap",
			headerToolbar: {
				left: "prev,next today",
				center: "title",
				right: "dayGridMonth,timeGridWeek,timeGridDay,listMonth",
			},
			events: eventsList.events,
			windowResize: function (view) {
				var newView = getInitialView();
				calendar.changeView(newView);
			},
			eventClick: (event) => handleEventClick(event),
			dateClick: (event) => handleDateClick(event.dateStr),
			eventReceive: function (info) {
				var newid = parseInt(info.event.id);
				var newEvent = {
					id: newid,
					title: info.event.title,
					start: info.event.start,
					allDay: info.event.allDay,
					className: info.event.classNames[0],
				};
				eventsList.events = [...eventsList.events, newEvent];
				updateCalendarEvents();
			},
		};
		// Initialize FullCalendar
		calendar = new FullCalendar.Calendar(calendarEl, options);

		calendar.render(); // Render the calendar
	});

	function updateCalendarEvents() {
		// Reassign the events property with the updated events data
		options.events = eventsList.events;
		calendar.destroy(); // Destroy the existing instance
		calendar = new FullCalendar.Calendar(calendarEl, options); // Reinitialize with updated options
		calendar.render();
		calendar.refetchEvents(); // Refresh the calendar with the updated events
	}

	const handleEventClick = (arg) => {
		const event = arg.event;
		setEvent = {
			id: parseInt(event.id),
			title: event.title,
			title_category: event.title_category,
			start: event.start,
			className: event.classNames,
			category: event.classNames[0],
			event_category: event.classNames[0],
		};
        setSelectedDay = setEvent.start;
		isedit = true;
		toggle();
	};

	const toggleCategory = () => {
		modalcategory = !modalcategory;
	};

	const handleValidEventSubmit = async ({
		target: {
			elements: { category, title },
		},
	}) => {
		if (isedit) {
			if (
				title.value == null ||
				title.value == undefined ||
				title.value == ""
			) {
				document.getElementById("divAlert").style.display = "block";
				return false;
			}
			const updateEvent = {
				id: setEvent.id,
				title: title.value,
				className: category.value,
				start: setSelectedDay,
				allDay: false,
			};

			const i = eventsList.events.findIndex(
				(t) => t.id === updateEvent.id
			);
			// update event
			eventsList.events[i] = updateEvent;
			eventsList.events = [...eventsList.events];

			updateCalendarEvents();
		} else {
			if (
				title.value == null ||
				title.value == undefined ||
				title.value == ""
			) {
				document.getElementById("divAlert").style.display = "block";
				return false;
			}
			let newEvent = {
				id: Math.floor(Math.random() * 100),
				title: title.value,
				start: setSelectedDay ? setSelectedDay : new Date(),
				allDay: false,
				className: category.value,
			};
			eventsList.events = [...eventsList.events, newEvent];
			updateCalendarEvents();
		}

		setSelectedDay = "";
		toggle();
	};

	const handleDeleteEvent = () => {
		var calendarEvents = CalendarEventsList.events.filter((e, i) => {
			return e.id !== setEvent.id;
		});

		// calendarEvents = [...calendarEvents];
		eventsList.events = calendarEvents;

		setDeleteModal(false);
		updateCalendarEvents();
		toggle();
	};

	const setDeleteModal = (status) => {
		deleteModal = status;
		isOpen = false;

		var calendarEvents = CalendarEventsList.events.filter((e, i) => {
			return e.id !== setEvent.id;
		});

		eventsList.events = calendarEvents;
		updateCalendarEvents();
		setTimeout(() => {
			setEvent = {};
			isedit = false;
		}, 500);
	};
</script>

<svelte:head>
	<title>Calendar | Velzon - Svelte Admin & Dashboard Template</title>
	<style>
		#divAlert {
			display: none;
		}
	</style>
</svelte:head>

<div class="page-content">
	<Container fluid>
		<BreadCrumb title="Calendar" pageTitle="Apps" />
		<Row>
			<Col xs={12}>
				<Row>
					<Col xl={3}>
						<Card class="card-h-100">
							<CardBody>
								<button
									class="btn btn-primary w-100"
									id="btn-new-event"
									on:click={toggle}
								>
									<i class="mdi mdi-plus" /> Create New Event
								</button>
								<div id="external-events">
									<br />
									<p class="text-muted">
										Drag and drop your event or click in the
										calendar
									</p>
									<div
										class="external-event fc-event bg-success-subtle text-success"
										data-class="bg-success-subtle"
									>
										<i
											class="mdi mdi-checkbox-blank-circle me-2"
										/>New Event Planning
									</div>
									<div class="external-event fc-event bg-info-subtle text-info" data-class="bg-info-subtle">
										<i class="mdi mdi-checkbox-blank-circle me-2"></i>Meeting
									</div>
									<div class="external-event fc-event bg-warning-subtle text-warning" data-class="bg-warning-subtle">
										<i class="mdi mdi-checkbox-blank-circle me-2"></i>Generating Reports
									</div>
									<div class="external-event fc-event bg-danger-subtle text-danger" data-class="bg-danger-subtle">
										<i class="mdi mdi-checkbox-blank-circle me-2"></i>Create New theme
									</div>
								</div>
							</CardBody>
						</Card>
						<div>
							<h5 class="mb-1">Upcoming Events</h5>
							<p class="text-muted">
								Don't miss scheduled events
							</p>
							<div
								class="pe-2 me-n1 mb-3"
								data-overlayscrollbars-initialize
								style="height: 400px"
							>
								<div id="upcoming-event-list">
									{#if CalendarEventsList.defaultevent}
										{#each CalendarEventsList.defaultevent as event}
											<UpcommingEvents {event} />
										{/each}
									{/if}
								</div>
							</div>
						</div>
						<Card>
							<CardBody class="bg-info-subtle">
								<div class="d-flex">
									<div class="flex-shrink-0">
										<CalendarIcon
											class="text-info icon-dual-info"
											size="24"
										/>
									</div>
									<div class="flex-grow-1 ms-3">
										<h6 class="fs-15">
											Welcome to your Calendar!
										</h6>
										<p class="text-muted mb-0">
											Event that applications book will
											appear here. Click on an event to
											see the details and manage
											applicants event.
										</p>
									</div>
								</div>
							</CardBody>
						</Card>
					</Col>
					<Col xl={9}>
						<Card className="card-h-100">
							<CardBody>
								<div id="calendar" />
							</CardBody>
						</Card>
					</Col>
				</Row>
			</Col>
		</Row>
	</Container>
</div>

<Modal {isOpen}>
	<ModalHeader {toggle} tag="h4">
		{!!isedit ? "Edit Event" : "Add Event"}
	</ModalHeader>
	<ModalBody>
		<form on:submit|preventDefault={handleValidEventSubmit}>
			<Row>
				<Col class="col-12">
					<div class="mb-3">
						<div id="divAlert">
							<Alert color="danger">Please provide a valid event name</Alert>
						</div>
						<Label class="form-label" for="title">Event Name</Label>
						<input
							type="text"
							class="form-control"
							name="title"
							placeholder="Event Name"
							value={setEvent && setEvent.title
								? setEvent.title
								: ""}
						/>
					</div>
				</Col>
				<Col class="col-12">
					<div class="mb-3">
						<Label class="form-label" for="category">Category</Label
						>
						<select
							name="category"
							class="form-control form-select"
							placeholder="Select Category"
							value={setEvent ? setEvent.category : "bg-primary"}
						>
							<option value="bg-danger-subtle">Danger</option>
							<option value="bg-success-subtle">Success</option>
							<option value="bg-primary-subtle">Primary</option>
							<option value="bg-info-subtle">Info</option>
							<option value="bg-dark-subtle">Dark</option>
							<option value="bg-warning-subtle">Warning</option>
						</select>
					</div>
				</Col>
				<Col class="col-12">
					<div class="mb-3">
						<Label class="form-label" for="date">Date</Label>
						<Flatpickr
                            class="form-control"
                            id="date"
                            placeholder="Select a date"
                            bind:value={setSelectedDay}
                            options={{
                                altInput: true,
                                altFormat: "F j, Y",
                                dateFormat: "d-m-Y",
                            }}
                        />
					</div>
				</Col>
			</Row>
			<Row class="mt-2">
				<Col xs="12" class="text-end">
					{#if !!isedit}
						<button
							type="button"
							class="btn btn-danger"
							on:click={() => setDeleteModal(true)}>Delete</button
						>
					{/if}
					<button
						type="button"
						class="btn btn-light me-2"
						on:click={toggle}
					>
						Close
					</button>
					<button type="submit" class="btn btn-success save-event">
						Save
					</button>
				</Col>
			</Row>
		</form>
	</ModalBody>
</Modal>

// React+Inertia/Galaxy/resources/js/Pages/Calendar/index.tsx
import React, { useEffect, useState } from "react";
import PropTypes from "prop-types";

//Import Icons
import FeatherIcon from "feather-icons-react";

import {
  Card,
  Container,
  Form,
  Modal,
  Row,
  Col
} from "react-bootstrap";

import * as Yup from "yup";
import { useFormik } from "formik";

import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import interactionPlugin, { Draggable } from "@fullcalendar/interaction";
import BootstrapTheme from "@fullcalendar/bootstrap";
import Flatpickr from "react-flatpickr";

//redux
import { useSelector, useDispatch } from "react-redux";

import BreadCrumb from "../../Components/Common/BreadCrumb";
import DeleteModal from "../../Components/Common/DeleteModal";

//Simple bar
import SimpleBar from "simplebar-react";
import UpcommingEvents from './UpcommingEvents';
import listPlugin from '@fullcalendar/list';

import { onAddNewEvent, onDeleteEvent, onGetCategories, onGetEvents, onGetUpCommingEvent, onUpdateEvent } from "../../slices/thunk";
import { createSelector } from "reselect";
import Layout from "../../Layouts";
import { Head, Link } from "@inertiajs/react";

const Calender = () => {
  const dispatch: any = useDispatch();
  const [event, setEvent] = useState<any>({});
  const [modal, setModal] = useState<boolean>(false);
  const [selectedNewDay, setSelectedNewDay] = useState<any>();
  const [isEdit, setIsEdit] = useState<boolean>(false);
  const [isEditButton, setIsEditButton] = useState<boolean>(true);
  const [deleteModal, setDeleteModal] = useState<boolean>(false);
  const [deleteEvent, setDeleteEvent] = useState<string>('');
  const [eventName, setEventName] = useState<string>("")

  const selectLayoutState = (state: any) => state.Calendar;
  const calendarDataProperties = createSelector(
    selectLayoutState,
    (state: any) => ({
      events: state.events,
      categories: state.categories,
      isEventUpdated: state.isEventUpdated,
    })
  );
  // Inside your component
  const {
    events, categories, isEventUpdated
  }: any = useSelector(calendarDataProperties);

  useEffect(() => {
    dispatch(onGetEvents());
    dispatch(onGetCategories());
    dispatch(onGetUpCommingEvent());
    new Draggable(document.getElementById("external-events") as HTMLElement, {
      itemSelector: ".external-event",
    });
  }, [dispatch]);

  useEffect(() => {
    if (isEventUpdated) {
      setIsEdit(false);
      setEvent({});
    }
  }, [dispatch, isEventUpdated]);

  /**
   * Handling the modal state
   */
  const toggle = () => {
    if (modal) {
      setModal(false);
      setEvent(null);
      setIsEdit(false);
      setIsEditButton(true);
    } else {
      setModal(true);
    }
  };
  /**
   * Handling date click on calendar
   */

  const handleDateClick = (arg: any) => {
    const date = arg["date"];
    setSelectedNewDay(date);
    toggle();
  };

  const str_dt = function formatDate(date: any) {
    var monthNames = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ];
    var d = new Date(date),
      month = "" + monthNames[d.getMonth()],
      day = "" + d.getDate(),
      year = d.getFullYear();
    if (month.length < 2) month = "0" + month;
    if (day.length < 2) day = "0" + day;
    return [day + " " + month, year].join(",");
  };

  /**
   * Handling click on event on calendar
   */

  const handleEventClick = (arg: any) => {
    const event = arg.event;

    const st_date = event.start;
    const ed_date = event.end;
    const r_date =
      ed_date == null
        ? str_dt(st_date)
        : str_dt(st_date) + " to " + str_dt(ed_date);
    const er_date = ed_date === null ? [st_date] : [st_date, ed_date];


    setEvent({
      id: event.id,
      title: event.title,
      start: event.start,
      end: event.end,
      className: event.classNames,
      category: event.classNames[0],
      location: event._def.extendedProps.location ? event._def.extendedProps.location : "No Loaction",
      description: event._def.extendedProps.description,
      defaultDate: er_date,
      datetag: r_date,
    });
    setSelectedNewDay(er_date);
    setEventName(event.title)
    setDeleteEvent(event.id);
    setIsEdit(true);
    setIsEditButton(false);
    toggle();
  };
  /**
   * On delete event
   */
  const handleDeleteEvent = () => {
    dispatch(onDeleteEvent(deleteEvent));
    setDeleteModal(false);
  };

  // events validation
  const validation: any = useFormik({
    // enableReinitialize : use this flag when initial values needs to be changed
    enableReinitialize: true,

    initialValues: {
      id: (event && event.id) || "",
      title: (event && event.title) || "",
      category: (event && event.category) || "",
      location: (event && event.location) || "",
      description: (event && event.description) || "",
      defaultDate: (event && event.defaultDate) || [],
      datetag: (event && event.datetag) || "",
      start: (event && event.start) || "",
      end: (event && event.end) || ''
    },

    validationSchema: Yup.object({
      title: Yup.string().required("Please Enter Your Event Name"),
      category: Yup.string().required("Please Select Your Category"),
      location: Yup.string().required("Please Enter Your Location"),
      description: Yup.string().required("Please Enter Your Description"),
      start: Yup.date().required('Start Time is required'),
      end: Yup.date().required('End Time is required'),
      defaultDate: Yup.array().of(Yup.date()).required('Date range is required').min(2, 'Select at least two dates'),
    }),
    onSubmit: (values) => {
      var updatedDay: any = "";
      if (selectedNewDay) {
        updatedDay = new Date(selectedNewDay[1]);
        // updatedDay.setDate(updatedDay.getDate() + 1);
        updatedDay.setDate(updatedDay.getDate());

      }

      if (isEdit) {
        const updateEvent = {
          id: event.id,
          title: values.title,
          className: values.category,
          start: selectedNewDay ? selectedNewDay[0].toISOString() : event.start,
          end: selectedNewDay ? updatedDay.toISOString() : event.end,
          location: values.location,
          description: values.description,
          defaultDate: [selectedNewDay[0].toISOString(), selectedNewDay[1].toISOString()]
        };
        // update event
        dispatch(onUpdateEvent(updateEvent));
        validation.resetForm();
      } else {
        const newEvent = {
          id: Math.floor(Math.random() * 100),
          title: values["title"],
          start: selectedNewDay[0].toISOString(),
          end: updatedDay.toISOString(),
          className: values["category"],
          location: values["location"],
          description: values["description"],
          defaultDate: [selectedNewDay[0].toISOString(), selectedNewDay[1].toISOString()]
        };
        // save new event
        dispatch(onAddNewEvent(newEvent));
        validation.resetForm();
      }

      // setSelectedDay(null);
      setSelectedNewDay(null);
      toggle();
    },
  });

  const submitOtherEvent = () => {

    document.getElementById("form-event")?.classList.remove("view-event");

    document
      .getElementById("event-title")?.classList.replace("d-none", "d-block");
    document
      .getElementById("event-category")?.classList.replace("d-none", "d-block");
    (document.getElementById("event-start-date")?.parentNode as HTMLElement).classList.remove("d-none");
    document
      .getElementById("event-start-date")?.classList.replace("d-none", "d-block");
    document
      .getElementById("event-location")?.classList.replace("d-none", "d-block");
    document
      .getElementById("event-description")?.classList.replace("d-none", "d-block");
    document
      .getElementById("event-start-date-tag")?.classList.replace("d-block", "d-none");
    document
      .getElementById("event-location-tag")?.classList.replace("d-block", "d-none");
    document
      .getElementById("event-description-tag")?.classList.replace("d-block", "d-none");

    setIsEditButton(true);
  };

  /**
   * On category darg event
   */
  const onDrag = (event: any) => {
    event.preventDefault();
  };

  /**
   * On calendar drop event
   */
  const onDrop = (event: any) => {
    const date = event["date"];
    const day = date.getDate();
    const month = date.getMonth();
    const year = date.getFullYear();

    const currectDate = new Date();
    const currentHour = currectDate.getHours();
    const currentMin = currectDate.getMinutes();
    const currentSec = currectDate.getSeconds();
    const modifiedDate = new Date(
      year,
      month,
      day,
      currentHour,
      currentMin,
      currentSec
    );

    const draggedEl = event.draggedEl;
    const draggedElclass = draggedEl.className;
    if (
      draggedEl.classList.contains("external-event") &&
      draggedElclass.indexOf("fc-event-draggable") === -1
    ) {
      const modifiedData = {
        id: Math.floor(Math.random() * 1000),
        title: draggedEl.innerText,
        start: modifiedDate,
        className: draggedEl.className,
      };
      dispatch(onAddNewEvent(modifiedData));
    }
  };

  return (
    <React.Fragment>
      <Head title= "Calendar | Velzon - React Admin & Dashboard Template"/>
      <DeleteModal
        show={deleteModal}
        onDeleteClick={handleDeleteEvent}
        onCloseClick={() => { setDeleteModal(false) }} />
      <div className="page-content">
        <Container fluid>
          <BreadCrumb title="Calendar" pageTitle="Apps" />
          <Row>
            <Col xs={12}>
              <Row>
                <Col xl={3}>
                  <Card className="card-h-100">
                    <Card.Body>
                      <button
                        className="btn btn-primary w-100"
                        id="btn-new-event"
                        onClick={toggle}
                      >
                        <i className="mdi mdi-plus"></i> Create New Event
                      </button>

                      <div id="external-events">
                        <br />
                        <p className="text-muted">
                          Drag and drop your event or click in the calendar
                        </p>
                        {categories &&
                          categories.map((category: any) => (
                            <div
                              className={`bg-${category.type}-subtle external-event fc-event text-${category.type}`}
                              key={"cat-" + category.id}
                              draggable
                              onDrag={(event: any) => {
                                onDrag(event);
                              }}
                            >
                              <i className="mdi mdi-checkbox-blank-circle font-size-11 me-2" />
                              {category.title}
                            </div>
                          ))}
                      </div>
                    </Card.Body>
                  </Card>
                  <div>
                    <h5 className="mb-1">Upcoming Events</h5>
                    <p className="text-muted">Don't miss scheduled events</p>
                    <SimpleBar
                      className="pe-2 me-n1 mb-3"
                      style={{ height: "400px" }}
                    >
                      <div id="upcoming-event-list">
                        {events &&
                          (events || []).map((event: any, key: any) => (
                            <React.Fragment key={key}>
                              <UpcommingEvents event={event} />
                            </React.Fragment>
                          ))}
                      </div>
                    </SimpleBar>
                  </div>

                  <Card>
                    <Card.Body className="bg-info-subtle">
                      <div className="d-flex">
                        <div className="flex-shrink-0">
                          <FeatherIcon
                            icon="calendar"
                            className="text-info icon-dual-info"
                          />
                        </div>
                        <div className="flex-grow-1 ms-3">
                          <h6 className="fs-15">Welcome to your Calendar!</h6>
                          <p className="text-muted mb-0">
                            Event that applications book will appear here. Click
                            on an event to see the details and manage applicants
                            event.
                          </p>
                        </div>
                      </div>
                    </Card.Body>
                  </Card>
                </Col>

                <Col xl={9}>
                  <Card className="card-h-100">
                    <Card.Body>
                      <FullCalendar
                        plugins={[
                          BootstrapTheme,
                          dayGridPlugin,
                          interactionPlugin,
                          listPlugin
                        ]}
                        initialView="dayGridMonth"
                        slotDuration={"00:15:00"}
                        handleWindowResize={true}
                        themeSystem="bootstrap"
                        headerToolbar={{
                          left: "prev,next today",
                          center: "title",
                          right: "dayGridMonth,dayGridWeek,dayGridDay,listWeek",
                        }}
                        events={events}
                        editable={true}
                        droppable={true}
                        selectable={true}
                        dateClick={handleDateClick}
                        eventClick={handleEventClick}
                        drop={onDrop}
                      />
                    </Card.Body>
                  </Card>
                </Col>
              </Row>

              <div style={{ clear: "both" }}></div>

              <Modal show={modal} onHide={toggle} id="event-modal" centered>
                <Modal.Header className="p-3 bg-info-subtle" closeButton>
                  <h5 className="modal-title">
                    {!!isEdit ? eventName : "Add Event"}
                  </h5>
                </Modal.Header>
                <Modal.Body>
                  <Form
                    className={!!isEdit ? "needs-validation view-event" : "needs-validation"}
                    name="event-form"
                    id="form-event"
                    onSubmit={(e) => {
                      e.preventDefault();
                      validation.handleSubmit();
                      return false;
                    }}
                  >
                    {!!isEdit ? (
                      <div className="text-end">
                        <Link
                          href="#"
                          className="btn btn-sm btn-soft-primary"
                          id="edit-event-btn"
                          onClick={(e: any) => {
                            e.preventDefault();
                            submitOtherEvent();
                            return false;
                          }}>
                          Edit
                        </Link>
                      </div>
                    ) : null}
                    <div className="event-details">
                      <div className="d-flex mb-2">
                        <div className="flex-grow-1 d-flex align-items-center">
                          <div className="flex-shrink-0 me-3">
                            <i className="ri-calendar-event-line text-muted fs-16"></i>
                          </div>
                          <div className="flex-grow-1">
                            <h6 className="d-block fw-semibold mb-0" id="event-start-date-tag">
                              {event ? event.datetag : ""}
                            </h6>
                          </div>
                        </div>
                      </div>
                      <div className="d-flex align-items-center mb-2">
                        <div className="flex-shrink-0 me-3">
                          <i className="ri-time-line text-muted fs-16"></i>
                        </div>
                        <div className="flex-grow-1">
                          <h6 className="d-block fw-semibold mb-0"><span id="event-timepicker1-tag">12:00 AM</span> - <span id="event-timepicker2-tag">5:30 AM</span></h6>
                        </div>
                      </div>
                      <div className="d-flex align-items-center mb-2">
                        <div className="flex-shrink-0 me-3">
                          <i className="ri-map-pin-line text-muted fs-16"></i>
                        </div>
                        <div className="flex-grow-1">
                          <h6 className="d-block fw-semibold mb-0">
                            <span id="event-location-tag">
                              {event && event.location !== undefined ? event.location : "No Location"}
                            </span>
                          </h6>
                        </div>
                      </div>
                      <div className="d-flex mb-3">
                        <div className="flex-shrink-0 me-3">
                          <i className="ri-discuss-line text-muted fs-16"></i>
                        </div>
                        <div className="flex-grow-1">
                          <p className="d-block text-muted mb-0" id="event-description-tag">
                            {event && event.description !== undefined ? event.description : "No Description"}
                          </p>
                        </div>
                      </div>
                    </div>
                    <Row className="event-form">
                      <Col xs={12}>
                        <div className="mb-3">
                          <Form.Label className="form-label">Type</Form.Label>
                          <select className={!!isEdit ? "form-select d-none" : "form-select d-block"}
                            name="category"
                            id="event-category"
                            onChange={validation.handleChange}
                            onBlur={validation.handleBlur}
                            value={validation.values.category || ""}>
                            <option value="bg-danger-subtle">Danger</option>
                            <option value="bg-success-subtle">Success</option>
                            <option value="bg-primary-subtle">Primary</option>
                            <option value="bg-info-subtle">Info</option>
                            <option value="bg-dark-subtle">Dark</option>
                            <option value="bg-warning-subtle">Warning</option>
                          </select>
                          {validation.touched.category && validation.errors.category ? (
                            <Form.Control.Feedback type="invalid" className="d-block">{validation.errors.category}</Form.Control.Feedback>
                          ) : null}
                        </div>
                      </Col>
                      <Col xs={12}>
                        <div className="mb-3">
                          <Form.Label className="form-label">Event Name</Form.Label>
                          <Form.Control
                            className={!!isEdit ? "d-none" : "d-block"}
                            placeholder="Enter event name"
                            type="text"
                            name="title"
                            id="event-title"
                            onChange={validation.handleChange}
                            onBlur={validation.handleBlur}
                            value={validation.values.title || ""} />
                          {validation.touched.title && validation.errors.title ? (
                            <Form.Control.Feedback type="invalid" className="d-block">{validation.errors.title}</Form.Control.Feedback>)
                            : null}
                        </div>
                      </Col>
                      <Col xs={12}>
                        <div className="mb-3">
                          <Form.Label>Event Date</Form.Label>
                          <div className={!!isEdit ? "input-group d-none" : "input-group"}>
                            <Flatpickr
                              data-enable-time
                              className="form-control"
                              id="event-start-date"
                              name="defaultDate"
                              placeholder="Select Date"
                              value={validation.values.defaultDate || ""}
                              options={{
                                mode: "range",
                                dateFormat: "Y-m-d",
                              }}
                              onChange={(date: any) => { setSelectedNewDay(date); validation.setFieldValue("defaultDate", date) }}
                            />
                            <span className="input-group-text">
                              <i className="ri-calendar-event-line"></i>
                            </span>
                          </div>
                          {validation.touched.defaultDate && validation.errors.defaultDate ? (
                            <Form.Control.Feedback type="invalid" className="d-block">{validation.errors.defaultDate} </Form.Control.Feedback>
                          ) : null}
                        </div>
                      </Col>
                      <Col xs={6}>
                        <div className="mb-3">
                          <Form.Label>Start Time</Form.Label>
                          <div className="input-group">
                            <Flatpickr className="form-control"
                              name="start"
                              value={validation.values.start || ""}
                              onChange={(date: any) => validation.setFieldValue("start", date[0])}
                              options={{
                                enableTime: true,
                                noCalendar: true,
                                dateFormat: "H:i",
                              }} />
                            <span className="input-group-text"> <i className="ri-calendar-event-line"></i> </span>
                          </div>
                          {validation.touched.start && validation.errors.start ? (
                            <Form.Control.Feedback type="invalid" className="d-block">{validation.errors.start} </Form.Control.Feedback>
                          ) : null}
                        </div>
                      </Col>

                      <Col xs={6}>
                        <div className="mb-3">
                          <Form.Label>End Time</Form.Label>
                          <div className="input-group">
                            <Flatpickr className="form-control input-group"
                              name="end"
                              value={validation.values.end || ""}
                              onChange={(date: any) => validation.setFieldValue("end", date[0])}
                              options={{
                                enableTime: true,
                                noCalendar: true,
                                dateFormat: "H:i",
                              }} />
                            <span className="input-group-text"> <i className="ri-calendar-event-line"></i> </span>
                          </div>
                          {validation.touched.end && validation.errors.end ? (
                            <Form.Control.Feedback type="invalid" className="d-block">{validation.errors.end} </Form.Control.Feedback>
                          ) : null}
                        </div>
                      </Col>
                      <Col xs={12}>
                        <div className="mb-3">
                          <Form.Label htmlFor="event-location">Location</Form.Label>
                          <div>
                            <Form.Control
                              type="text"
                              className={!!isEdit ? "d-none" : "d-block"}
                              name="location"
                              id="event-location"
                              placeholder="Event location"
                              onChange={validation.handleChange}
                              onBlur={validation.handleBlur}
                              value={validation.values.location} />
                            {validation.touched.location && validation.errors.location ? (
                              <Form.Control.Feedback type="invalid" className="d-block">{validation.errors.location}</Form.Control.Feedback>
                            ) : null}
                          </div>
                        </div>
                      </Col>
                      <Col xs={12}>
                        <div className="mb-3">
                          <Form.Label className="form-label">Description</Form.Label>
                          <textarea
                            className={!!isEdit ? "form-control d-none" : "form-control d-block"}
                            id="event-description"
                            name="description"
                            placeholder="Enter a description"
                            rows={3}
                            onChange={validation.handleChange}
                            onBlur={validation.handleBlur}
                            value={validation.values.description}></textarea>
                          {validation.touched.description && validation.errors.description ? (
                            <Form.Control.Feedback type="invalid" className="d-block">{validation.errors.description}</Form.Control.Feedback>
                          ) : null}
                        </div>
                      </Col>
                    </Row>
                    <div className="hstack gap-2 justify-content-end">
                      {!!isEdit && (
                        <button type="button" className="btn btn-soft-danger" id="btn-delete-event" onClick={() => { toggle(); setDeleteModal(true) }}>
                          <i className="ri-close-line align-bottom"></i> Delete
                        </button>
                      )}
                      {isEditButton &&
                        <button type="submit" className="btn btn-success" id="btn-save-event">
                          {!!isEdit ? "Edit Event" : "Add Event"}
                        </button>}
                    </div>
                  </Form>
                </Modal.Body>
              </Modal>
            </Col>
          </Row>
        </Container>
      </div>
    </React.Fragment>
  );
};

Calender.propTypes = {
  events: PropTypes.any,
  categories: PropTypes.array,
  className: PropTypes.string,
  onGetEvents: PropTypes.func,
  onAddNewEvent: PropTypes.func,
  onUpdateEvent: PropTypes.func,
  onDeleteEvent: PropTypes.func,
  onGetCategories: PropTypes.func,
};
Calender.layout = (page: any) => <Layout children={page} />
export default Calender;
