// React+Inertia/Modern/resources/js/Pages/DashboardCrm/index.tsx
import React from 'react';
import { Container, Row } from 'react-bootstrap';
import BreadCrumb from '../../Components/Common/BreadCrumb';
import BalanceOverview from './BalanceOverview';
import ClosingDeals from './ClosingDeals';
import DealsStatus from './DealsStatus';
import DealType from './DealType';
import MyTasks from './MyTasks';
import SalesForecast from './SalesForecast';
import UpcomingActivities from './UpcomingActivities';
import Widgets from './Widgets';
import { Head } from '@inertiajs/react';
import Layout from '../../Layouts';


const DashboardCrm = () => {
    return (
        <React.Fragment>
            <Head title="CRM | Velzon - React Admin & Dashboard Template" />
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="CRM" pageTitle="Dashboards" />
                    <Row>
                        <Widgets />
                    </Row>
                    <Row>
                        <SalesForecast />
                        <DealType />
                        <BalanceOverview />
                    </Row>
                    <Row>
                        <DealsStatus />
                        <MyTasks />
                    </Row>
                    <Row>
                        <UpcomingActivities />
                        <ClosingDeals />
                    </Row>
                </Container>
            </div>
        </React.Fragment>
    );
};
DashboardCrm.layout = (page: any) => <Layout children={page} />
export default DashboardCrm;

// Svelte/master/src/routes/dashboard-crm/+page.svelte
<svelte:head>
  <title>CRM | Velzon - Svelte Admin & Dashboard Template</title>
</svelte:head>
<script>
	import { Container, Row } from 'sveltestrap';
	import BreadCrumb from '../../Components/Common/BreadCrumb.svelte';

	import BalanceOverview from './BalanceOverview.svelte';
	import ClosingDeals from './ClosingDeals.svelte';
	import DealsStatus from './DealsStatus.svelte';
	import DealType from './DealType.svelte';
	import MyTasks from './MyTasks.svelte';
	import SalesForecast from './SalesForecast.svelte';
	import UpcomingActivities from './UpcomingActivities.svelte';
	import Widgets from './Widgets.svelte';
	import Counter from '../../Components/Common/CounterPage.svelte'
</script>
<Counter />
<div class="page-content">
	<Container fluid>
		<BreadCrumb title="CRM" pageTitle="Dashboards" />
		<Row>
			<Widgets />
		</Row>
		<Row>
			<SalesForecast />
			<DealType />
			<BalanceOverview />
		</Row>
		<Row>
			<DealsStatus />
			<MyTasks />
		</Row>
		<Row>
			<UpcomingActivities />
			<ClosingDeals />
		</Row>
	</Container>
</div>
