// React+TS/Master/src/pages/DashboardCrm/DashboardCrmCharts.tsx
import React from 'react';
import ReactApexChart from "react-apexcharts";
import useChartColors from 'Components/Common/useChartColors';

const SalesForecastCharts = ({ chartId, series }: any) => {
    const chartColors = useChartColors(chartId);

    var options: any = {
        chart: {
            type: 'bar',
            height: 341,
            toolbar: {
                show: false,
            },
        },
        plotOptions: {
            bar: {
                horizontal: false,
                columnWidth: '65%',
            },
        },
        stroke: {
            show: true,
            width: 5,
            colors: ['transparent']
        },
        xaxis: {
            categories: [''],
            axisTicks: {
                show: false,
                borderType: 'solid',
                color: '#78909C',
                height: 6,
                offsetX: 0,
                offsetY: 0
            },
            title: {
                text: 'Total Forecasted Value',
                offsetX: 0,
                offsetY: -30,
                style: {
                    color: '#78909C',
                    fontSize: '12px',
                    fontWeight: 400,
                },
            },
        },
        yaxis: {
            labels: {
                formatter: function (value: any) {
                    return "$" + value + "k";
                }
            },
            tickAmount: 4,
            min: 0
        },
        fill: {
            opacity: 1
        },
        legend: {
            show: true,
            position: 'bottom',
            horizontalAlign: 'center',
            fontWeight: 500,
            offsetX: 0,
            offsetY: -14,
            itemMargin: {
                horizontal: 8,
                vertical: 0
            },
            markers: {
                width: 10,
                height: 10,
            }
        },
        colors: chartColors
    };
    return (
        <React.Fragment>
            <ReactApexChart dir="ltr"
                options={options}
                series={series}
                id={chartId}
                type="bar"
                height="341"

                data-colors='["--vz-primary", "--vz-success", "--vz-warning"]'
                data-colors-minimal='["--vz-primary-rgb, 0.75", "--vz-primary", "--vz-primary-rgb, 0.55"]'
                data-colors-creative='["--vz-primary", "--vz-secondary", "--vz-info"]'
                data-colors-corporate='["--vz-primary", "--vz-success", "--vz-secondary"]'
                data-colors-galaxy='["--vz-primary", "--vz-secondary", "--vz-info"]'
                data-colors-classic='["--vz-primary", "--vz-warning", "--vz-secondary"]'
                className="apex-charts"
            />
        </React.Fragment>
    );
};

const DealTypeCharts = ({ chartId, series }: any) => {
    const chartColors = useChartColors(chartId);


    var options: any = {
        chart: {
            height: 341,
            type: 'radar',
            dropShadow: {
                enabled: true,
                blur: 1,
                left: 1,
                top: 1
            },
            toolbar: {
                show: false
            },
        },
        stroke: {
            width: 2
        },
        fill: {
            opacity: 0.2
        },
        legend: {
            show: true,
            fontWeight: 500,
            offsetX: 0,
            offsetY: -8,
            markers: {
                width: 8,
                height: 8,
                radius: 6,
            },
            itemMargin: {
                horizontal: 10,
                vertical: 0
            }
        },
        markers: {
            size: 0
        },
        colors: chartColors,
        xaxis: {
            categories: ['2016', '2017', '2018', '2019', '2020', '2021']
        }
    };
    return (
        <React.Fragment>
            <ReactApexChart dir="ltr"
                options={options}
                series={series}
                id={chartId}
                type="radar"
                height="341"

                data-colors='["--vz-warning", "--vz-danger", "--vz-success"]'
                data-colors-minimal='["--vz-primary-rgb, 0.15", "--vz-primary-rgb, 0.35", "--vz-primary-rgb, 0.45"]'
                data-colors-modern='["--vz-warning", "--vz-secondary", "--vz-success"]'
                data-colors-interactive='["--vz-warning", "--vz-info", "--vz-primary"]'
                data-colors-corporate='["--vz-secondary", "--vz-info", "--vz-success"]'
                data-colors-classic='["--vz-secondary", "--vz-danger", "--vz-success"]'
                className="apex-charts"
            />
        </React.Fragment>
    );
};

const BalanceOverviewCharts = ({ chartId, series }: any) => {
    const chartColors = useChartColors(chartId);


    var options: any = {
        chart: {
            height: 290,
            type: 'area',
            toolbar: 'false',
        },
        dataLabels: {
            enabled: false
        },
        stroke: {
            curve: 'smooth',
            width: 2,
        },
        xaxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        yaxis: {
            labels: {
                formatter: function (value: any) {
                    return "$" + value + "k";
                }
            },
            tickAmount: 5,
            min: 0,
            max: 260
        },
        colors: chartColors,
        fill: {
            opacity: 0.06,
            colors: chartColors,
            type: 'solid'
        }
    };
    return (
        <React.Fragment>
            <ReactApexChart dir="ltr"
                options={options}
                series={series}
                id={chartId}
                type="area"
                height="290"

                data-colors='["--vz-success", "--vz-danger"]'
                data-colors-minimal='["--vz-primary", "--vz-info"]'
                data-colors-interactive='["--vz-info", "--vz-primary"]'
                data-colors-galaxy='["--vz-primary", "--vz-secondary"]'
                data-colors-classic='["--vz-primary", "--vz-secondary"]'
                className="apex-charts"
            />
        </React.Fragment>
    );
};

export { SalesForecastCharts, DealTypeCharts, BalanceOverviewCharts };

// Svelte/master/src/routes/dashboard-crm/DashboardCrmCharts.svelte
<script>
	import { onMount } from "svelte";
	import { themeChangeEvent } from "$lib/eventBus";
	import { browser } from "$app/environment";
	export let dataColors;
	let chart;

	function getChartColorsArray(colors) {
		if (browser) {
			return colors.map(function (value) {
				var newValue = value.replace(" ", "");
				if (newValue.indexOf(",") === -1) {
					var color = getComputedStyle(
						document.documentElement
					).getPropertyValue(newValue);
					if (color.indexOf("#") !== -1)
						color = color.replace(" ", "");
					if (color) return color;
					else return newValue;
				} else {
					var val = value.split(",");
					if (val.length === 2) {
						var rgbaColor = getComputedStyle(
							document.documentElement
						).getPropertyValue(val[0]);
						rgbaColor = "rgba(" + rgbaColor + "," + val[1] + ")";
						return rgbaColor;
					} else {
						return newValue;
					}
				}
			});
		}
	}

	const areachartSalesColors = getChartColorsArray(dataColors);

	const THEME_CHART_COLORS = {
		default: ["--vz-primary", "--vz-success", "--vz-warning"],
		minimal: ["--vz-primary-rgb, 0.75", "--vz-primary", "--vz-primary-rgb, 0.55"],
		creative: ["--vz-primary", "--vz-secondary", "--vz-info"],
		corporate: ["--vz-primary", "--vz-success", "--vz-secondary"],
		galaxy: ["--vz-primary", "--vz-secondary", "--vz-info"], 
		classic: ["--vz-primary", "--vz-warning", "--vz-secondary"],
		modern: ["--vz-primary", "--vz-success", "--vz-warning"],
		interactive: ["--vz-primary", "--vz-success", "--vz-warning"],
		vintage: ["--vz-primary", "--vz-success", "--vz-warning"],
		saas: ["--vz-primary", "--vz-success", "--vz-warning"],
		material: ["--vz-primary", "--vz-success", "--vz-warning"],
	};

	// Function to find the index of a key
	function findIndexByKey(key) {
		const keys = Object.keys(THEME_CHART_COLORS);
		return keys.indexOf(key);
	}

	// Subscribe to the theme change event
	const unsubscribeEvent = themeChangeEvent.subscribe((newTheme) => {
		// Handle the theme change event
		if(newTheme == null || newTheme == undefined){
			return;
		}
		let key = findIndexByKey(newTheme);
		let newColors;
		if (key >= 0) {
			newColors = THEME_CHART_COLORS[newTheme];
		}
		if (browser) {
			newColors = ( key >= 0) ? getChartColorsArray(newColors) : dataColors;
			setTimeout(() => {
				chart.updateOptions({
					colors: newColors,
				});
			}, 500);
		}
	});

	var options = {
		chart: {
			type: "bar",
			height: 341,
			toolbar: {
				show: false,
			},
		},
		series: [
			{
				name: "Goal",
				data: [37],
			},
			{
				name: "Pending Forcast",
				data: [12],
			},
			{
				name: "Revenue",
				data: [18],
			},
		],
		plotOptions: {
			bar: {
				horizontal: false,
				columnWidth: "65%",
			},
		},
		stroke: {
			show: true,
			width: 5,
			colors: ["transparent"],
		},
		xaxis: {
			categories: [""],
			axisTicks: {
				show: false,
				borderType: "solid",
				color: "#78909C",
				height: 6,
				offsetX: 0,
				offsetY: 0,
			},
			title: {
				text: "Total Forecasted Value",
				offsetX: 0,
				offsetY: -30,
				style: {
					color: "#78909C",
					fontSize: "12px",
					fontWeight: 400,
				},
			},
		},
		yaxis: {
			labels: {
				formatter: function (value) {
					return "$" + value + "k";
				},
			},
			tickAmount: 4,
			min: 0,
		},
		fill: {
			opacity: 1,
		},
		legend: {
			show: true,
			position: "bottom",
			horizontalAlign: "center",
			fontWeight: 500,
			offsetX: 0,
			offsetY: -14,
			itemMargin: {
				horizontal: 8,
				vertical: 0,
			},
			markers: {
				width: 10,
				height: 10,
			},
		},
		colors: areachartSalesColors,
	};
	onMount(() => {
			chart = new ApexCharts(
			document.querySelector("#dashboardcrmchart"),
			options
		);
		chart.render();
	});
</script>

<div id="dashboardcrmchart" class="apex-charts" dir="ltr" />
