// React+TS/Master/src/pages/Crypto/BuySell/Market.tsx
import React, { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardBody, CardHeader, Col, Row } from 'reactstrap';
import { market } from '../../../common/data';
import TableContainer from '../../../Components/Common/TableContainer';
import {
    Price,
    Pairs,
    HighPrice,
    LowPrice,
    MarketVolume
} from "./MarketCol";

const Market = () => {
    const columns = useMemo(
        () => [
            {
                header: "Currency",
                accessorKey: "coinName",
                enableColumnFilter: false,
                cell: (cell: any) => (
                    <>
                        <div className="d-flex align-items-center fw-medium">
                            <img src={cell.row.original.img} alt="" className="avatar-xxs me-2" />
                            <Link to="#" className="currency_name">{cell.getValue()}</Link>
                        </div>
                    </>
                ),
            },
            {
                header: "Price",
                accessorKey: "price",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <Price {...cell} />;
                },
            },
            {
                header: "Pairs",
                accessorKey: "pairs",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <Pairs {...cell} />;
                },
            },
            {
                header: "24 High",
                accessorKey: "high",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <HighPrice {...cell} />;
                },
            },
            {
                header: "24 Low",
                accessorKey: "low",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <LowPrice {...cell} />;
                },
            },
            {
                header: "Market Volume",
                accessorKey: "marketVolume",
                enableColumnFilter: false,
                cell: (cell: any) => {
                    return <MarketVolume {...cell} />;
                },
            },
            {
                header: "Volume %",
                accessorKey: "percentage",
                enableColumnFilter: false,
                cell: (cell: any) => (
                    <>
                        <h6 className={"text-" + cell.row.original.iconClass + " fs-13 mb-0"}>
                            <i className={cell.row.original.icon + " align-middle me-1"}></i>
                            {cell.getValue()}
                        </h6>
                    </>
                ),
            },
            {
                header: "Action",
                cell: () => (
                    <>
                        <button className="btn btn-sm btn-soft-info material-shadow-none">Trade Now</button>
                    </>
                ),
            },
        ],
        []
    );
    return (
        <React.Fragment>
            <Card>
                <CardHeader className="border-bottom-dashed">
                    <Row className="align-items-center">
                        <Col xs={3}>
                            <h5 className="card-title mb-0">Markets</h5>
                        </Col>
                        <div className="col-auto ms-auto">
                            <div className="d-flex gap-2">
                                <button className="btn btn-success"><i className="ri-equalizer-line align-bottom me-1"></i> Filters</button>
                            </div>
                        </div>
                    </Row>
                </CardHeader>
                <CardBody className="p-0 border-bottom border-bottom-dashed">
                    <div className="search-box">
                        <input type="text" className="form-control search border-0 py-3" placeholder="Search to currency..." />
                        <i className="ri-search-line search-icon"></i>
                    </div>
                </CardBody>
                <CardBody>
                    <TableContainer
                        columns={columns}
                        data={(market || [])}
                        customPageSize={8}
                        divClass="table-responsive table-card"
                        tableClass="align-middle table-nowrap"
                        theadClass="table-light text-muted"
                    />
                </CardBody>
            </Card>
        </React.Fragment>
    );
};

export default Market;

// Svelte/master/src/routes/crypto/buysell/Market.svelte
<script>
    import { Card, CardBody, CardHeader, Col, Row } from "sveltestrap";
    import { html } from "gridjs";
    import Grid from "gridjs-svelte";
    import cryptoData from "../../../common/data/cryptoPage";

    const data = cryptoData.market;

    const columns = [
        {
            id: "coinName",
            hidden: true,
        },
        {
            name: "Currency",
            id: "img",
            sort:true,
            formatter: (cell, row) =>
                html(`<div class="d-flex align-items-center fw-medium">
                <img src=${cell} alt="" class="avatar-xxs me-2" />
                <a href={null} class="currency_name">${row.cells[0].data}</a>
            </div>`),
        },
        {
            name: "Price",
            id: "price",
            sort:true,
        },
        {
            name: "Pairs",
            id: "pairs",
            sort:true,
        },
        {
            name: "24 High",
            id: "high",
            sort:true,
        },
        {
            name: "24 Low",
            id: "low",
            sort:true,
        },
        {
            name: "Market Volume",
            id: "marketVolume",
            sort:true,
        },
        {
            id: "percentage",
            hidden: true,
        },
        {
            id: "icon",
            hidden: true,
        },
        {
            name: "Volume %",
            id: "iconClass",
            sort:true,
            formatter: (cell, row) =>
                html(`<h6 class="text-${cell} fs-13 mb-0">
                    <i class="${row.cells[8].data} align-middle me-1"></i>
                    ${row.cells[7].data}
                </h6>`),
        },
        {
            name: "Action",
            formatter: (cell) =>
                html(
                    `<button class="btn btn-sm btn-soft-info material-shadow-none">Trade Now</button>`
                ),
        },
    ];
</script>

<Card>
    <CardHeader class="border-bottom-dashed">
        <Row class="align-items-center">
            <Col xs={3}>
                <h5 class="card-title mb-0">Markets</h5>
            </Col>
            <div class="col-auto ms-auto">
                <div class="d-flex gap-2">
                    <button class="btn btn-success"
                        ><i class="ri-equalizer-line align-bottom me-1" /> Filters</button
                    >
                </div>
            </div>
        </Row>
    </CardHeader>
    <CardBody class="p-0 border-bottom border-bottom-dashed">
        <div class="search-box">
            <input
                type="text"
                class="form-control search border-0 py-3"
                placeholder="Search to currency..."
            />
            <i class="ri-search-line search-icon" />
        </div>
    </CardBody>
    <CardBody>
        <div class="table-card gridjs-border-none">
            <Grid
                {data}
                {columns}
                className={{ th: "text-muted" }}
                pagination={{ enabled: true, limit: 8 }}
            />
        </div>
    </CardBody>
</Card>
