// React+TS/Master/src/pages/Chat/PersonalInfo.tsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import {
  Button,
  Offcanvas,
  OffcanvasBody,
  Dropdown,
  DropdownToggle,
  DropdownMenu,
  DropdownItem,
  UncontrolledDropdown
} from "reactstrap";
import Img9 from "../../assets/images/small/img-9.jpg";
import dummyImage from "../../assets/images/users/user-dummy-img.jpg";
import { attachements } from "../../common/data/chat";

const Attachements = (props:any) => {
  return (
    <div className="border rounded border-dashed p-2">
      <div className="d-flex align-items-center">
        <div className="flex-shrink-0 me-3">
          <div className="avatar-xs"> 
            <div className="avatar-title bg-light text-secondary rounded fs-20">
              <i className={props.attachement.foldericon}></i>
            </div>
          </div>
        </div>
        <div className="flex-grow-1 overflow-hidden">
          <h5 className="fs-13 mb-1">
            <Link to="#" className="text-body text-truncate d-block">
              {props.attachement.foldername}
            </Link>
          </h5>
          <div className="text-muted">{props.attachement.foldersize}</div>
        </div>
        <div className="flex-shrink-0 ms-2">
          <div className="d-flex gap-1">
            <button
              type="button"
              className="btn btn-icon text-muted btn-sm fs-18 material-shadow-none"
            >
              <i className="ri-download-2-line"></i>
            </button>
            <UncontrolledDropdown>
              <DropdownToggle
                tag="button"
                className="btn btn-icon text-muted btn-sm fs-18 dropdown material-shadow-none"
              >
                <i className="ri-more-fill"></i>
              </DropdownToggle>
              <DropdownMenu>
                <DropdownItem>
                  <i className="ri-share-line align-bottom me-2 text-muted"></i>{" "}
                  Share
                </DropdownItem>
                <DropdownItem>
                  <i className="ri-bookmark-line align-bottom me-2 text-muted"></i>{" "}
                  Bookmark
                </DropdownItem>
                <DropdownItem>
                  <i className="ri-delete-bin-line align-bottom me-2 text-muted"></i>{" "}
                  Delete
                </DropdownItem>
              </DropdownMenu>
            </UncontrolledDropdown>
          </div>
        </div>
      </div>
    </div>
  );
};

const PersonalInfo = ({ show, onCloseClick, currentuser, cuurentiseImg }:any) => {
  const [menu1, setMenu1] = useState<boolean>(false);
  const [menu2, setMenu2] = useState<boolean>(false);

  return (
    <Offcanvas
      isOpen={show}
      direction="end"
      className="offcanvas-end border-0"
      toggle={onCloseClick}
    >
      <OffcanvasBody className="offcanvas-body profile-offcanvas p-0">
        <div className="team-cover">
          <img src={Img9} alt="" className="img-fluid" />
        </div>
        <div className="p-1 pb-4 pt-0">
          <div className="team-settings">
            <div className="row g-0">
              <div className="col">
                <div className="btn nav-btn">
                  <Button
                    onClick={onCloseClick}
                    color=""
                    className="btn-close btn-close-white"
                  ></Button>
                </div>
              </div>
              <div className="col-auto">
                <div className="user-chat-nav d-flex">
                  <button
                    type="button"
                    className="btn nav-btn favourite-btn active"
                  >
                    <i className="ri-star-fill"></i>
                  </button>

                  <Dropdown isOpen={menu1} toggle={() => setMenu1(!menu1)}>
                    <DropdownToggle className="btn nav-btn" tag="a">
                      <i className="ri-more-2-fill"></i>
                    </DropdownToggle>
                    <DropdownMenu className="dropdown-menu-end">
                      <DropdownItem href="#">
                        <i className="ri-inbox-archive-line align-bottom text-muted me-2"></i>
                        Archive
                      </DropdownItem>
                      <DropdownItem href="#">
                        <i className="ri-mic-off-line align-bottom text-muted me-2"></i>
                        Muted
                      </DropdownItem>
                      <DropdownItem href="#">
                        <i className="ri-delete-bin-5-line align-bottom text-muted me-2"></i>
                        Delete
                      </DropdownItem>
                    </DropdownMenu>
                  </Dropdown>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="p-3 text-center">
        {cuurentiseImg ?
        
          <img
            src={cuurentiseImg}
            alt=""
            className="avatar-lg img-thumbnail rounded-circle mx-auto profile-img"
          />
          :
          <img 
          src={dummyImage}
          alt="" 
          className="avatar-lg img-thumbnail rounded-circle mx-auto profile-img" />
        }
          <div className="mt-3">
            <h5 className="fs-16 mb-1">
              <Link to="#" className="link-primary username">
                {currentuser}
              </Link>
            </h5>
            <p className="text-muted">
              <i className="ri-checkbox-blank-circle-fill me-1 align-bottom text-success"></i>
              Online
            </p>
          </div>
          <div className="d-flex gap-2 justify-content-center">
            <button
              type="button"
              className="btn avatar-xs p-0"
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Message"
            >
              <span className="avatar-title rounded bg-light text-body">
                <i className="ri-question-answer-line"></i>
              </span>
            </button>

            <button
              type="button"
              className="btn avatar-xs p-0"
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Favourite"
            >
              <span className="avatar-title rounded bg-light text-body">
                <i className="ri-star-line"></i>
              </span>
            </button>

            <button
              type="button"
              className="btn avatar-xs p-0"
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Phone"
            >
              <span className="avatar-title rounded bg-light text-body">
                <i className="ri-phone-line"></i>
              </span>
            </button>

            <Dropdown isOpen={menu2} toggle={() => setMenu2(!menu2)}>
              <DropdownToggle className="btn avatar-xs p-0" tag="a">
                <span className="avatar-title bg-light text-body rounded">
                  <i className="ri-more-fill"></i>
                </span>
              </DropdownToggle>
              <DropdownMenu className="dropdown-menu-end">
                <DropdownItem href="#">
                  <i className="ri-inbox-archive-line align-bottom text-muted me-2"></i>
                  Archive
                </DropdownItem>
                <DropdownItem href="#">
                  <i className="ri-mic-off-line align-bottom text-muted me-2"></i>
                  Muted
                </DropdownItem>
                <DropdownItem href="#">
                  <i className="ri-delete-bin-5-line align-bottom text-muted me-2"></i>
                  Delete
                </DropdownItem>
              </DropdownMenu>
            </Dropdown>
          </div>
        </div>
        <div className="border-top border-top-dashed p-3">
          <h5 className="fs-15 mb-3">Personal Details</h5>
          <div className="mb-3">
            <p className="text-muted text-uppercase fw-medium fs-12 mb-1">
              Number
            </p>
            <h6>+(256) 2451 8974</h6>
          </div>
          <div className="mb-3">
            <p className="text-muted text-uppercase fw-medium fs-12 mb-1">
              Email
            </p>
            <h6>lisaparker@gmail.com</h6>
          </div>
          <div>
            <p className="text-muted text-uppercase fw-medium fs-12 mb-1">
              Location
            </p>
            <h6 className="mb-0">California, USA</h6>
          </div>
        </div>

        <div className="border-top border-top-dashed p-3">
          <h5 className="fs-15 mb-3">Attached Files</h5>

          <div className="vstack gap-2">
            {attachements.map((attachement, key) => (
              <Attachements attachement={attachement} key={key} />
            ))}

            <div className="text-center mt-2">
              <button type="button" className="btn btn-danger">
                Load more{" "}
                <i className="ri-arrow-right-fill align-bottom ms-1"></i>
              </button>
            </div>
          </div>
        </div>
      </OffcanvasBody>
    </Offcanvas>
  );
};

export default PersonalInfo;

// Svelte/interactive/src/routes/apps-chat/PersonalInfo.svelte
<script>
  import Link from "svelte-link";
  import {onMount} from "svelte";
  import {
    Button,
    Offcanvas,
    Dropdown,
    DropdownToggle,
    DropdownMenu,
    DropdownItem,
  } from "sveltestrap";

  import data from "../../common/data/chat";
  import Attachements from "./attachement.svelte";

  export let currentuser, cuurentiseImg, show, onCloseClick;

  import img9 from '../../assets/images/small/img-9.jpg'
  import userdummyimg from '../../assets/images/users/user-dummy-img.jpg'

  onMount(() => {
    let btnfav = document.getElementById("favourite-btn");
    if(btnfav){
      btnfav.addEventListener("click",function(){
        if(btnfav.classList.contains("active")){
          btnfav.classList.remove("active");
        }else{
          btnfav.classList.add("active");

        }
      })
    }
  });

</script>

<Offcanvas
  isOpen={show}
  placement="end"
  class="offcanvas-end border-0 profile-details-canvas"
>
  <div class="profile-offcanvas p-0">
    <div class="team-cover">
      <img src={img9} alt="" class="img-fluid" />
    </div>
    <div class="p-1 pb-4 pt-0">
      <div class="team-settings">
        <div class="row g-0">
          <div class="col">
            <div class="btn nav-btn">
              <Button
                on:click={onCloseClick}
                color=""
                class="btn-close btn-close-white"
              />
            </div>
          </div>
          <div class="col-auto">
            <div class="user-chat-nav d-flex">
              <button type="button" class="btn nav-btn favourite-btn active" id="favourite-btn">
                <i class="ri-star-fill" />
              </button>

              <Dropdown>
                <DropdownToggle
                  class="btn nav-btn p-0 text-white"
                  color=""
                  tag="a"
                >
                  <i class="ri-more-2-fill" />
                </DropdownToggle>
                <DropdownMenu class="dropdown-menu-end">
                  <DropdownItem href={null}>
                    <i
                      class="ri-inbox-archive-line align-bottom text-muted me-2"
                    />
                    Archive
                  </DropdownItem>
                  <DropdownItem href={null}>
                    <i class="ri-mic-off-line align-bottom text-muted me-2" />
                    Muted
                  </DropdownItem>
                  <DropdownItem href={null}>
                    <i
                      class="ri-delete-bin-5-line align-bottom text-muted me-2"
                    />
                    Delete
                  </DropdownItem>
                </DropdownMenu>
              </Dropdown>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="p-3 text-center">
      {#if cuurentiseImg}
        <img
          src={cuurentiseImg}
          alt=""
          class="avatar-lg img-thumbnail rounded-circle mx-auto"
        />
      {:else}
        <img
          src={userdummyimg}
          alt=""
          class="avatar-lg img-thumbnail rounded-circle mx-auto"
        />
      {/if}

      <div class="mt-3">
        <h5 class="fs-16 mb-1">
          <Link href="{null}" class="link-primary username">
            {currentuser}
          </Link>
        </h5>
        <p class="text-muted">
          <i
            class="ri-checkbox-blank-circle-fill me-1 align-bottom text-success"
          />
          Online
        </p>
      </div>
      <div class="d-flex gap-2 justify-content-center">
        <button type="button" class="btn avatar-xs p-0">
          <span class="avatar-title rounded bg-light text-body">
            <i class="ri-question-answer-line" />
          </span>
        </button>

        <button type="button" class="btn avatar-xs p-0">
          <span class="avatar-title rounded bg-light text-body">
            <i class="ri-star-line" />
          </span>
        </button>

        <button type="button" class="btn avatar-xs p-0">
          <span class="avatar-title rounded bg-light text-body">
            <i class="ri-phone-line" />
          </span>
        </button>

        <Dropdown>
          <DropdownToggle class="btn avatar-xs p-0" color="" tag="a">
            <span class="avatar-title bg-light text-body rounded">
              <i class="ri-more-fill" />
            </span>
          </DropdownToggle>
          <DropdownMenu class="dropdown-menu-end">
            <DropdownItem href={null}>
              <i class="ri-inbox-archive-line align-bottom text-muted me-2" />
              Archive
            </DropdownItem>
            <DropdownItem href={null}>
              <i class="ri-mic-off-line align-bottom text-muted me-2" />
              Muted
            </DropdownItem>
            <DropdownItem href={null}>
              <i class="ri-delete-bin-5-line align-bottom text-muted me-2" />
              Delete
            </DropdownItem>
          </DropdownMenu>
        </Dropdown>
      </div>
    </div>
    <div class="border-top border-top-dashed p-3">
      <h5 class="fs-15 mb-3">Personal Details</h5>
      <div class="mb-3">
        <p class="text-muted text-uppercase fw-medium fs-12 mb-1">Number</p>
        <h6>+(256) 2451 8974</h6>
      </div>
      <div class="mb-3">
        <p class="text-muted text-uppercase fw-medium fs-12 mb-1">Email</p>
        <h6>lisaparker@gmail.com</h6>
      </div>
      <div>
        <p class="text-muted text-uppercase fw-medium fs-12 mb-1">Location</p>
        <h6 class="mb-0">California, USA</h6>
      </div>
    </div>

    <div class="border-top border-top-dashed p-3">
      <h5 class="fs-15 mb-3">Attached Files</h5>

      <div class="vstack gap-2">
        {#each data.attachements as attachement}
          <Attachements {attachement} />
        {/each}

        <div class="text-center mt-2">
          <button type="button" class="btn btn-danger">
            Load more{" "}
            <i class="ri-arrow-right-fill align-bottom ms-1" />
          </button>
        </div>
      </div>
    </div>
  </div>
</Offcanvas>
