// React+Inertia/Modern/resources/js/Pages/DashboardAnalytics/Widget.tsx
import React from 'react';
import { Card, Col, Row } from 'react-bootstrap';
import CountUp from "react-countup";

//Import Icons
import FeatherIcon from "feather-icons-react";

const Widget = () => {
    return (
        <React.Fragment>
            <Row>
                <Col md={6}>
                    <Card className="card-animate">
                        <Card.Body>
                            <div className="d-flex justify-content-between">
                                <div>
                                    <p className="fw-medium text-muted mb-0">Users</p>
                                    <h4 className="fs-22 mt-4 ff-secondary fw-semibold">
                                        <span className="counter-value">
                                            <CountUp
                                                start={0}
                                                end={28.05}
                                                decimals={1}
                                                duration={4}
                                            />
                                            0</span>k</h4>
                                    <p className="mb-0 text-muted text-truncate "><span className="badge bg-light text-success mb-0">
                                        <i className="ri-arrow-up-line align-middle"></i> 16.24 %
                                    </span> vs. previous month</p>
                                </div>
                                <div>
                                    <div className="avatar-sm flex-shrink-0">
                                        <span className="avatar-title bg-info-subtle rounded-circle fs-2">
                                            <FeatherIcon
                                                icon="users"
                                                className="text-info"
                                            />
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>

                <Col md={6}>
                    <Card className="card-animate">
                        <Card.Body>
                            <div className="d-flex justify-content-between">
                                <div>
                                    <p className="fw-medium text-muted mb-0">Sessions</p>
                                    <h4 className="fs-22 mt-4 ff-secondary fw-semibold">
                                        <span className="counter-value" data-target="97.66">
                                            <CountUp
                                                start={0}
                                                end={97.66}
                                                decimals={2}
                                                duration={4}
                                            />
                                        </span>k</h4>
                                    <p className="mb-0 text-muted text-truncate "><span className="badge bg-light text-danger mb-0">
                                        <i className="ri-arrow-down-line align-middle"></i> 3.96 %
                                    </span> vs. previous month</p>
                                </div>
                                <div>
                                    <div className="avatar-sm flex-shrink-0">
                                        <span className="avatar-title bg-info-subtle rounded-circle fs-2">
                                            <FeatherIcon
                                                icon="activity"
                                                className="text-info"
                                            />
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            <Row>
                <Col md={6}>
                    <Card className="card-animate">
                        <Card.Body>
                            <div className="d-flex justify-content-between">
                                <div>
                                    <p className="fw-medium text-muted mb-0">Avg. Visit Duration</p>
                                    <h4 className="fs-22 mt-4 ff-secondary fw-semibold">
                                        <span className="counter-value" data-target="3">
                                            <CountUp
                                                start={0}
                                                end={3}
                                                duration={4}
                                            />
                                        </span>m{" "}
                                        <span className="counter-value" data-target="40">
                                            <CountUp
                                                start={0}
                                                end={40}
                                                duration={4}
                                            />
                                        </span>sec</h4>
                                    <p className="mb-0 text-muted text-truncate "><span className="badge bg-light text-danger mb-0">
                                        <i className="ri-arrow-down-line align-middle"></i> 0.24 %
                                    </span> vs. previous month</p>
                                </div>
                                <div>
                                    <div className="avatar-sm flex-shrink-0">
                                        <span className="avatar-title bg-info-subtle rounded-circle fs-2">
                                            <FeatherIcon
                                                icon="clock"
                                                className="text-info"
                                            />
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>

                <Col md={6}>
                    <Card className="card-animate">
                        <Card.Body>
                            <div className="d-flex justify-content-between">
                                <div>
                                    <p className="fw-medium text-muted mb-0">Bounce Rate</p>
                                    <h4 className="fs-22 mt-4 ff-secondary fw-semibold">
                                        <span className="counter-value" data-target="33.48">
                                            <CountUp
                                                start={0}
                                                end={33.48}
                                                decimals={2}
                                                duration={4}
                                            />
                                        </span>%</h4>
                                    <p className="mb-0 text-muted text-truncate "><span className="badge bg-light text-success mb-0">
                                        <i className="ri-arrow-up-line align-middle"></i> 7.05 %
                                    </span> vs. previous month</p>
                                </div>
                                <div>
                                    <div className="avatar-sm flex-shrink-0">
                                        <span className="avatar-title bg-info-subtle rounded-circle fs-2">
                                            <FeatherIcon
                                                icon="external-link"
                                                className="text-info"
                                            />
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>
        </React.Fragment>
    );
};

export default Widget;

// Svelte/corporate/src/routes/dashboard-analytics/Widget.svelte
<script>
	import { Card, CardBody, Col, Row } from 'sveltestrap';
	import { UsersIcon, ActivityIcon, ClockIcon, ExternalLinkIcon } from 'svelte-feather-icons';
</script>

<Row>
	<Col md={6}>
	<Card class="card-animate">
		<CardBody>
			<div class="d-flex justify-content-between">
				<div>
					<p class="fw-medium text-muted mb-0">Users</p>
					<h4 class="mt-4 fs-22 ff-secondary fw-semibold">
						<span class="counter-value" data-target="28.05">0</span>k
					</h4>
					<p class="mb-0 text-muted text-truncate">
						<span class="badge bg-light text-success mb-0">
							<i class="ri-arrow-up-line align-middle" /> 16.24 %
						</span> vs. previous month
					</p>
				</div>
				<div>
					<div class="avatar-sm flex-shrink-0">
						<span class="avatar-title bg-info-subtle rounded-circle fs-2">
							<UsersIcon class="text-info" size="24" />
						</span>
					</div>
				</div>
			</div>
		</CardBody>
	</Card>
	</Col>

	<Col md={6}>
	<Card class="card-animate">
		<CardBody>
			<div class="d-flex justify-content-between">
				<div>
					<p class="fw-medium text-muted mb-0">Sessions</p>
					<h4 class="mt-4 fs-22 ff-secondary fw-semibold">
						<span class="counter-value" data-target="97.66">0</span>k
					</h4>
					<p class="mb-0 text-muted text-truncate">
						<span class="badge bg-light text-danger mb-0">
							<i class="ri-arrow-down-line align-middle" /> 3.96 %
						</span> vs. previous month
					</p>
				</div>
				<div>
					<div class="avatar-sm flex-shrink-0">
						<span class="avatar-title bg-info-subtle rounded-circle fs-2">
							<ActivityIcon class="text-info" size="24" />
						</span>
					</div>
				</div>
			</div>
		</CardBody>
	</Card>
	</Col>
</Row>

<Row>
	<Col md={6}>
	<Card class="card-animate">
		<CardBody>
			<div class="d-flex justify-content-between">
				<div>
					<p class="fw-medium text-muted mb-0">Avg. Visit Duration</p>
					<h4 class="mt-4 fs-22 ff-secondary fw-semibold">
						<span class="counter-value" data-target="3">0</span>m
						<span class="counter-value" data-target="40">0</span>sec
					</h4>
					<p class="mb-0 text-muted text-truncate">
						<span class="badge bg-light text-danger mb-0">
							<i class="ri-arrow-down-line align-middle" /> 0.24 %
						</span> vs. previous month
					</p>
				</div>
				<div>
					<div class="avatar-sm flex-shrink-0">
						<span class="avatar-title bg-info-subtle rounded-circle fs-2">
							<ClockIcon class="text-info" size="24" />
						</span>
					</div>
				</div>
			</div>
		</CardBody>
	</Card>
	</Col>

	<Col md={6}>
	<Card class="card-animate">
		<CardBody>
			<div class="d-flex justify-content-between">
				<div>
					<p class="fw-medium text-muted mb-0">Bounce Rate</p>
					<h4 class="mt-4 fs-22 ff-secondary fw-semibold">
						<span class="counter-value" data-target="33.48">0</span>%
					</h4>

					<p class="mb-0 text-muted text-truncate">
						<span class="badge bg-light text-success mb-0">
							<i class="ri-arrow-up-line align-middle" /> 7.05 %
						</span> vs. previous month
					</p>
				</div>
				<div>
					<div class="avatar-sm flex-shrink-0">
						<span class="avatar-title bg-info-subtle rounded-circle fs-2">
							<ExternalLinkIcon class="text-info" size="24" />
						</span>
					</div>
				</div>
			</div>
		</CardBody>
	</Card>
	</Col>
</Row>
