// Svelte/minimal/src/routes/dashboard-projects/Chat.svelte
<script>
	import {
		Card,
		CardBody,
		CardHeader,
		Col,
		DropdownItem,
		DropdownMenu,
		DropdownToggle,
		Dropdown
	} from 'sveltestrap';
import avatar2 from '../../assets/images/users/avatar-2.jpg'
import avatar1 from '../../assets/images/users/avatar-1.jpg'
import img1 from '../../assets/images/small/img-1.jpg'
import img2 from '../../assets/images/small/img-2.jpg'
</script>

<Col xxl={4} lg={6}>
	<Card class="card-height-100">
		<CardHeader class="align-items-center d-flex">
			<h4 class="card-title mb-0 flex-grow-1">Chat</h4>
			<div class="flex-shrink-0">
				<Dropdown class="card-header-dropdown" direction="start">
					<DropdownToggle tag="a" class="text-reset p-0" color="" role="button">
						<span class="text-muted"><i class="ri-settings-4-line align-bottom me-1" />Setting
							<i class="mdi mdi-chevron-down ms-1" /></span
						>
					</DropdownToggle>
					<DropdownMenu class="dropdown-menu-end">
						<DropdownItem><i class="ri-user-2-fill align-bottom text-muted me-2" /> View Profile</DropdownItem
						>
						<DropdownItem><i class="ri-inbox-archive-line align-bottom text-muted me-2" /> Archive</DropdownItem
						>
						<DropdownItem><i class="ri-mic-off-line align-bottom text-muted me-2" /> Muted</DropdownItem
						>
						<DropdownItem><i class="ri-delete-bin-5-line align-bottom text-muted me-2" /> Delete</DropdownItem
						>
					</DropdownMenu>
				</Dropdown>
			</div>
		</CardHeader>

		<CardBody class="p-0">
			<div class="chat-conversation p-3" data-simplebar style="height: 400px;">
				<ul class="list-unstyled chat-conversation-list chat-sm" id="users-conversation">
					<li class="chat-list left">
						<div class="conversation-list">
							<div class="chat-avatar">
								<img src={avatar2} alt="" />
							</div>
							<div class="user-chat-content">
								<div class="ctext-wrap">
									<div class="ctext-wrap-content">
										<p class="mb-0 ctext-content">Good morning 😊</p>
									</div>
									<Dropdown class="align-self-start message-box-drop">
										<DropdownToggle class="p-0" tag="a" color="" href="{null}">
											<i class="ri-more-2-fill" />
										</DropdownToggle>
										<DropdownMenu>
											<DropdownItem
												><i class="ri-reply-line me-2 text-muted align-bottom" />Reply</DropdownItem>
											<DropdownItem><i
													class="ri-share-line me-2 text-muted align-bottom"
												/>Forward</DropdownItem>
											<DropdownItem><i
													class="ri-file-copy-line me-2 text-muted align-bottom"
												/>Copy</DropdownItem>
											<DropdownItem><i
													class="ri-bookmark-line me-2 text-muted align-bottom"
												/>Bookmark</DropdownItem>
											<DropdownItem class="delete-item">
                                                <i
													class="ri-delete-bin-5-line me-2 text-muted align-bottom"
												/>Delete</DropdownItem>
										</DropdownMenu>
									</Dropdown>
								</div>
								<div class="conversation-name">
									<small class="text-muted time">09:07 am</small>
									<span class="text-success check-message-icon"><i class="ri-check-double-line align-bottom" /></span>
								</div>
							</div>
						</div>
					</li>

					<li class="chat-list right">
						<div class="conversation-list">
							<div class="user-chat-content">
								<div class="ctext-wrap">
									<div class="ctext-wrap-content">
										<p class="mb-0 ctext-content">
											Good morning, How are you? What about our next meeting?
										</p>
									</div>
									<Dropdown class="align-self-start message-box-drop">
										<DropdownToggle class="p-0" tag="a" color="" href="{null}">
											<i class="ri-more-2-fill" />
										</DropdownToggle>
										<DropdownMenu>
											<DropdownItem
												><i class="ri-reply-line me-2 text-muted align-bottom" />Reply</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-share-line me-2 text-muted align-bottom"
												/>Forward</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-file-copy-line me-2 text-muted align-bottom"
												/>Copy</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-bookmark-line me-2 text-muted align-bottom"
												/>Bookmark</DropdownItem
											>
											<DropdownItem class="delete-item"
												><i
													class="ri-delete-bin-5-line me-2 text-muted align-bottom"
												/>Delete</DropdownItem
											>
										</DropdownMenu>
									</Dropdown>
								</div>
								<div class="conversation-name">
									<small class="text-muted time">09:08 am</small>
									<span class="text-success check-message-icon"
										><i class="ri-check-double-line align-bottom" /></span
									>
								</div>
							</div>
						</div>
					</li>

					<li class="chat-list left">
						<div class="conversation-list">
							<div class="chat-avatar">
								<img src={avatar2} alt="" />
							</div>
							<div class="user-chat-content">
								<div class="ctext-wrap">
									<div class="ctext-wrap-content">
										<p class="mb-0 ctext-content">
											Yeah everything is fine. Our next meeting tomorrow at 10.00 AM
										</p>
									</div>
									<Dropdown class="align-self-start message-box-drop">
										<DropdownToggle class="p-0" tag="a" color="" href="{null}">
											<i class="ri-more-2-fill" />
										</DropdownToggle>
										<DropdownMenu>
											<DropdownItem
												><i class="ri-reply-line me-2 text-muted align-bottom" />Reply</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-share-line me-2 text-muted align-bottom"
												/>Forward</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-file-copy-line me-2 text-muted align-bottom"
												/>Copy</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-bookmark-line me-2 text-muted align-bottom"
												/>Bookmark</DropdownItem
											>
											<DropdownItem class="delete-item"
												><i
													class="ri-delete-bin-5-line me-2 text-muted align-bottom"
												/>Delete</DropdownItem
											>
										</DropdownMenu>
									</Dropdown>
								</div>
								<div class="ctext-wrap">
									<div class="ctext-wrap-content">
										<p class="mb-0 ctext-content">
											Hey, I'm going to meet a friend of mine at the department store. I have to buy
											some presents for my parents 🎁.
										</p>
									</div>
									<Dropdown class="align-self-start message-box-drop">
										<DropdownToggle class="p-0" tag="a" color="" href="{null}">
											<i class="ri-more-2-fill" />
										</DropdownToggle>
										<DropdownMenu>
											<DropdownItem
												><i class="ri-reply-line me-2 text-muted align-bottom" />Reply</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-share-line me-2 text-muted align-bottom"
												/>Forward</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-file-copy-line me-2 text-muted align-bottom"
												/>Copy</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-bookmark-line me-2 text-muted align-bottom"
												/>Bookmark</DropdownItem
											>
											<DropdownItem class="delete-item"
												><i
													class="ri-delete-bin-5-line me-2 text-muted align-bottom"
												/>Delete</DropdownItem
											>
										</DropdownMenu>
									</Dropdown>
								</div>
								<div class="conversation-name">
									<small class="text-muted time">09:10 am</small>
									<span class="text-success check-message-icon"
										><i class="ri-check-double-line align-bottom" /></span
									>
								</div>
							</div>
						</div>
					</li>

					<li class="chat-list right">
						<div class="conversation-list">
							<div class="user-chat-content">
								<div class="ctext-wrap">
									<div class="ctext-wrap-content">
										<p class="mb-0 ctext-content">Wow that's great</p>
									</div>
									<Dropdown class="align-self-start message-box-drop">
										<DropdownToggle class="p-0" tag="a" color="" href="{null}">
											<i class="ri-more-2-fill" />
										</DropdownToggle>
										<DropdownMenu>
											<DropdownItem
												><i class="ri-reply-line me-2 text-muted align-bottom" />Reply</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-share-line me-2 text-muted align-bottom"
												/>Forward</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-file-copy-line me-2 text-muted align-bottom"
												/>Copy</DropdownItem
											>
											<DropdownItem
												><i
													class="ri-bookmark-line me-2 text-muted align-bottom"
												/>Bookmark</DropdownItem
											>
											<DropdownItem class="delete-item"
												><i
													class="ri-delete-bin-5-line me-2 text-muted align-bottom"
												/>Delete</DropdownItem
											>
										</DropdownMenu>
									</Dropdown>
								</div>
								<div class="conversation-name">
									<small class="text-muted time">09:12 am</small>
									<span class="text-success check-message-icon"
										><i class="ri-check-double-line align-bottom" /></span
									>
								</div>
							</div>
						</div>
					</li>

					<li class="chat-list left">
						<div class="conversation-list">
							<div class="chat-avatar">
								<img src={avatar2} alt="" />
							</div>
							<div class="user-chat-content">
								<div class="ctext-wrap">
									<div class="message-img mb-0">
										<div class="message-img-list">
											<div>
												<a
													class="popup-img d-inline-block"
													href={img1}
												>
													<img
														src={img1}
														alt=""
														class="rounded border"
													/>
												</a>
											</div>
											<div class="message-img-link">
												<ul class="list-inline mb-0">
													<Dropdown class="list-inline-item">
														<DropdownToggle
															tag="a"
															class="dropdown-toggle p-0"
															color=""
															href="{null}"
															role="button"
														>
															<i class="ri-more-fill" />
														</DropdownToggle>
														<DropdownMenu>
															<DropdownItem href={avatar1} download=""
																><i
																	class="ri-download-2-line me-2 text-muted align-bottom"
																/>Download</DropdownItem
															>
															<DropdownItem href="{null}"
																><i
																	class="ri-reply-line me-2 text-muted align-bottom"
																/>Reply</DropdownItem
															>
															<DropdownItem href="{null}"
																><i
																	class="ri-share-line me-2 text-muted align-bottom"
																/>Forward</DropdownItem
															>
															<DropdownItem href="{null}"
																><i
																	class="ri-bookmark-line me-2 text-muted align-bottom"
																/>Bookmark</DropdownItem
															>
															<DropdownItem class="delete-item" href="{null}"
																><i
																	class="ri-delete-bin-5-line me-2 text-muted align-bottom"
																/>Delete</DropdownItem
															>
														</DropdownMenu>
													</Dropdown>
												</ul>
											</div>
										</div>

										<div class="message-img-list">
											<div>
												<a
													class="popup-img d-inline-block"
													href="{null}"
												>
													<img
														src={img2}
														alt=""
														class="rounded border"
													/>
												</a>
											</div>
											<div class="message-img-link">
												<ul class="list-inline mb-0">
													<Dropdown class="list-inline-item">
														<DropdownToggle
															tag="a"
															class="dropdown-toggle p-0"
															color=""
															href="{null}"
															role="button"
														>
															<i class="ri-more-fill" />
														</DropdownToggle>
														<DropdownMenu>
															<DropdownItem href={avatar1} download=""
																><i
																	class="ri-download-2-line me-2 text-muted align-bottom"
																/>Download</DropdownItem
															>
															<DropdownItem href="{null}"
																><i
																	class="ri-reply-line me-2 text-muted align-bottom"
																/>Reply</DropdownItem
															>
															<DropdownItem href="{null}"
																><i
																	class="ri-share-line me-2 text-muted align-bottom"
																/>Forward</DropdownItem
															>
															<DropdownItem href="{null}"
																><i
																	class="ri-bookmark-line me-2 text-muted align-bottom"
																/>Bookmark</DropdownItem
															>
															<DropdownItem class="delete-item" href="{null}"
																><i
																	class="ri-delete-bin-5-line me-2 text-muted align-bottom"
																/>Delete</DropdownItem
															>
														</DropdownMenu>
													</Dropdown>
												</ul>
											</div>
										</div>
									</div>
								</div>

								<div class="conversation-name">
									<small class="text-muted time">09:30 am</small>
									<span class="text-success check-message-icon"
										><i class="ri-check-double-line align-bottom" /></span
									>
								</div>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="border-top border-top-dashed">
				<div class="row g-2 mx-3 mt-2 mb-3">
					<div class="col">
						<div class="position-relative">
							<input
								type="text"
								class="form-control border-light bg-light"
								placeholder="Enter Message..."
							/>
						</div>
					</div>
					<div class="col-auto">
						<button type="submit" class="btn btn-primary"><span class="d-none d-sm-inline-block me-2">Send</span>
							<i class="mdi mdi-send float-end" /></button
						>
					</div>
				</div>
			</div>
		</CardBody>
	</Card>
</Col>

// React+TS/Corporate/src/pages/DashboardProject/Chat.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { Card, CardBody, CardHeader, Col, DropdownItem, DropdownMenu, DropdownToggle, UncontrolledDropdown } from 'reactstrap';

import { dashboardChat } from '../../common/data';

//Import Scrollbar
import PerfectScrollbar from "react-perfect-scrollbar";
import "react-perfect-scrollbar/dist/css/styles.css";

const Chat = () => {
    const [text, setText] = useState<any>("");
    const [messages, setMessages] = useState<any>([...dashboardChat]);
    const [messageBox, setMessageBox] = useState<any>(null);

    const scrollToBottom = useCallback(() => {
        if (messageBox) {
            messageBox.scrollTop = messageBox.scrollHeight + 1000;
        }
    }, [messageBox]);

    useEffect(() => {
        if ((messages || []).length > 1) {
            scrollToBottom();
        }
    }, [messages, scrollToBottom]);


    const onSendMessage = () => {
        var modifiedMessages = [...messages];
        const lastItem = modifiedMessages.length
            ? modifiedMessages[modifiedMessages.length - 1]
            : { id: 1 };
        const today = new Date();
        const hour = today.getHours();
        const minute = today.getMinutes();
        const senderObj = {
            id: lastItem["id"] + 1,
            message: text,
            time: `${hour}.${minute}`,
            isLeft: false,
        };
        modifiedMessages.push({ ...senderObj });
        setMessages(modifiedMessages);
        setText("");
    };
    return (
        <React.Fragment>
            <Col xxl={4} lg={6}>
                <Card className="card-height-100">
                    <CardHeader className="align-items-center d-flex">
                        <h4 className="card-title mb-0 flex-grow-1">Chat</h4>
                        <div className="flex-shrink-0">
                            <UncontrolledDropdown className="card-header-dropdown">
                                <DropdownToggle tag="a" className="text-reset" role="button">
                                    <span className="text-muted"><i className="ri-settings-4-line align-middle me-1"></i>Setting <i className="mdi mdi-chevron-down ms-1"></i></span>
                                </DropdownToggle>
                                <DropdownMenu className="dropdown-menu-end" end>
                                    <DropdownItem><i className="ri-user-2-fill align-bottom text-muted me-2"></i> View Profile</DropdownItem>
                                    <DropdownItem><i className="ri-inbox-archive-line align-bottom text-muted me-2"></i> Archive</DropdownItem>
                                    <DropdownItem><i className="ri-mic-off-line align-bottom text-muted me-2"></i> Muted</DropdownItem>
                                    <DropdownItem><i className="ri-delete-bin-5-line align-bottom text-muted me-2"></i> Delete</DropdownItem>
                                </DropdownMenu>
                            </UncontrolledDropdown>
                        </div>
                    </CardHeader>

                    <CardBody className="p-0">
                        <div id="users-chat">
                        <PerfectScrollbar className="chat-conversation p-3" id="chat-conversation"
                                style={{ marginBottom: "1rem", maxHeight: "400px" }}
                                containerRef={ref => setMessageBox(ref)}
                            >
                                <ul className="list-unstyled chat-conversation-list chat-sm" id="users-conversation">
                                    {(messages || []).map((item :any, key :any) => (
                                        <li className={item.isLeft ? "chat-list left" : "chat-list right"} key={key}>
                                            <div className="conversation-list">
                                                {item.img ? <div className="chat-avatar">
                                                    <img src={item.img} alt="" />
                                                </div> : null}
                                                <div className="user-chat-content">
                                                    <div className="ctext-wrap">
                                                        <React.Fragment>
                                                            <div className="ctext-wrap-content">
                                                                <p className="mb-0 ctext-content">{item.message}</p>
                                                            </div>
                                                            <UncontrolledDropdown className="align-self-start message-box-drop">
                                                                <DropdownToggle tag="a" role="button">
                                                                    <i className="ri-more-2-fill"></i>
                                                                </DropdownToggle>
                                                                <DropdownMenu>
                                                                    <DropdownItem><i className="ri-reply-line me-2 text-muted align-bottom"></i>Reply</DropdownItem>
                                                                    <DropdownItem><i className="ri-share-line me-2 text-muted align-bottom"></i>Forward</DropdownItem>
                                                                    <DropdownItem><i className="ri-file-copy-line me-2 text-muted align-bottom"></i>Copy</DropdownItem>
                                                                    <DropdownItem><i className="ri-bookmark-line me-2 text-muted align-bottom"></i>Bookmark</DropdownItem>
                                                                    <DropdownItem className="delete-item"><i className="ri-delete-bin-5-line me-2 text-muted align-bottom"></i>Delete</DropdownItem>
                                                                </DropdownMenu>
                                                            </UncontrolledDropdown>
                                                        </React.Fragment>
                                                    </div>
                                                    <div className="conversation-name"><small className="text-muted time">{item.time}</small> <span className="text-success check-message-icon"><i className="ri-check-double-line align-bottom"></i></span></div>
                                                </div>
                                            </div>
                                        </li>))}
                                </ul>
                            </PerfectScrollbar>
                        </div>
                        <div className="border-top border-top-dashed">
                            <div className="row g-2 mx-3 mt-2 mb-3">
                                <div className="col">
                                    <div className="position-relative">
                                        <input type="text" className="form-control border-light bg-light" placeholder="Enter Message..." 
                                        value={text} onChange={e => setText(e.target.value)}/>
                                    </div>
                                </div>
                                <div className="col-auto">
                                    <button type="submit" className="btn btn-primary"  onClick={() => onSendMessage()}><span className="d-none d-sm-inline-block me-2">Send</span> <i className="mdi mdi-send float-end"></i></button>
                                </div>
                            </div>
                        </div>
                    </CardBody>
                </Card>
            </Col>
        </React.Fragment>
    );
};

export default Chat;
