// Svelte/corporate/src/routes/dashboard/RecentOrders.svelte
<script>
	import { Card, CardBody, CardHeader, Col } from 'sveltestrap';
	import data from '../../common/data/dashboardEcommerce';
</script>

<Col xl={8}>
<Card>
	<CardHeader class="align-items-center d-flex">
		<h4 class="card-title mb-0 flex-grow-1">Recent Orders</h4>
		<div class="flex-shrink-0">
			<button type="button" class="btn btn-soft-secondary btn-sm">
				<i class="ri-file-list-3-line align-middle" /> Generate Report
			</button>
		</div>
	</CardHeader>

	<CardBody>
		<div class="table-responsive table-card">
			<table class="table table-borderless table-centered align-middle table-nowrap mb-0">
				<thead class="text-muted table-light">
					<tr>
						<th scope="col">Order ID</th>
						<th scope="col">Customer</th>
						<th scope="col">Product</th>
						<th scope="col">Amount</th>
						<th scope="col">Vendor</th>
						<th scope="col">Status</th>
						<th scope="col">Rating</th>
					</tr>
				</thead>
				<tbody>
					{#each data.recentOrders as item}
					<tr>
						<td>
							<a href="/ecommerce/apps-ecommerce-order-details"
								class="fw-medium link-primary">{item.orderId}</a>
						</td>
						<td>
							<div class="d-flex align-items-center">
								<div class="flex-shrink-0 me-2">
									<img src={item.img} alt="" class="avatar-xs rounded-circle" />
								</div>
								<div class="flex-grow-1">{item.name}</div>
							</div>
						</td>
						<td>{item.product}</td>
						<td>
							<span class="text-success">${item.amount}</span>
						</td>
						<td>{item.vendor}</td>
						<td>
							<span class={'badge bg-' + item.statusClass}>{item.status}</span>
						</td>
						<td>
							<h5 class="fs-14 fw-medium mb-0">
								{item.rating}<span class="text-muted fs-11 ms-1">({item.votes} votes)</span>
							</h5>
						</td>
					</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</CardBody>
</Card>
</Col>

// React+Inertia/Corporate/resources/js/Pages/DashboardEcommerce/RecentOrders.tsx
import React from 'react';
import { Card, Col } from 'react-bootstrap';
import { recentOrders } from '../../common/data';
import { Link } from '@inertiajs/react';

const RecentOrders = () => {
    return (
        <React.Fragment>
            <Col xl={8}>
                <Card>
                    <Card.Header className="align-items-center d-flex">
                        <h4 className="card-title mb-0 flex-grow-1">Recent Orders</h4>
                        <div className="flex-shrink-0">
                            <button type="button" className="btn btn-soft-secondary btn-sm">
                                <i className="ri-file-list-3-line align-middle"></i> Generate Report
                            </button>
                        </div>
                    </Card.Header>

                    <Card.Body>
                        <div className="table-responsive table-card">
                            <table className="table table-borderless table-centered align-middle table-nowrap mb-0">
                                <thead className="text-muted table-light">
                                    <tr>
                                        <th scope="col">Order ID</th>
                                        <th scope="col">Customer</th>
                                        <th scope="col">Product</th>
                                        <th scope="col">Amount</th>
                                        <th scope="col">Vendor</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Rating</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {(recentOrders || []).map((item, key) => (<tr key={key}>
                                        <td>
                                            <Link href="/apps-ecommerce-order-details" className="fw-medium text-reset">{item.orderId}</Link>
                                        </td>
                                        <td>
                                            <div className="d-flex align-items-center">
                                                <div className="flex-shrink-0 me-2">
                                                    <img src={item.img} alt="" className="avatar-xs rounded-circle" />
                                                </div>
                                                <div className="flex-grow-1">{item.name}</div>
                                            </div>
                                        </td>
                                        <td>{item.product}</td>
                                        <td>
                                            <span className="text-primary">${item.amount}.00</span>
                                        </td>
                                        <td>{item.vendor}</td>
                                        <td>
                                            <span className={"badge bg-" + item.statusClass+"-subtle text-"+ item.statusClass}>{item.status}</span>
                                        </td>
                                        <td>
                                            <h5 className="fs-14 fw-medium mb-0">{item.rating}<span className="text-muted fs-11 ms-1">({item.votes} votes)</span></h5>
                                        </td>
                                    </tr>))}
                                </tbody>
                            </table>
                        </div>
                    </Card.Body>
                </Card>
            </Col>
        </React.Fragment>
    );
};

export default RecentOrders;
