// React+Inertia/Interactive/resources/js/Layouts/Header.tsx
import { Link } from "@inertiajs/react";
import React, { useState } from "react";

//import images
import logoSm from "../../images/logo-sm.png";
import logoDark from "../../images/logo-dark.png";
import logoLight from "../../images/logo-light.png";
import { useDispatch, useSelector } from "react-redux";
import { createSelector } from "@reduxjs/toolkit";
import { Dropdown, Form } from "react-bootstrap";
import { changeSidebarVisibility } from "../slices/thunk";
import SearchOption from "../Components/Common/SearchOption";
import LanguageDropdown from "../Components/Common/LanguageDropdown";
import WebAppsDropdown from "../Components/Common/WebAppsDropdown";
import MyCartDropdown from "../Components/Common/MyCartDropdown";
import FullScreenDropdown from "../Components/Common/FullScreenDropdown";
import ProfileDropdown from "../Components/Common/ProfileDropdown";
import LightDark from "../Components/Common/LightDark";
import NotificationDropdown from "../Components/Common/NotificationDropdown";

const Header = ({ onChangeLayoutMode, layoutModeType, headerClass }: any) => {
    const dispatch : any = useDispatch();


    const selectDashboardData = createSelector(
        (state:any) => state.Layout,
        (sidebarVisibilitytype:any) => sidebarVisibilitytype.sidebarVisibilitytype
      );
    // Inside your component
    const sidebarVisibilitytype = useSelector(selectDashboardData);


    const [search, setSearch] = useState<boolean>(false);
    const toogleSearch = () => {
        setSearch(!search);
    };

    const toogleMenuBtn = () => {
        var windowSize = document.documentElement.clientWidth;
        const humberIcon = document.querySelector(".hamburger-icon") as HTMLElement;
        dispatch(changeSidebarVisibility("show"));

        if (windowSize > 767)
            humberIcon.classList.toggle('open');

        //For collapse horizontal menu
        if (document.documentElement.getAttribute('data-layout') === "horizontal") {
            document.body.classList.contains("menu") ? document.body.classList.remove("menu") : document.body.classList.add("menu");
        }

    //For collapse vertical and semibox menu
    if (sidebarVisibilitytype === "show" && (document.documentElement.getAttribute('data-layout') === "vertical" || document.documentElement.getAttribute('data-layout') === "semibox")) {
        if (windowSize < 1025 && windowSize > 767) {
            document.body.classList.remove('vertical-sidebar-enable');
            (document.documentElement.getAttribute('data-sidebar-size') === 'sm') ? document.documentElement.setAttribute('data-sidebar-size', '') : document.documentElement.setAttribute('data-sidebar-size', 'sm');
        } else if (windowSize > 1025) {
            document.body.classList.remove('vertical-sidebar-enable');
            (document.documentElement.getAttribute('data-sidebar-size') === 'lg') ? document.documentElement.setAttribute('data-sidebar-size', 'sm') : document.documentElement.setAttribute('data-sidebar-size', 'lg');
        } else if (windowSize <= 767) {
            document.body.classList.add('vertical-sidebar-enable');
            document.documentElement.setAttribute('data-sidebar-size', 'lg');
        }
    }


    //Two column menu
        if (document.documentElement.getAttribute('data-layout') === "twocolumn") {
            document.body.classList.contains('twocolumn-panel') ? document.body.classList.remove('twocolumn-panel') : document.body.classList.add('twocolumn-panel');
        }
    };
    return (
        <React.Fragment>
            <header id="page-topbar" className={headerClass}>
                <div className="layout-width">
                    <div className="navbar-header">
                        <div className="d-flex">

                            <div className="navbar-brand-box horizontal-logo">
                                <Link href="/" className="logo logo-dark">
                                    <span className="logo-sm">
                                        <img src={logoSm} alt="" height="22" />
                                    </span>
                                    <span className="logo-lg">
                                        <img src={logoDark} alt="" height="17" />
                                    </span>
                                </Link>

                                <Link href="/" className="logo logo-light">
                                    <span className="logo-sm">
                                        <img src={logoSm} alt="" height="22" />
                                    </span>
                                    <span className="logo-lg">
                                        <img src={logoLight} alt="" height="17" />
                                    </span>
                                </Link>
                            </div>

                            <button
                                onClick={toogleMenuBtn}
                                type="button"
                                className="btn btn-sm px-3 fs-16 header-item vertical-menu-btn topnav-hamburger"
                                id="topnav-hamburger-icon">
                                <span className="hamburger-icon">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </span>
                            </button>


                            <SearchOption />
                        </div>

                        <div className="d-flex align-items-center">

                            <Dropdown show={search} onClick={toogleSearch} className="d-md-none topbar-head-dropdown header-item">
                                <Dropdown.Toggle type="button" as="button" className="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle">
                                    <i className="bx bx-search fs-22"></i>
                                </Dropdown.Toggle>
                                <Dropdown.Menu className="dropdown-menu-lg dropdown-menu-end p-0">
                                    <Form className="p-3">
                                        <div className="form-group m-0">
                                            <div className="input-group">
                                                <input type="text" className="form-control" placeholder="Search ..."
                                                    aria-label="Recipient's username" />
                                                <button className="btn btn-primary" type="submit"><i
                                                    className="mdi mdi-magnify"></i></button>
                                            </div>
                                        </div>
                                    </Form>
                                </Dropdown.Menu>
                            </Dropdown>

                            {/* LanguageDropdown */}
                            <LanguageDropdown />

                            {/* WebAppsDropdown */}
                            <WebAppsDropdown />

                            {/* MyCartDropdwon */}
                            <MyCartDropdown />

                            {/* FullScreenDropdown */}
                            <FullScreenDropdown />

                            {/* Dark/Light Mode set */}
                            <LightDark
                                layoutMode={layoutModeType}
                                onChangeLayoutMode={onChangeLayoutMode}
                            />

                            {/* NotificationDropdown */}
                            <NotificationDropdown />

                            {/* ProfileDropdown */}
                            <ProfileDropdown />
                        </div>
                    </div>
                </div>
            </header>
        </React.Fragment>
    )
}
export default Header;

// Svelte/corporate/src/Layouts/Header.svelte
<script>
	import { Form, Input, Dropdown, DropdownMenu, Button } from "sveltestrap";
	import { browser } from "$app/environment";

	import SearchOption from "./../Components/Common/SearchOption.svelte";
	import LanguageDropdown from "./../Components/Common/LanguageDropdown.svelte";
	import WebAppsDropdown from "./../Components/Common/WebAppsDropdown.svelte";
	import MyCartDropdown from "./../Components/Common/MyCartDropdown.svelte";
	import FullScreenDropdown from "./../Components/Common/FullScreenDropdown.svelte";
	import NotificationDropdown from "./../Components/Common/NotificationDropdown.svelte";
	import ProfileDropdown from "./../Components/Common/ProfileDropdown.svelte";
	import LightDark from "./../Components/Common/LightDark.svelte";

	import logosm from '../assets/images/logo-sm.png'
	import logodark from '../assets/images/logo-dark.png' 
	import logolight from '../assets/images/logo-light.png'
	
	export let headerClass;
	function toogleMenuBtn() {
		if (browser) {
			var windowSize = document.documentElement.clientWidth;

			if (windowSize > 767)
				document.querySelector(".hamburger-icon").classList.toggle('open');

			//For collapse horizontal menu
			if (document.documentElement.getAttribute('data-layout') === "horizontal") {
				document.body.classList.contains("menu") ? document.body.classList.remove("menu") : document.body.classList.add("menu");
			}

			//For collapse vertical menu
			if (document.documentElement.getAttribute('data-layout') === "vertical") {
				if (windowSize < 1025 && windowSize > 767) {
					document.body.classList.remove('vertical-sidebar-enable');
					(document.documentElement.getAttribute('data-sidebar-size') === 'sm') ? document.documentElement.setAttribute('data-sidebar-size', '') : document.documentElement.setAttribute('data-sidebar-size', 'sm');
				} else if (windowSize > 1025) {
					document.body.classList.remove('vertical-sidebar-enable');
					(document.documentElement.getAttribute('data-sidebar-size') === 'lg') ? document.documentElement.setAttribute('data-sidebar-size', 'sm') : document.documentElement.setAttribute('data-sidebar-size', 'lg');
				} else if (windowSize <= 767) {
					document.body.classList.add('vertical-sidebar-enable');
					document.documentElement.setAttribute('data-sidebar-size', 'lg');
				}
			}

			//Two column menu
			if (document.documentElement.getAttribute('data-layout') === "twocolumn") {
				document.body.classList.contains('twocolumn-panel') ? document.body.classList.remove('twocolumn-panel') : document.body.classList.add('twocolumn-panel');
			}
		}
	}
</script>

<header id="page-topbar" class={headerClass}>
	<div class="layout-width">
		<div class="navbar-header">
			<div class="d-flex">
				<!-- LOGO -->
				<div class="navbar-brand-box horizontal-logo">
					<a href="dashboard" class="logo logo-dark">
						<span class="logo-sm">
							<img
								src={logosm}
								alt=""
								height="22"
							/>
						</span>
						<span class="logo-lg">
							<img
								src={logodark}
								alt=""
								height="17"
							/>
						</span>
					</a>

					<a href="dashboard" class="logo logo-light">
						<span class="logo-sm">
							<img
								src={logosm}
								alt=""
								height="22"
							/>
						</span>
						<span class="logo-lg">
							<img
								src={logolight}
								alt=""
								height="17"
							/>
						</span>
					</a>
				</div>

				<button
					type="button"
					class="btn btn-sm px-3 fs-16 header-item vertical-menu-btn topnav-hamburger"
					id="topnav-hamburger-icon"
					on:click={toogleMenuBtn}
				>
					<span class="hamburger-icon">
						<span />
						<span />
						<span />
					</span>
				</button>

				<SearchOption />
			</div>

			<div class="d-flex align-items-center">
				<Dropdown class="d-md-none topbar-head-dropdown header-item">
					<button
						type="button"
						class="btn btn-icon btn-topbar btn-ghost-secondary rounded-circle"
						id="page-header-search-dropdown">
						<i class="bx bx-search fs-22" />
					</button>
					<DropdownMenu
						class="dropdown-menu-lg dropdown-menu-end p-0">
						<Form class="p-3">
							<div class="form-group m-0">
								<div class="input-group">
									<Input
										type="text"
										class="form-control"
										placeholder="Search ..."
									/>
									<Button color="primary" type="submit"
										><i class="mdi mdi-magnify" /></Button
									>
								</div>
							</div>
						</Form>
					</DropdownMenu>
				</Dropdown>

				<LanguageDropdown />

				<WebAppsDropdown />

				<MyCartDropdown />

				<FullScreenDropdown />

				<LightDark />

				<NotificationDropdown />

				<ProfileDropdown />
			</div>
		</div>
	</div>
</header>

<div class="vertical-overlay" />
