// React+Inertia/Modern/resources/js/Pages/SupportTickets/TicketsDetails/Section.tsx
import React from 'react';
import { Card, Col, Row, Dropdown } from 'react-bootstrap';
import img from "../../../../images/companies/img-4.png";


const Section = () => {
    return (
        <React.Fragment>
            <Col lg={12}>
                <Card className="mt-n4 mx-n4 mb-n5">
                    <div className="bg-warning-subtle">
                        <Card.Body className="pb-4 mb-5">
                            <Row>
                                <div className="col-md">
                                    <Row className="align-items-center">
                                        <div className="col-md-auto">
                                            <div className="avatar-md mb-md-0 mb-4">
                                                <div className="avatar-title bg-white rounded-circle">
                                                    <img src={img} alt="" className="avatar-sm" />
                                                </div>
                                            </div>
                                        </div>
                                        <div className="col-md">
                                            <h4 className="fw-semibold" id="ticket-title">#VLZ135 - Create an Excellent UI for a Dashboard</h4>
                                            <div className="hstack gap-3 flex-wrap">
                                                <div className="text-muted"><i className="ri-building-line align-bottom me-1"></i> <span id="ticket-client">Themesbrand</span></div>
                                                <div className="vr"></div>
                                                <div className="text-muted">Create Date : <span className="fw-medium" id="create-date">20 Dec, 2021</span></div>
                                                <div className="vr"></div>
                                                <div className="text-muted">Due Date : <span className="fw-medium" id="due-date">29 Dec, 2021</span></div>
                                                <div className="vr"></div>
                                                <div className="badge rounded-pill bg-info fs-12" id="ticket-status">New</div>
                                                <div className="badge rounded-pill bg-danger fs-12" id="ticket-priority">High</div>
                                            </div>
                                        </div>
                                    </Row>
                                </div>
                                <div className="col-md-auto mt-md-0 mt-4">
                                    <div className="hstack gap-1 flex-wrap">
                                        <button type="button" className="btn avatar-xs mt-n1 p-0 favourite-btn active">
                                            <span className="avatar-title bg-transparent fs-15">
                                                <i className="ri-star-fill"></i>
                                            </span>
                                        </button>
                                        <Dropdown >
                                            <Dropdown.Toggle as="button" type="button" className="btn py-0 fs-16 text-body arrow-none">
                                                <i className="ri-share-line"></i>
                                            </Dropdown.Toggle>

                                            <Dropdown.Menu>
                                                <li><Dropdown.Item><i className="ri-eye-fill align-bottom me-2 text-muted"></i> View</Dropdown.Item></li>
                                                <li><Dropdown.Item><i className="ri-share-forward-fill align-bottom me-2 text-muted"></i> Share with</Dropdown.Item></li>
                                                <li><Dropdown.Item><i className="ri-delete-bin-fill align-bottom me-2 text-muted"></i> Delete</Dropdown.Item></li>
                                            </Dropdown.Menu>
                                        </Dropdown>
                                        <button type="button" className="btn py-0 fs-16 text-body">
                                            <i className="ri-flag-line"></i>
                                        </button>
                                    </div>
                                </div>
                            </Row>
                        </Card.Body>
                    </div>
                </Card>
            </Col>
        </React.Fragment>
    );
};

export default Section;

// Svelte/saas/src/routes/support/ticketsdetails/Section.svelte
<script>
	import {
		Card,
		CardBody,
		Col,
		DropdownItem,
		DropdownMenu,
		DropdownToggle,
		Row,
		Dropdown,
	} from "sveltestrap";
	import img4 from "../../../assets/images/companies/img-4.png";
</script>

<Col lg={12}>
	<Card class="mt-n4 mx-n4 mb-n5">
		<div class="bg-warning-subtle">
			<CardBody class="pb-4 mb-5">
				<Row>
					<div class="col-md">
						<Row class="align-items-center">
							<div class="col-md-auto">
								<div class="avatar-md mb-md-0 mb-4">
									<div
										class="avatar-title bg-white rounded-circle"
									>
										<img
											src={img4}
											alt=""
											class="avatar-sm"
										/>
									</div>
								</div>
							</div>
							<!--end col-->
							<div class="col-md">
								<h4 class="fw-semibold" id="ticket-title">
									#VLZ135 - Create an Excellent UI for a
									Dashboard
								</h4>
								<div class="hstack gap-3 flex-wrap">
									<div class="text-muted">
										<i
											class="ri-building-line align-bottom me-1"
										/><span id="ticket-client"
											>Themesbrand</span
										>
									</div>
									<div class="vr" />
									<div class="text-muted">
										Create Date : <span
											class="fw-medium"
											id="create-date">20 Dec, 2021</span
										>
									</div>
									<div class="vr" />
									<div class="text-muted">
										Due Date : <span
											class="fw-medium"
											id="due-date">29 Dec, 2021</span
										>
									</div>
									<div class="vr" />
									<div
										class="badge rounded-pill bg-info fs-12"
										id="ticket-status"
									>
										New
									</div>
									<div
										class="badge rounded-pill bg-danger fs-12"
										id="ticket-priority"
									>
										High
									</div>
								</div>
							</div>
							<!--end col-->
						</Row>
						<!--end row-->
					</div>
					<!--end col-->
					<div class="col-md-auto mt-md-0 mt-4">
						<div class="hstack gap-1 flex-wrap">
							<button
								type="button"
								class="btn avatar-xs mt-n1 p-0 favourite-btn active"
							>
								<span class="avatar-title bg-transparent fs-15">
									<i class="ri-star-fill" />
								</span>
							</button>
							<Dropdown>
								<DropdownToggle
									tag="button"
									color=""
									type="button"
									class="btn py-0 fs-16 text-body"
								>
									<i class="ri-share-line" />
								</DropdownToggle>

								<DropdownMenu>
									<li>
										<DropdownItem
											><i
												class="ri-eye-fill align-bottom me-2 text-muted"
											/> View</DropdownItem
										>
									</li>
									<li>
										<DropdownItem
											><i
												class="ri-share-forward-fill align-bottom me-2 text-muted"
											/> Share with</DropdownItem
										>
									</li>
									<li>
										<DropdownItem
											><i
												class="ri-delete-bin-fill align-bottom me-2 text-muted"
											/> Delete</DropdownItem
										>
									</li>
								</DropdownMenu>
							</Dropdown>
							<button
								type="button"
								class="btn py-0 fs-16 text-body"
							>
								<i class="ri-flag-line" />
							</button>
						</div>
					</div>
					<!--end col-->
				</Row>
				<!--end row-->
			</CardBody>
			<!-- end card body -->
		</div>
	</Card>
	<!-- end card -->
</Col>
<!-- end col -->
