// React+Inertia/Modern/resources/js/Pages/SupportTickets/ListView/index.tsx
import React from 'react';
import { Container, Row } from 'react-bootstrap';
import BreadCrumb from '../../../Components/Common/BreadCrumb';
import Widgets from './Widgets';
import TicketsData from './TicketsData';
import { Head } from '@inertiajs/react';
import Layout from '../../../Layouts';


const ListView = () => {
    return (
        <React.Fragment>
            <Head title="Tickets List | Velzon - React Admin & Dashboard Template" />
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="Tickets List" pageTitle="Tickets" />
                    <Row>
                        <Widgets />
                    </Row>
                    <TicketsData />
                </Container>
            </div>
        </React.Fragment>
    );
};
ListView.layout = (page: any) => <Layout children={page} />
export default ListView;

// Svelte/modern/src/routes/support/listview/+page.svelte
<svelte:head>
  <title>Tickets List | Velzon - Svelte Admin & Dashboard Template</title>
</svelte:head>
<script>
	import BreadCrumb from '../../../Components/Common/BreadCrumb.svelte';
	import Counter from '../../../Components/Common/CounterPage.svelte';
	import tickitData from '../../../common/data/supportTickets';
	import Widgets from './Widgets.svelte';
	import TicketsData from './TicketsData.svelte';

	import { Row, Container } from 'sveltestrap';
</script>

<Counter />

<div class="page-content">
	<Container fluid>
		<BreadCrumb title="Invoice List" pageTitle="Invoices" />

		<Row>
			<Widgets ticketsWidgets={tickitData.ticketsWidgets} />
		</Row>

		<TicketsData />
	</Container>
</div>
