// Angular/corporate/src/app/pages/nft-marketplace/collections/collections.component.ts
import { Component, QueryList, ViewChildren } from '@angular/core';
import {DecimalPipe} from '@angular/common';
import {Observable} from 'rxjs';

import { collectionModel } from './collection.model';
import { PaginationService } from 'src/app/core/services/pagination.service';
import { collectionData } from 'src/app/core/data';

@Component({
  selector: 'app-collections',
  templateUrl: './collections.component.html',
  styleUrls: ['./collections.component.scss']
})

/**
 * Collections Component
 */
export class CollectionsComponent {

  // bread crumb items
  breadCrumbItems!: Array<{}>;
  collectionData: collectionModel[];
  searchTerm: any;
  searchResults: any;
  allcollectionData: any[];
  

  constructor(public service: PaginationService) {
    this.collectionData = collectionData;
    this.allcollectionData = collectionData;
  }

  ngOnInit(): void {
     /**
    * BreadCrumb
    */
      this.breadCrumbItems = [
        { label: 'NFT Marketplace' },
        { label: 'Collections', active: true }
      ];
  }

    // Pagination
    changePage() {
      this.collectionData = this.service.changePage(this.allcollectionData)
    }

    // Search Data
    performSearch(): void {
      this.searchResults = collectionData.filter((item: any) => {
        return (
          item.title.toLowerCase().includes(this.searchTerm.toLowerCase())
        );
      });
      this.collectionData = this.service.changePage(this.searchResults)
    }

}

<!-- Start Breadcrumbs -->
<app-breadcrumbs title="Collections" [breadcrumbItems]="breadCrumbItems"></app-breadcrumbs>
<!-- End Breadcrumbs -->

<div class="row g-4 mb-3 align-items-center justify-content-between">
    <div class="col-sm-auto">
        <div>
            <h5 class="mb-0">Top Collections</h5>
        </div>
    </div>
    <!--end col-->
    <div class="col-sm-auto">
        <div class="d-flex justify-content-sm-end gap-2">
            <div class="search-box ms-2">
                <input type="text" class="form-control" placeholder="Search..." [(ngModel)]="searchTerm" (ngModelChange)="performSearch()">
                <i class="ri-search-line search-icon"></i>
            </div>

            <select class="form-control w-md" data-choices data-choices-search-false>
                <option value="All">All</option>
                <option value="Today" selected>Today</option>
                <option value="Yesterday">Yesterday</option>
                <option value="Last 7 Days">Last 7 Days</option>
                <option value="Last 30 Days">Last 30 Days</option>
                <option value="This Month">This Month</option>
                <option value="Last Year">Last Year</option>
            </select>
        </div>
    </div>
    <!--end col-->
</div>
<!--end row-->

<div class="row">
    @for(data of collectionData;track $index){
    <div class="col-xl-3 col-md-4 col-sm-6">
        <div class="card">
            <div class="card-body">
                <div class="row g-1 mb-3">
                    @for(user of data.images;track $index){
                    <div class="col-6" >
                        @for(user of user.image;track $index){
                        <img src="{{user.img}}" alt="" class="img-fluid rounded  mt-1">
                        }
                    </div>
                }
                    <!--end col-->
                </div>
                <!--end row-->
                <a href="javascript:void(0);" class="float-end"> View All <i
                        class="ri-arrow-right-line align-bottom"></i></a>
                <h5 class="mb-0 fs-16"><a href="javascript:void(0);" class="text-body">{{data.title}} <span
                            class="badge bg-success-subtle text-success">{{data.count}}</span></a></h5>
            </div>
        </div>
    </div>
    <!--end col-->
}
</div>
<!--end row-->

<div class="row g-0 text-center text-sm-start align-items-center mb-4">
    <div class="col-sm-6">
        <div>
            <p class="mb-sm-0 text-muted">
                Showing
                1 to
                8 of {{allcollectionData.length}}
                entries
            </p>
        </div>
    </div>
    <!-- end col -->
    <div class="col-sm-6">
        <!-- Pagination -->
        <div class="text-sm-right float-sm-end listjs-pagination">
            <ngb-pagination [collectionSize]="allcollectionData.length" [(page)]="service.page" [pageSize]="service.pageSize" (pageChanged)="changePage()">
            </ngb-pagination>
        </div>
        <!-- End Pagination -->
    </div><!-- end col -->
</div>
<!--end row-->

// React+Inertia/Corporate/resources/js/Pages/NFTMarketplace/Collections/index.tsx
import React from "react";
import { Button, Card, Col, Container, Row } from "react-bootstrap";
import BreadCrumb from "../../../Components/Common/BreadCrumb";

import { topCollection } from "../../../common/data";
import { Head, Link } from "@inertiajs/react";
import Layout from "../../../Layouts";

const Collections = () => {
    return (
        <React.Fragment>
            <Head title = "Collections | Velzon - React Admin & Dashboard Template"/>
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="Collections" pageTitle="NFT Marketplace" />
                    <Row className="g-4 mb-3 align-items-center">
                        <Col className="col-sm-auto">
                            <div>
                                <h5 className="mb-0">Top Collections</h5>
                            </div>
                        </Col>
                        <Col className="col-sm">
                            <div className="d-flex justify-content-sm-end gap-2">
                                <div className="search-box ms-2">
                                    <input type="text" className="form-control" placeholder="Search..." />
                                    <i className="ri-search-line search-icon"></i>
                                </div>
                                <div className="choices">
                                    <select className="form-control w-md">
                                        <option value="All">All</option>
                                        <option value="Today" defaultValue=''>Today</option>
                                        <option value="Yesterday">Yesterday</option>
                                        <option value="Last 7 Days">Last 7 Days</option>
                                        <option value="Last 30 Days">Last 30 Days</option>
                                        <option value="This Month">This Month</option>
                                        <option value="Last Year">Last Year</option>
                                    </select>
                                </div>
                            </div>
                        </Col>
                    </Row>

                    <Row>

                        {topCollection.map((item, key) => (<Col xl={3} md={4} sm={6} key={key}>
                            <Card>
                                <Card.Body>
                                    <Row className="g-1 mb-3">
                                        {item.subItem.map((item, key) => (<Col className="col-6" key={key}>
                                            {item.isChildren.map((item, key) => (<img src={item.img} alt="" className={"img-fluid rounded " + item.imgClass} key={key} />))}
                                        </Col>))}
                                    </Row>
                                    <Link href="#" className="float-end"> View All <i className="ri-arrow-right-line align-bottom"></i></Link>
                                    <h5 className="mb-0 fs-16"><Link href="#">{item.category} <span className="badge bg-success-subtle text-success">{item.quantity}</span></Link></h5>
                                </Card.Body>
                            </Card>
                        </Col>))}
                    </Row>

                    <Row className="g-0 text-center text-sm-start align-items-center mb-4">
                        <Col sm={6}>
                            <div>
                                <p className="mb-sm-0 text-muted">Showing <span className="fw-semibold">1</span> to <span className="fw-semibold">8</span> of <span className="fw-semibold text-decoration-underline">12</span> entries</p>
                            </div>
                        </Col>

                        <Col sm={6}>
                            <ul className="pagination pagination-separated justify-content-center justify-content-sm-end mb-sm-0">
                                <li className="page-item disabled">
                                    <Button variant="link" className="page-link">Previous</Button>
                                </li>
                                <li className="page-item active">
                                    <Button variant="link" className="page-link">1</Button>
                                </li>
                                <li className="page-item ">
                                    <Button variant="link" className="page-link">2</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">3</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">4</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">5</Button>
                                </li>
                                <li className="page-item">
                                    <Button variant="link" className="page-link">Next</Button>
                                </li>
                            </ul>
                        </Col>
                    </Row>
                </Container>
            </div>
        </React.Fragment>
    );
};
Collections.layout = (page:any) => <Layout children={page}/>
export default Collections;
