// React+Inertia/Default/resources/js/Pages/DashboardNFT/Popularity.tsx
import React from 'react';
import { Card, Col } from 'react-bootstrap';
import { popularityData } from "../../common/data/dashboardNFT";

// Import Chart
import { PopularityChart } from "./DashboardNFTCharts";

//SimpleBar
import SimpleBar from "simplebar-react";
import { Link } from '@inertiajs/react';

const Popularity = () => {

    return (
        <React.Fragment>
            <Col xxl={3}>
                <Card>
                    <Card.Header className="border-0 pb-0">
                        <h6 className="card-title mb-0">Popularity</h6>
                    </Card.Header>
                    <div>
                        <PopularityChart dataColors='["--vz-success", "--vz-warning"]' />
                    </div>
                </Card>

                <Card>
                    <Card.Header className="d-flex align-items-center">
                        <h6 className="card-title mb-0 flex-grow-1">History of Bids</h6>
                        <Link className="text-muted" href="/apps-nft-item-details">
                            See All <i className="ri-arrow-right-line align-bottom"></i>
                        </Link>
                    </Card.Header>
                    <Card.Body>
                        <div className="table-responsive table-card">
                            <SimpleBar style={{ maxHeight: "365px" }}>
                                <ul className="list-group list-group-flush">
                                    {popularityData.map((item, key) => (
                                        <li key={key} className="list-group-item list-group-item-action">
                                            <div className="d-flex align-items-center">
                                                <img src={item.img} alt="" className="avatar-xs object-fit-cover rounded-circle" />
                                                <div className="ms-3 flex-grow-1">
                                                    <Link href="#" className="stretched-link">
                                                        <h6 className="fs-14 mb-1">{item.author}</h6>
                                                    </Link>
                                                    <p className="mb-0 text-muted">{item.username}</p>
                                                </div>
                                                <div>
                                                    <h6>{item.price}</h6>
                                                </div>
                                            </div>
                                        </li>
                                    ))}
                                </ul>
                            </SimpleBar>
                        </div>
                    </Card.Body>
                </Card>
            </Col>
        </React.Fragment>
    );
};

export default Popularity;

// Svelte/modern/src/routes/dashboard-nft/Popularity.svelte
<script>
    import { Card, CardBody, CardHeader, Col } from 'sveltestrap';
    import data from "../../common/data/dashboardNFT";
    import Link from 'svelte-link'
    import PopularityChart from "./PopularityChart.svelte";

</script>
<Col xxl={3}>
    <Card>
        <CardHeader class="border-0 pb-0">
            <h6 class="card-title mb-0">Popularity</h6>
        </CardHeader>
        <div>
            <PopularityChart dataColors={["--vz-success", "--vz-warning"]} />
        </div>
    </Card>

    <Card>
        <CardHeader class="d-flex align-items-center">
            <h6 class="card-title mb-0 flex-grow-1">History of Bids</h6>
            <Link class="text-muted" href="/NFTmarketplace/Itemdetails/apps-nft-item-details">
                See All <i class="ri-arrow-right-line align-bottom"></i>
            </Link>
        </CardHeader>
        <CardBody>
            <div class="table-responsive table-card">
                <div id="scrollbar" data-simplebar style="max-height: 382px">
                    <ul class="list-group list-group-flush">
                        {#each data.popularityData as item}
                            <li class="list-group-item list-group-item-action">
                                <div class="d-flex align-items-center">
                                    <img src={item.img} alt="" class="avatar-xs object-cover rounded-circle" />
                                    <div class="ms-3 flex-grow-1">
                                        <Link href={null} class="stretched-link">
                                            <h6 class="fs-14 mb-1">{item.author}</h6>
                                        </Link>
                                        <p class="mb-0 text-muted">{item.username}</p>
                                    </div>
                                    <div>
                                        <h6>{item.price}</h6>
                                    </div>
                                </div>
                            </li>
                        {/each}
                    </ul>
                </div>
            </div>
        </CardBody>
    </Card>
</Col>
