// Svelte/galaxy/src/routes/email/emailtemplates/ecommerceaction/+page.svelte
<script>
    import BreadCrumb from '../../../../Components/Common/BreadCrumb.svelte';
    import { Container } from 'sveltestrap';
    import InvoiceAction from "./InvoiceAction.svelte";
    import FeedbackAction from "./FeedbackAction.svelte";
    import RatingTemplate from "./RatingTemplate.svelte";
</script>
<svelte:head>
	<title>Ecommerce Action | Velzon - Svelte Admin & Dashboard Template</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
</svelte:head>
<div class="page-content">
    <Container fluid>
        <BreadCrumb title="Ecommerce Action" pageTitle="Email" />
        <InvoiceAction />
        <FeedbackAction />
        <RatingTemplate />
    </Container>
</div>

// React+Inertia/Modern/resources/js/Pages/Email/EmailTemplates/EcommerceAction/index.tsx
import React from 'react';
import { Container } from 'react-bootstrap';
import BreadCrumb from "../../../../Components/Common/BreadCrumb";
import InvoiceAction from "./InvoiceAction";
import FeedbackAction from "./FeedbackAction";
import RatingTemplate from "./RatingTemplate";
import { Head } from '@inertiajs/react';
import Layout from '../../../../Layouts';

const index = () => {
    return (
        <React.Fragment>
            <Head title="Invoice Action | Velzon - React Admin & Dashboard Template" />
            <div className="page-content">
                <Container fluid>
                    <BreadCrumb title="Ecommerce Action" pageTitle="Email" />
                    <InvoiceAction />
                    <FeedbackAction />
                    <RatingTemplate />
                </Container>
            </div>
        </React.Fragment>
    );
}
index.layout = (page: any) => <Layout children={page} />
export default index;
