// React+Inertia/Interactive/resources/js/Pages/Auth/Register.tsx
import React, { useEffect } from 'react';
import GuestLayout from '../../Layouts/GuestLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { Button, Card, Col, Container, Form, Row } from 'react-bootstrap';
import logoLight from '../../../images/logo-light.png';

export default function Register() {
    const { data, setData, post, processing, errors, reset } = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
    });

    useEffect(() => {
        return () => {
            reset('password', 'password_confirmation');
        };
    }, []);

    const submit = (e: any) => {
        e.preventDefault();
        console.log('here')
        post(route('register'));
    };

    return (
        <React.Fragment>
            <GuestLayout>
                <Head title="Basic SignUp | Velzon - React Admin & Dashboard Template" />
                <div className="auth-page-content mt-lg-5">
                    <Container>
                        <Row>
                            <Col lg={12}>
                                <div className="text-center mt-sm-5 mb-4 text-white-50">
                                    <div>
                                        <Link href="/" className="d-inline-block auth-logo">
                                            <img src={logoLight} alt="" height="20" />
                                        </Link>
                                    </div>
                                    <p className="mt-3 fs-15 fw-medium">Premium Admin & Dashboard Template</p>
                                </div>
                            </Col>
                        </Row>

                        <Row className="justify-content-center">
                            <Col md={8} lg={6} xl={5}>
                                <Card className="mt-4">
                                    <Card.Body className="p-4">
                                        <div className="text-center mt-2">
                                            <h5 className="text-primary">Create New Account</h5>
                                            <p className="text-muted">Get your free velzon account now</p>
                                        </div>
                                        <div className="p-2 mt-4">
                                            <form onSubmit={submit}>
                                                <div>
                                                    <Form.Label htmlFor="email" value="Email" className='form-label'> Email </Form.Label>
                                                    <span className="text-danger ms-1">*</span>
                                                    <Form.Control
                                                        id="email"
                                                        type="email"
                                                        name="email"
                                                        placeholder="Enter Email address"
                                                        value={data.email}
                                                        className={'mt-1 form-control' + (errors.email ? 'is-invalid' : '')}
                                                        autoComplete="username"
                                                        onChange={(e: any) => setData('email', e.target.value)}
                                                        required
                                                    />

                                                    <Form.Control.Feedback type="invalid" className='mt-2 d-block'>{errors.email}</Form.Control.Feedback>

                                                </div>

                                                <div className="mt-4">
                                                    <Form.Label htmlFor="name" value="Username" > Username </Form.Label>
                                                    <span className="text-danger ms-1">*</span>

                                                    <Form.Control
                                                        id="name"
                                                        name="name"
                                                        placeholder="Enter username"
                                                        value={data.name}
                                                        className={"mt-1 form-control" + (errors.name ? 'is-invalid' : '')}
                                                        autoComplete="name"
                                                        autoFocus
                                                        onChange={(e: any) => setData('name', e.target.value)}
                                                        required
                                                    />

                                                    <Form.Control.Feedback type="invalid" className='mt-2 d-block'>{errors.name}</Form.Control.Feedback>
                                                </div>

                                                <div className="mt-4">
                                                    <Form.Label htmlFor="password" value="Password" className='form-label'> Password </Form.Label>
                                                    <span className="text-danger ms-1">*</span>
                                                    <Form.Control
                                                        id="password"
                                                        type="password"
                                                        name="password"
                                                        placeholder="Enter Password"
                                                        value={data.password}
                                                        className={"mt-1 form-control" + (errors.password ? 'is-invalid' : '')}
                                                        autoComplete="new-password"
                                                        onChange={(e: any) => setData('password', e.target.value)}
                                                        required
                                                    />

                                                    <Form.Control.Feedback type="invalid" className='mt-2 d-block'>{errors.password}</Form.Control.Feedback>
                                                </div>

                                                <div className="mt-4">
                                                    <Form.Label htmlFor="password_confirmation" value="Confirm Password" className='form-label'> Confirm Password </Form.Label>
                                                    <span className="text-danger ms-1">*</span>

                                                    <Form.Control
                                                        id="password_confirmation"
                                                        type="password"
                                                        placeholder="Confirm password"
                                                        name="password_confirmation"
                                                        value={data.password_confirmation}
                                                        className={"mt-1 form-control" + (errors.password_confirmation ? 'is-invalid' : '')}
                                                        autoComplete="new-password"
                                                        onChange={(e: any) => setData('password_confirmation', e.target.value)}
                                                        required
                                                    />

                                                    <Form.Control.Feedback type="invalid" className='mt-2 d-block'>{errors.password_confirmation}</Form.Control.Feedback>
                                                </div>

                                                <div className="mb-4 mt-4">
                                                    <p className="mb-0 fs-12 text-muted fst-italic">By registering you agree to the Velzon 
                                                        <Link href="#" className="text-primary text-decoration-underline fst-normal fw-medium ms-2"> Terms of Use</Link></p>
                                                </div>

                                                <Button type="submit" className="btn btn-info w-100" disabled={processing}>
                                                    Sign Up
                                                </Button>

                                                <div className="mt-4 text-center">
                                                    <div className="signin-other-title">
                                                        <h5 className="fs-13 mb-4 title text-muted">Create account with</h5>
                                                    </div>

                                                    <div>
                                                        <button type="button" className="btn btn-primary btn-icon waves-effect waves-light"><i className="ri-facebook-fill fs-16"></i></button>{" "}
                                                        <button type="button" className="btn btn-danger btn-icon waves-effect waves-light"><i className="ri-google-fill fs-16"></i></button>{" "}
                                                        <button type="button" className="btn btn-dark btn-icon waves-effect waves-light"><i className="ri-github-fill fs-16"></i></button>{" "}
                                                        <button type="button" className="btn btn-info btn-icon waves-effect waves-light"><i className="ri-twitter-fill fs-16"></i></button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </Card.Body>
                                </Card>
                                <div className="mt-4 text-center">
                                    <p className="mb-0">Already have an account ? <Link href={route('login')} className="fw-semibold text-primary text-decoration-underline"> Signin </Link> </p>
                                </div>
                            </Col>
                        </Row>
                    </Container>
                </div>
            </GuestLayout>
        </React.Fragment>
    );
}

// Angular/galaxy/src/app/account/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup, Validators } from '@angular/forms';

// Register Auth
import { environment } from '../../../environments/environment';
import { AuthenticationService } from '../../core/services/auth.service';
import { UserProfileService } from '../../core/services/user.service';
import { Router } from '@angular/router';
import { first } from 'rxjs/operators';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})

/**
 * Register Component
 */
export class RegisterComponent implements OnInit {

  // Login Form
  signupForm!: UntypedFormGroup;
  submitted = false;
  successmsg = false;
  error = '';
  // set the current year
  year: number = new Date().getFullYear();

  constructor(private formBuilder: UntypedFormBuilder, private router: Router,
    private authenticationService: AuthenticationService,
    private userService: UserProfileService) { }

  ngOnInit(): void {
    /**
     * Form Validatyion
     */
     this.signupForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      name: ['', [Validators.required]],
      password: ['', Validators.required],
    });

    document.documentElement.setAttribute('ddata-bs-theme', 'dark');
    document.documentElement.setAttribute('data-body-image', 'img-1');
  }

  // convenience getter for easy access to form fields
  get f() { return this.signupForm.controls; }

  /**
   * Register submit form
   */
   onSubmit() {
    this.submitted = true;
    
    //Register Api
    this.authenticationService.register(this.f['email'].value, this.f['name'].value, this.f['password'].value).pipe(first()).subscribe(
      (data: any) => {
      this.successmsg = true;
      if (this.successmsg) {
        this.router.navigate(['/auth/login']);
      }
    },
    (error: any) => {
      this.error = error ? error : '';
    });

    // stop here if form is invalid
    // if (this.signupForm.invalid) {
    //   return;
    // } else {
    //   if (environment.defaultauth === 'firebase') {
    //     this.authenticationService.register(this.f['email'].value, this.f['password'].value).then((res: any) => {
    //       this.successmsg = true;
    //       if (this.successmsg) {
    //         this.router.navigate(['']);
    //       }
    //     })
    //       .catch((error: string) => {
    //         this.error = error ? error : '';
    //       });
    //   } else {
    //     this.userService.register(this.signupForm.value)
    //       .pipe(first())
    //       .subscribe(
    //         (data: any) => {
    //           this.successmsg = true;
    //           if (this.successmsg) {
    //             this.router.navigate(['/auth/login']);
    //           }
    //         },
    //         (error: any) => {
    //           this.error = error ? error : '';
    //         });
    //   }
    // }
  }

}

<div class="auth-page-wrapper pt-5">
  <!-- auth page content -->
  <div class="auth-page-content">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="text-center mt-sm-5 mb-4 text-white-50">
                      <div>
                          <a routerLink="" class="d-inline-block auth-logo">
                              <img src="assets/images/logo-light.png" alt="" height="20">
                          </a>
                      </div>
                      <p class="mt-3 fs-15 fw-medium">Premium Admin & Dashboard Template</p>
                  </div>
              </div>
          </div>
          <!-- end row -->

          <div class="row justify-content-center">
              <div class="col-md-8 col-lg-6 col-xl-5">
                  <div class="card mt-4">

                      <div class="card-body p-4">
                          <div class="text-center mt-2">
                              <h5 class="text-primary">Create New Account</h5>
                              <p class="text-muted">Get your free velzon account now</p>
                          </div>
                          <div class="p-2 mt-4">
                              <form [formGroup]="signupForm" (ngSubmit)="onSubmit()">

                                  <div class="mb-3">
                                      <label for="useremail" class="form-label">Email <span class="text-danger">*</span></label>
                                      <input type="email" class="form-control" id="useremail" placeholder="Enter email address" required formControlName="email" [ngClass]="{ 'is-invalid': submitted && f['email'].errors }">
                                      <div class="invalid-feedback">
                                          Please enter email
                                      </div>
                                  </div>
                                  <div class="mb-3">
                                      <label for="username" class="form-label">Username <span class="text-danger">*</span></label>
                                      <input type="text" class="form-control" id="username" placeholder="Enter username" required formControlName="name" [ngClass]="{ 'is-invalid': submitted && f['name'].errors }">
                                      <div class="invalid-feedback">
                                          Please enter username
                                      </div>
                                  </div>

                                  <div class="mb-2">
                                      <label for="userpassword" class="form-label">Password <span class="text-danger">*</span></label>
                                      <input type="password" class="form-control" id="userpassword" placeholder="Enter password" required formControlName="password" [ngClass]="{ 'is-invalid': submitted && f['password'].errors }">
                                      <div class="invalid-feedback">
                                          Please enter password
                                      </div>
                                  </div>

                                  <div class="mb-4">
                                      <p class="mb-0 fs-12 text-muted fst-italic">By registering you agree to the Velzon <a href="javascript:void(0);" class="text-primary text-decoration-underline fst-normal fw-medium">Terms of Use</a></p>
                                  </div>

                                  <div class="mt-4">
                                      <button class="btn btn-success w-100" type="submit">Sign Up</button>
                                  </div>

                                  <div class="mt-4 text-center">
                                      <div class="signin-other-title">
                                          <h5 class="fs-13 mb-4 title text-muted">Create account with</h5>
                                      </div>

                                      <div class="d-flex gap-2 justify-content-center">
                                          <button type="button" class="btn btn-primary btn-icon waves-effect waves-light"><i class="ri-facebook-fill fs-16"></i></button>
                                          <button type="button" class="btn btn-danger btn-icon waves-effect waves-light"><i class="ri-google-fill fs-16"></i></button>
                                          <button type="button" class="btn btn-dark btn-icon waves-effect waves-light"><i class="ri-github-fill fs-16"></i></button>
                                          <button type="button" class="btn btn-info btn-icon waves-effect waves-light"><i class="ri-twitter-fill fs-16"></i></button>
                                      </div>
                                  </div>
                              </form>

                          </div>
                      </div>
                      <!-- end card body -->
                  </div>
                  <!-- end card -->

                  <div class="mt-4 text-center">
                      <p class="mb-0">Already have an account ? <a routerLink="/auth/login" class="fw-semibold text-primary text-decoration-underline"> Signin </a> </p>
                  </div>

              </div>
          </div>
          <!-- end row -->
      </div>
      <!-- end container -->
  </div>
  <!-- end auth page content -->

  <!-- footer -->
  <footer class="footer">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="text-center">
                      <p class="mb-0 text-muted">&copy; {{year}} Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                  </div>
              </div>
          </div>
      </div>
  </footer>
  <!-- end Footer -->
</div>
<!-- end auth-page-wrapper -->
