// React+TS/Master/src/pages/DashboardNFT/DashboardNFTCharts.tsx
import React from "react";
import ReactApexChart from "react-apexcharts";
import useChartColors from "Components/Common/useChartColors";

const MarketplaceChart = ({ chartId, series }: any) => {
    var MarketplaceChartColors = useChartColors(chartId);

    var options: any = {
        chart: {
            height: 350,
            type: 'line',
            zoom: {
                enabled: false
            },
            toolbar: {
                show: false
            }
        },
        // markers: {
        //     size: 4,
        // },
        dataLabels: {
            enabled: false
        },
        stroke: {
            curve: 'smooth',
            width: 3
        },
        colors: MarketplaceChartColors,
        xaxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        }
    };
    return (
        <React.Fragment>
            <ReactApexChart dir="ltr"
                options={options}
                series={series}
                id={chartId}
                type="line"
                height="350"

                data-colors='["--vz-primary","--vz-success", "--vz-light"]'
                data-colors-corporate='["--vz-primary","--vz-secondary", "--vz-light"]'
                data-colors-galaxy='["--vz-primary","--vz-success", "--vz-secondary"]'
                data-colors-classic='["--vz-primary","--vz-light", "--vz-secondary"]'
                className="apex-charts"
            />
        </React.Fragment>
    );
};

const PopularityChart = ({ chartId }: any) => {
    var PopularityChartColors = useChartColors(chartId);
    const series = [{
        name: 'Like',
        data: [12.45, 16.2, 8.9, 11.42, 12.6, 18.1, 18.2, 14.16]
    }, {
        name: 'Share',
        data: [-11.45, -15.42, -7.9, -12.42, -12.6, -18.1, -18.2, -14.16]
    }];

    const options: any = {
        chart: {
            type: 'bar',
            height: 260,
            stacked: true,
            toolbar: {
                show: false
            },
        },
        plotOptions: {
            bar: {
                columnWidth: '20%',
                borderRadius: [4, 4]
            },
        },
        dataLabels: {
            enabled: false,
            textAnchor: 'top',
        },
        colors: PopularityChartColors,

        fill: {
            opacity: 1
        },
        legend: {
            position: 'top',
            horizontalAlign: 'right',
        },
        yaxis: {
            labels: {
                show: false,
                formatter: function (y: any) {
                    return y.toFixed(0) + "%";
                }
            }
        },
        xaxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
            labels: {
                rotate: -90
            }
        }
    };

    return (
        <React.Fragment>
            <ReactApexChart dir="ltr"
                options={options}
                series={series}
                type="bar"
                height={260}

                data-colors='["--vz-success", "--vz-warning"]'
                data-colors-minimal='["--vz-gray-200", "--vz-primary"]'
                data-colors-corporate='["--vz-success", "--vz-secondary"]'
                data-colors-galaxy='["--vz-primary-rgb, 0.65", "--vz-primary"]'
                className="apex-charts mt-n4"
            />
        </React.Fragment>
    );
};

const TopArtworkChart = ({ seriesData, chartsColor }: any) => {
    const topartworkColors = [chartsColor];
    var options: any = {
        chart: {
            width: 80,
            height: 30,
            type: "line",
            sparkline: {
                enabled: true,
            },
            toolbar: {
                show: false,
            },
        },
        stroke: {
            curve: "smooth",
            width: 2.3,
        },
        tooltip: {
            fixed: {
                enabled: false
            },
            x: {
                show: false
            },
            y: {
                title: {
                    formatter: function (seriesName: any) {
                        return '';
                    }
                }
            },
            marker: {
                show: false
            }
        },
        colors: topartworkColors
    };
    return (
        <React.Fragment>
            <ReactApexChart dir="ltr"
                options={options}
                series={[...seriesData]}
                type="line"
                height="30"
                width="80"
                className="apex-charts"
            />
        </React.Fragment>
    );
};

export { MarketplaceChart, PopularityChart, TopArtworkChart };

// Svelte/master/src/routes/dashboard-nft/DashboardNFTCharts.svelte
<script>
    import { onMount } from "svelte";
    import { browser } from "$app/environment";
    export let dataColors;
    import { themeChangeEvent } from "$lib/eventBus";
    let chart;

    function getChartColorsArray(colors) {
        if (browser) {
            return colors.map(function (value) {
                var newValue = value.replace(" ", "");
                if (newValue.indexOf(",") === -1) {
                    var color = getComputedStyle(
                        document.documentElement
                    ).getPropertyValue(newValue);
                    if (color.indexOf("#") !== -1)
                        color = color.replace(" ", "");
                    if (color) return color;
                    else return newValue;
                } else {
                    var val = value.split(",");
                    if (val.length === 2) {
                        var rgbaColor = getComputedStyle(
                            document.documentElement
                        ).getPropertyValue(val[0]);
                        rgbaColor = "rgba(" + rgbaColor + "," + val[1] + ")";
                        return rgbaColor;
                    } else {
                        return newValue;
                    }
                }
            });
        }
    }

    var MarketplaceChartColors = getChartColorsArray(dataColors);

    const THEME_CHART_COLORS = {
		default: ["--vz-primary","--vz-success", "--vz-light"],
		corporate: ["--vz-primary","--vz-secondary", "--vz-light"],
		galaxy: ["--vz-primary","--vz-success", "--vz-secondary"], 
		classic: ["--vz-primary","--vz-light", "--vz-secondary"],
		minimal: ["--vz-primary","--vz-success", "--vz-light"],
		creative: ["--vz-primary","--vz-success", "--vz-light"],
		modern: ["--vz-primary","--vz-success", "--vz-light"],
		interactive: ["--vz-primary","--vz-success", "--vz-light"],
		vintage: ["--vz-primary","--vz-success", "--vz-light"],
		saas: ["--vz-primary","--vz-success", "--vz-light"],
		material: ["--vz-primary","--vz-success", "--vz-light"],
	};

	// Function to find the index of a key
	function findIndexByKey(key) {
		const keys = Object.keys(THEME_CHART_COLORS);
		return keys.indexOf(key);
	}

	// Subscribe to the theme change event
	const unsubscribeEvent = themeChangeEvent.subscribe((newTheme) => {
		// Handle the theme change event
		if(newTheme == null || newTheme == undefined){
			return;
		}
		let key = findIndexByKey(newTheme);
		let newColors;
		if (key >= 0) {
			newColors = THEME_CHART_COLORS[newTheme];
		}
		if (browser) {
			newColors = ( key >= 0) ? getChartColorsArray(newColors) : dataColors;
			setTimeout(() => {
				chart.updateOptions({
					colors: newColors,
				});
			}, 500);
		}
	});

    var options = {
        chart: {
            id:"dashboardnftcharts",
            height: 350,
            type: "line",
            zoom: {
                enabled: false,
            },
            toolbar: {
                show: false,
            },
        },
        dataLabels: {
            enabled: false,
        },
        stroke: {
            curve: "smooth",
            width: 3,
        },
        series: [{
            name: "Artwork",
            data: [10, 41, 35, 51, 49, 62, 69, 91, 148]
        },
        {
            name: "Auction",
            data: [40, 120, 83, 45, 31, 74, 35, 34, 78]
        },
        {
            name: "Creators",
            data: [95, 35, 20, 130, 64, 22, 43, 45, 31]
        }],
        colors: MarketplaceChartColors,
        xaxis: {
            categories: [
                "Jan",
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
            ],
        },
    };

    onMount(() => {
        chart = new ApexCharts(document.querySelector("#dashboardnftcharts"),options);
        chart.render();
    });
</script>

<div id="dashboardnftcharts" class="apex-charts" dir="ltr" />
