// Svelte/material/src/routes/dashboard-crypto/Widgets1.svelte
<script>
	import { Swiper, SwiperSlide } from 'swiper/svelte';

	// Import Swiper styles
	import 'swiper/css';
	import 'swiper/css/pagination';

	import { Autoplay, Mousewheel } from 'swiper';
	import {
		Card,
		CardBody,
		Col,
		DropdownItem,
		DropdownMenu,
		DropdownToggle,
		Row,
		Dropdown
	} from 'sveltestrap';

	import data from '../../common/data/crypto';
    import DashboardCryptoCharts from './DashboardCryptoCharts.svelte';
	
</script>

<Col lg={12}>
	<Swiper
		slidesPerView={5}
		spaceBetween={24}
		mousewheel={true}
		autoplay={{
			delay: 2000,
			disableOnInteraction: false
		}}
		modules={[Autoplay, Mousewheel]}
		class="cryptoSlider"
	>
		{#each data.cryptoSlider as item}
			<SwiperSlide>
				<Card>
					<CardBody>
						<div class="float-end">
							<Dropdown>
								<DropdownToggle class="text-reset p-0 shadow-none" color="" tag="a" role="button">
									<span class="text-muted fs-18"><i class="mdi mdi-dots-horizontal" /></span>
								</DropdownToggle>
								<DropdownMenu class="dropdown-menu dropdown-menu-end" end>
									<DropdownItem href={null}>Details</DropdownItem>
									<DropdownItem href={null}>Cancel</DropdownItem>
								</DropdownMenu>
							</Dropdown>
						</div>
						<div class="d-flex align-items-center">
							<img src={item.img} class="bg-light rounded-circle p-1 avatar-xs img-fluid shadow" alt="" />
							<h6 class="ms-2 mb-0 fs-14">{item.label}</h6>
						</div>
						<Row class="align-items-end g-0">
							<Col xs={6}>
								<h5 class="mb-1 mt-4">{item.price}</h5>
								<p class={'fs-13 fw-medium mb-0 text-' + item.changeClass}>
									{item.change}<span class="text-muted ms-2 fs-10 text-uppercase"
										>({item.coinName})</span
									>
								</p>
							</Col>
							<Col xs={6}>
								<div class="apex-charts crypto-widget" dir="ltr">
									<DashboardCryptoCharts seriesData={item.series} id={item.id} chartsColor={item.chartsColor} />
								</div>
							</Col>
						</Row>
					</CardBody>
				</Card>
			</SwiperSlide>
		{/each}
	</Swiper>
</Col>

// React+Inertia/Minimal/resources/js/Pages/DashboardCrypto/Widgets1.tsx
import React from 'react';
import { Card, Col, Row, Dropdown } from 'react-bootstrap';
import { Swiper, SwiperSlide } from "swiper/react";

import "swiper/css";
import "swiper/css/pagination";

// import required modules
import { Autoplay, Mousewheel } from "swiper/modules";
import { cryptoSlider } from '../../common/data';
import { WidgetsCharts } from './DashboardCryptoCharts';
const Widgets1 = () => {
    return (
        <React.Fragment>
            <Col lg={12}>
                <Swiper
                    slidesPerView={5}
                    spaceBetween={24}
                    mousewheel={true}
                    autoplay={{
                        delay: 2000,
                        disableOnInteraction: false,
                    }}
                    breakpoints={{
                        640: {
                            slidesPerView: 2,
                        },
                        1024: {
                            slidesPerView: 2,
                        },
                        1200: {
                            slidesPerView: 3,
                        },
                        1600: {
                            slidesPerView: 5,
                        },
                    }}
                    modules={[Autoplay, Mousewheel]}
                    className="cryptoSlider">

                    {(cryptoSlider || []).map((item, key) => (
                        <SwiperSlide key={key}>
                            <Card>
                                <Card.Body>
                                    <div className="float-end">
                                        <Dropdown >
                                            <Dropdown.Toggle className="text-reset arrow-none" as="a" role="button">
                                                <span className="text-muted fs-18"><i className="mdi mdi-dots-horizontal"></i></span>
                                            </Dropdown.Toggle>
                                            <Dropdown.Menu className="dropdown-menu dropdown-menu-end">
                                                <Dropdown.Item href="#"> Details </Dropdown.Item>
                                                <Dropdown.Item href="#"> Cancel </Dropdown.Item>
                                            </Dropdown.Menu>
                                        </Dropdown>
                                    </div>
                                    <div className="d-flex align-items-center">
                                        <img src={item.img} className="bg-light rounded-circle p-1 avatar-xs img-fluid" alt="" />
                                        <h6 className="ms-2 mb-0 fs-14">{item.label}</h6>
                                    </div>
                                    <Row className="align-items-end g-0">
                                        <Col xs={6}>
                                            <h5 className="mb-1 mt-4">{item.price}</h5>
                                            <p className={"fs-13 fw-medium mb-0 text-" + item.changeClass}>{item.change}<span className="text-muted ms-2 fs-10 text-uppercase">({item.coinName})</span></p>
                                        </Col>
                                        <Col xs={6}>
                                            <div className="apex-charts crypto-widget" dir="ltr">
                                                <WidgetsCharts seriesData={item.series} chartsColor={item.chartsColor} />
                                            </div>
                                        </Col>
                                    </Row>
                                </Card.Body>
                            </Card>
                        </SwiperSlide>
                    ))}
                </Swiper>
            </Col>
        </React.Fragment>
    );
};

export default Widgets1;
