// React+TS/Corporate/src/pages/Crm/CrmDeals/leadDiscover.tsx
import React from "react";
import { Link } from "react-router-dom";
import {
  Card,
  CardBody,
  UncontrolledCollapse,
  CardFooter,
  Button
} from "reactstrap";

const leadDiscover = (props :any) => {
  return (
    <div className="col">
      <Card>
        <Link
          to="#"
          className={"card-header bg-" + props.deal.bgColor+"-subtle"}
          id={"leadDiscovered" + props.index}
        >
          <h5 className="card-title text-uppercase fw-semibold mb-1 fs-14">
            {props.deal.title}
          </h5>
          <p className="text-muted mb-0">
            {props.deal.price}{" "}
            <span className="fw-medium">{props.deal.deals} Deals</span>
          </p>
        </Link>
      </Card>
      <UncontrolledCollapse
        toggler={"#leadDiscovered" + props.index}
        defaultOpen={true}
      >
        {props.deal.subItems.map((subitem :any, subitemkey :any) => (
          <React.Fragment key={subitemkey}>
            <Card
              className={
                subitem.isRibbon
                  ? "mb-1 ribbon-box ribbon-fill ribbon-sm"
                  : "mb-1"
              }
            >
              {subitem.isRibbon && (
                <div className="ribbon ribbon-info">
                  <i className="ri-flashlight-fill"></i>
                </div>
              )}
              <CardBody>
                <Link
                  to="#"
                  className="d-flex align-items-center"
                  id={"leadInnerDiscovered" + props.index + subitemkey}
                >
                  <div className="flex-shrink-0">
                    <img
                      src={subitem.img}
                      alt=""
                      className="avatar-xs rounded-circle"
                    />
                  </div>
                  <div className="flex-grow-1 ms-3">
                    <h6 className="fs-14 mb-1">{subitem.title}</h6>
                    <p className="text-muted mb-0">
                      {subitem.price} - {subitem.date}
                    </p>
                  </div>
                </Link>
              </CardBody>
              <UncontrolledCollapse
                className="border-top border-top-dashed"
                toggler={"#leadInnerDiscovered" + props.index + subitemkey}
                defaultOpen={subitem.isOpen === true ? true : false}
              >
                <CardBody>
                  <h6 className="fs-14 mb-1">
                    {subitem.subTitle}{" "}
                    <small
                      className={
                        "badge bg-" + subitem.timeDurationClass+"-subtle text-"+subitem.timeDurationClass
                      }
                    >
                      {subitem.timeDuration}
                    </small>
                  </h6>
                  <p className="text-muted">
                    As a company grows however, you find it's not as easy to
                    shout across
                  </p>
                  <ul className="list-unstyled vstack gap-2 mb-0">
                    <li>
                      <div className="d-flex">
                        <div className="flex-shrink-0 avatar-xxs text-muted">
                          <i className="ri-question-answer-line"></i>
                        </div>
                        <div className="flex-grow-1">
                          <h6 className="mb-0">Meeting with Thomas</h6>
                          <small className="text-muted">
                            Yesterday at 9:12AM
                          </small>
                        </div>
                      </div>
                    </li>
                    <li>
                      <div className="d-flex">
                        <div className="flex-shrink-0 avatar-xxs text-muted">
                          <i className="ri-mac-line"></i>
                        </div>
                        <div className="flex-grow-1">
                          <h6 className="mb-0">Product Demo</h6>
                          <small className="text-muted">
                            Monday at 04:41PM
                          </small>
                        </div>
                      </div>
                    </li>
                    <li>
                      <div className="d-flex">
                        <div className="flex-shrink-0 avatar-xxs text-muted">
                          <i className="ri-earth-line"></i>
                        </div>
                        <div className="flex-grow-1">
                          <h6 className="mb-0">Marketing Team Meeting</h6>
                          <small className="text-muted">
                            Monday at 04:41PM
                          </small>
                        </div>
                      </div>
                    </li>
                  </ul>
                </CardBody>
                <CardFooter className="hstack gap-2">
                  <Button color="primary" className="btn-sm w-100">
                    <i className="ri-phone-line align-bottom me-1"></i> Call
                  </Button>
                  <Button color="secondary" className="btn-sm w-100">
                    <i className="ri-question-answer-line align-bottom me-1"></i>{" "}
                    Message
                  </Button>
                </CardFooter>
              </UncontrolledCollapse>
            </Card>
          </React.Fragment>
        ))}
      </UncontrolledCollapse>
    </div>
  );
};

export default leadDiscover;

// Svelte/galaxy/src/routes/crm/leadDiscover.svelte
<script>
	export let deal, index;
	import { Card, CardBody, Collapse, CardFooter, Button } from "sveltestrap";
	import Link from "svelte-link";
</script>

<div class="col">
	<Card>
		<Link
			href={null}
			class={"card-header bg-" + deal.bgColor+"-subtle"}
			id={"leadDiscovered" + index}
		>
			<h5 class="card-title text-uppercase fw-semibold mb-1 fs-15">
				{deal.title}
			</h5>
			<p class="text-muted mb-0">
				{deal.price}{" "}
				<span class="fw-medium">{deal.deals} Deals</span>
			</p>
		</Link>
	</Card>
	<Collapse toggler={"#leadDiscovered" + index} isOpen={true}>
		{#each deal.subItems as subitem, subitemkey}
			<Card
				class={subitem.isRibbon
					? "mb-1 ribbon-box ribbon-fill ribbon-sm"
					: "mb-1"}
			>
				{#if subitem.isRibbon}
					<div class="ribbon ribbon-info">
						<i class="ri-flashlight-fill" />
					</div>
				{/if}
				<CardBody>
					<Link
						href={null}
						class="d-flex align-items-center"
						id={"leadInnerDiscovered" + index + subitemkey}>
						<div class="flex-shrink-0">
							<img
								src={subitem.img}
								alt=""
								class="avatar-xs rounded-circle"
							/>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">{subitem.title}</h6>
							<p class="text-muted mb-0">
								{subitem.price} - {subitem.date}
							</p>
						</div>
					</Link>
				</CardBody>
				<Collapse
					class="border-top border-top-dashed"
					toggler={"#leadInnerDiscovered" + index + subitemkey}
					isOpen={subitem.isOpen === true ? true : false}
				>
					<CardBody>
						<h6 class="fs-14 mb-1">
							{subitem.subTitle}{" "}
							<small
								class={"badge bg-" +
									subitem.timeDurationClass+'-subtle text-' + subitem.timeDurationClass}>
								{subitem.timeDuration}
							</small>
						</h6>
						<p class="text-muted">
							As a company grows however, you find it's not as
							easy to shout across
						</p>
						<ul class="list-unstyled vstack gap-2 mb-0">
							<li>
								<div class="d-flex">
									<div class="flex-shrink-0 avatar-xxs text-muted"
									>
										<i class="ri-question-answer-line" />
									</div>
									<div class="flex-grow-1">
										<h6 class="mb-0">
											Meeting with Thomas
										</h6>
										<small class="text-muted">
											Yesterday at 9:12AM
										</small>
									</div>
								</div>
							</li>
							<li>
								<div class="d-flex">
									<div class="flex-shrink-0 avatar-xxs text-muted"
									>
										<i class="ri-mac-line" />
									</div>
									<div class="flex-grow-1">
										<h6 class="mb-0">Product Demo</h6>
										<small class="text-muted">
											Monday at 04:41PM
										</small>
									</div>
								</div>
							</li>
							<li>
								<div class="d-flex">
									<div class="flex-shrink-0 avatar-xxs text-muted"
									>
										<i class="ri-earth-line" />
									</div>
									<div class="flex-grow-1">
										<h6 class="mb-0">
											Marketing Team Meeting
										</h6>
										<small class="text-muted">
											Monday at 04:41PM
										</small>
									</div>
								</div>
							</li>
						</ul>
					</CardBody>
					<CardFooter class="hstack gap-2">
						<Button color="primary" class="btn-sm w-100">
							<i class="ri-phone-line align-bottom me-1" /> Call
						</Button>
						<Button color="secondary" class="btn-sm w-100">
							<i
								class="ri-question-answer-line align-bottom me-1"
							/>{" "}
							Message
						</Button>
					</CardFooter>
				</Collapse>
			</Card>
		{/each}
	</Collapse>
</div>
