// React+Inertia/Minimal/resources/js/Pages/Projects/ProjectOverview/ActivitiesTab.tsx
import React from 'react';
import { Card, Col, Row } from 'react-bootstrap';

//import images
import avatar1 from "../../../../images/users/avatar-1.jpg";
import avatar4 from "../../../../images/users/avatar-4.jpg";
import avatar3 from "../../../../images/users/avatar-3.jpg";
import avatar2 from "../../../../images/users/avatar-2.jpg";
import avatar6 from "../../../../images/users/avatar-6.jpg";
import avatar7 from "../../../../images/users/avatar-7.jpg";
import avatar8 from "../../../../images/users/avatar-8.jpg";
import image2 from "../../../../images/small/img-2.jpg";
import image3 from "../../../../images/small/img-3.jpg";
import image4 from "../../../../images/small/img-4.jpg";
import { Link } from '@inertiajs/react';

const ActivitiesTab = () => {
    return (
        <React.Fragment>
            <Card>
                <Card.Body>
                    <h5 className="card-title">Activities</h5>
                    <div className="Activity-timeline py-3">
                        <div className="Activity-item d-flex">
                            <div className="flex-shrink-0">
                                <img src={avatar1} alt="" className="avatar-xs rounded-circle Activity-avatar" />
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Oliver Phillips <span className="badge bg-primary-subtle text-primary align-middle">New</span></h6>
                                <p className="text-muted mb-2">We talked about a project on linkedin.</p>
                                <small className="mb-0 text-muted">Today</small>
                            </div>
                        </div>
                        <div className="Activity-item py-3 d-flex">
                            <div className="flex-shrink-0 avatar-xs Activity-avatar">
                                <div className="avatar-title bg-success-subtle text-success rounded-circle">
                                    N
                                </div>
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Nancy Martino <span className="badge bg-secondary-subtle text-secondary align-middle">In Progress</span></h6>
                                <p className="text-muted mb-2"><i className="ri-file-text-line align-middle ms-2"></i> Create new project Buildng product</p>
                                <div className="avatar-group mb-2">
                                    <Link href="#" className="avatar-group-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Christi">
                                        <img src={avatar4} alt="" className="rounded-circle avatar-xs" />
                                    </Link>
                                    <Link href="#" className="avatar-group-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Frank Hook">
                                        <img src={avatar3} alt="" className="rounded-circle avatar-xs" />
                                    </Link>
                                    <Link href="#" className="avatar-group-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title=" Ruby">
                                        <div className="avatar-xs">
                                            <div className="avatar-title rounded-circle bg-light text-primary">
                                                R
                                            </div>
                                        </div>
                                    </Link>
                                    <Link href="#" className="avatar-group-item" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="more">
                                        <div className="avatar-xs">
                                            <div className="avatar-title rounded-circle">
                                                2+
                                            </div>
                                        </div>
                                    </Link>
                                </div>
                                <small className="mb-0 text-muted">Yesterday</small>
                            </div>
                        </div>
                        <div className="Activity-item py-3 d-flex">
                            <div className="flex-shrink-0">
                                <img src={avatar2} alt="" className="avatar-xs rounded-circle Activity-avatar" />
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Natasha Carey <span className="badge bg-success-subtle text-success align-middle">Completed</span></h6>
                                <p className="text-muted mb-2">Adding a new event with attachments</p>
                                <Row>
                                    <Col xxl={4}>
                                        <Row className="border border-dashed gx-2 p-2 mb-2">
                                            <Col xs={4}>
                                                <img src={image2} alt="" className="img-fluid rounded" />
                                            </Col>
                                            <Col xs={4}>
                                                <img src={image3} alt="" className="img-fluid rounded" />
                                            </Col>
                                            <Col xs={4}>
                                                <img src={image4} alt="" className="img-fluid rounded" />
                                            </Col>
                                        </Row>
                                    </Col>
                                </Row>
                                <small className="mb-0 text-muted">25 Nov</small>
                            </div>
                        </div>
                        <div className="Activity-item py-3 d-flex">
                            <div className="flex-shrink-0">
                                <img src={avatar6} alt="" className="avatar-xs rounded-circle Activity-avatar" />
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Bethany Johnson</h6>
                                <p className="text-muted mb-2">added a new member to velzon dashboard</p>
                                <small className="mb-0 text-muted">19 Nov</small>
                            </div>
                        </div>
                        <div className="Activity-item py-3 d-flex">
                            <div className="flex-shrink-0">
                                <div className="avatar-xs Activity-avatar">
                                    <div className="avatar-title rounded-circle bg-danger-subtle text-danger">
                                        <i className="ri-shopping-bag-line"></i>
                                    </div>
                                </div>
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Your order is placed <span className="badge bg-danger-subtle text-danger align-middle ms-1">Out of Delivery</span></h6>
                                <p className="text-muted mb-2">These customers can rest assured their order has been placed.</p>
                                <small className="mb-0 text-muted">16 Nov</small>
                            </div>
                        </div>
                        <div className="Activity-item py-3 d-flex">
                            <div className="flex-shrink-0">
                                <img src={avatar7} alt="" className="avatar-xs rounded-circle Activity-avatar" />
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Lewis Pratt</h6>
                                <p className="text-muted mb-2">They all have something to say beyond the words on the page. They can come across as casual or neutral, exotic or graphic. </p>
                                <small className="mb-0 text-muted">22 Oct</small>
                            </div>
                        </div>
                        <div className="Activity-item py-3 d-flex">
                            <div className="flex-shrink-0">
                                <div className="avatar-xs Activity-avatar">
                                    <div className="avatar-title rounded-circle bg-info-subtle text-info">
                                        <i className="ri-line-chart-line"></i>
                                    </div>
                                </div>
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Monthly sales report</h6>
                                <p className="text-muted mb-2"><span className="text-danger">2 days left</span>
                                notification to submit the monthly sales report. <Link href="#" className="link-warning text-decoration-underline">Reports Builder</Link></p>
                                <small className="mb-0 text-muted">15 Oct</small>
                            </div>
                        </div>
                        <div className="Activity-item d-flex">
                            <div className="flex-shrink-0">
                                <img src={avatar8} alt="" className="avatar-xs rounded-circle Activity-avatar" />
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">New ticket received <span className="badge bg-success-subtle text-success align-middle">Completed</span></h6>
                                <p className="text-muted mb-2">User <span className="text-secondary">Erica245</span> submitted a ticket.</p>
                                <small className="mb-0 text-muted">26 Aug</small>
                            </div>
                        </div>
                    </div>
                </Card.Body>
            </Card>
        </React.Fragment>
    );
};

export default ActivitiesTab;

// Svelte/galaxy/src/routes/projects/apps-projects-overview/ActivitiesTab.svelte
<script>
	import { Card, CardBody, Col, Row, Tooltip } from 'sveltestrap';
	import Link from 'svelte-link';
	import avatar1 from '../../../assets/images/users/avatar-1.jpg';
	import avatar2 from '../../../assets/images/users/avatar-2.jpg';
	import avatar3 from '../../../assets/images/users/avatar-3.jpg';
	import avatar4 from '../../../assets/images/users/avatar-4.jpg';
	import avatar6 from '../../../assets/images/users/avatar-6.jpg';
	import avatar7 from '../../../assets/images/users/avatar-7.jpg';
	import avatar8 from '../../../assets/images/users/avatar-8.jpg';
	import img2 from '../../../assets/images/small/img-2.jpg';
	import img3 from '../../../assets/images/small/img-3.jpg';
	import img4 from '../../../assets/images/small/img-4.jpg';
</script>

<Card>
	<CardBody>
		<h5 class="card-title">Activities</h5>
		<div class="acitivity-timeline py-3">
			<div class="acitivity-item d-flex">
				<div class="flex-shrink-0">
					<img src={avatar1} alt="" class="avatar-xs rounded-circle acitivity-avatar" />
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">
						Oliver Phillips <span class="badge bg-primary-subtle text-primary align-middle">New</span>
					</h6>
					<p class="text-muted mb-2">We talked about a project on linkedin.</p>
					<small class="mb-0 text-muted">Today</small>
				</div>
			</div>
			<div class="acitivity-item py-3 d-flex">
				<div class="flex-shrink-0 avatar-xs acitivity-avatar">
					<div class="avatar-title bg-success-subtle text-success rounded-circle">N</div>
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">
						Nancy Martino <span class="badge bg-secondary-subtle text-primary align-middle">In
							Progress</span>
					</h6>
					<p class="text-muted mb-2">
						<i class="ri-file-text-line align-middle ms-2" /> Create new project Building product
					</p>
					<div class="avatar-group mb-2">
						<Link href="{null}" class="avatar-group-item" id="tooltip-1" data-bs-toggle="tooltip"
							data-bs-placement="top" title="" data-bs-original-title="Christi">
						<img src={avatar4} alt="" class="rounded-circle avatar-xs" />
						</Link>
						<Tooltip target="tooltip-1" placement="top">Christi</Tooltip>

						<Link href="{null}" class="avatar-group-item" id="tooltip-2"
							data-bs-original-title="Frank Hook">
						<img src={avatar3} alt="" class="rounded-circle avatar-xs" />
						</Link>
						<Tooltip target="tooltip-2" placement="top">Frank Hook</Tooltip>

						<Link href="{null}" class="avatar-group-item" id="tooltip-3">
						<div class="avatar-xs">
							<div class="avatar-title rounded-circle bg-light text-primary">R</div>
						</div>
						</Link>
						<Tooltip target="tooltip-3" placement="top">Ruby</Tooltip>

						<Link href="{null}" class="avatar-group-item" id="tooltip-4">
						<div class="avatar-xs">
							<div class="avatar-title rounded-circle">2+</div>
						</div>
						</Link>
						<Tooltip target="tooltip-4" placement="top">More</Tooltip>

					</div>
					<small class="mb-0 text-muted">Yesterday</small>
				</div>
			</div>
			<div class="acitivity-item py-3 d-flex">
				<div class="flex-shrink-0">
					<img src={avatar2} alt="" class="avatar-xs rounded-circle acitivity-avatar" />
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">
						Natasha Carey <span class="badge bg-success-subtle text-success align-middle">Completed</span>
					</h6>
					<p class="text-muted mb-2">Adding a new event with attachments</p>
					<Row>
						<Col xxl={4}>
						<div class="row border border-dashed gx-2 p-2 mb-2">
							<Col xs={4}>
							<img src={img2} alt="" class="img-fluid rounded" />
							</Col><!--end col-->
							<Col xs={4}>
							<img src={img3} alt="" class="img-fluid rounded" />
							</Col><!--end col-->
							<Col xs={4}>
							<img src={img4} alt="" class="img-fluid rounded" />
							</Col><!--end col-->
						</div>
						<!--end row-->
						</Col>
					</Row>
					<small class="mb-0 text-muted">25 Nov</small>
				</div>
			</div>
			<div class="acitivity-item py-3 d-flex">
				<div class="flex-shrink-0">
					<img src={avatar6} alt="" class="avatar-xs rounded-circle acitivity-avatar" />
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">Bethany Johnson</h6>
					<p class="text-muted mb-2">added a new member to velzon dashboard</p>
					<small class="mb-0 text-muted">19 Nov</small>
				</div>
			</div>
			<div class="acitivity-item py-3 d-flex">
				<div class="flex-shrink-0">
					<div class="avatar-xs acitivity-avatar">
						<div class="avatar-title rounded-circle bg-danger-subtle text-danger">
							<i class="ri-shopping-bag-line" />
						</div>
					</div>
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">
						Your order is placed <span class="badge bg-danger-subtle text-danger align-middle ms-1">Out of
							Delivery</span>
					</h6>
					<p class="text-muted mb-2">
						These customers can rest assured their order has been placed.
					</p>
					<small class="mb-0 text-muted">16 Nov</small>
				</div>
			</div>
			<div class="acitivity-item py-3 d-flex">
				<div class="flex-shrink-0">
					<img src={avatar7} alt="" class="avatar-xs rounded-circle acitivity-avatar" />
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">Lewis Pratt</h6>
					<p class="text-muted mb-2">
						They all have something to say beyond the words on the page. They can come across as
						casual or neutral, exotic or graphic.
					</p>
					<small class="mb-0 text-muted">22 Oct</small>
				</div>
			</div>
			<div class="acitivity-item py-3 d-flex">
				<div class="flex-shrink-0">
					<div class="avatar-xs acitivity-avatar">
						<div class="avatar-title rounded-circle bg-info-subtle text-info">
							<i class="ri-line-chart-line" />
						</div>
					</div>
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">Monthly sales report</h6>
					<p class="text-muted mb-2">
						<span class="text-danger">2 days left</span> notification to submit the monthly sales
						report.
						<a href="{null}" class="link-warning text-decoration-underline">Reports Builder</a>
					</p>
					<small class="mb-0 text-muted">15 Oct</small>
				</div>
			</div>
			<div class="acitivity-item d-flex">
				<div class="flex-shrink-0">
					<img src={avatar8} alt="" class="avatar-xs rounded-circle acitivity-avatar" />
				</div>
				<div class="flex-grow-1 ms-3">
					<h6 class="mb-1">
						New ticket received <span
							class="badge bg-success-subtle text-success align-middle">Completed</span>
					</h6>
					<p class="text-muted mb-2">
						User <span class="text-primary">Erica245</span> submitted a ticket.
					</p>
					<small class="mb-0 text-muted">26 Aug</small>
				</div>
			</div>
		</div>
	</CardBody><!--end card-body-->
</Card>
