// React+TS/Interactive/src/Layouts/TwoColumnLayout/index.tsx
import React, { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import PropTypes from "prop-types";
import { Collapse, Container } from 'reactstrap';
import withRouter from '../../Components/Common/withRouter';

import logoSm from "../../assets/images/logo-sm.png";
//i18n
import { withTranslation } from "react-i18next";

// Import Data
import navdata from "../LayoutMenuData";
import VerticalLayout from "../VerticalLayouts";

//SimpleBar
import SimpleBar from "simplebar-react";

const TwoColumnLayout = (props : any) => {
    const navData = navdata().props.children;
    const activateParentDropdown = useCallback((item : any) => {
        item.classList.add("active");
        let parentCollapseDiv = item.closest(".collapse.menu-dropdown");
        if (parentCollapseDiv) {
            // to set aria expand true remaining
            parentCollapseDiv.classList.add("show");
            parentCollapseDiv.parentElement.children[0].classList.add("active");
            parentCollapseDiv.parentElement.children[0].setAttribute("aria-expanded", "true");
            if (parentCollapseDiv.parentElement.closest(".collapse.menu-dropdown")) {
                parentCollapseDiv.parentElement.closest(".collapse").classList.add("show");
                const parentParentCollapse = parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling;
                if (parentParentCollapse) {
                    parentParentCollapse.classList.add("active");
                    if (parentParentCollapse.closest(".collapse.menu-dropdown")) {
                        parentParentCollapse.closest(".collapse.menu-dropdown").classList.add("show");
                    }
                }
            }
            activateIconSidebarActive(parentCollapseDiv.getAttribute("id"));
            return false;
        }
        return false;
    }, []);

    const path = props.router.location.pathname;

    const initMenu = useCallback(() => {
        const pathName = process.env.PUBLIC_URL + path;
        const ul = document.getElementById("navbar-nav") as HTMLElement;
        const items : any = ul.getElementsByTagName("a");
        let itemsArray = [...items]; // converts NodeList to Array
        removeActivation(itemsArray);
        let matchingMenuItem = itemsArray.find((x) => {
            return x.pathname === pathName;
        });
        if (matchingMenuItem) {
            activateParentDropdown(matchingMenuItem);
        } else {
            if (process.env.PUBLIC_URL) {
                var id = pathName.replace(process.env.PUBLIC_URL, '');
                id = id.replace("/", "");
            } else {
                id = pathName.replace("/", "");
            }
            if (id) document.body.classList.add('twocolumn-panel');
            activateIconSidebarActive(id);
        }
    }, [path, activateParentDropdown]);

    useEffect(() => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
        initMenu();
    }, [path, initMenu]);

    function activateIconSidebarActive(id  :any) {
        var menu = document.querySelector("#two-column-menu .simplebar-content-wrapper a[sub-items='" + id + "'].nav-icon");
        if (menu !== null) {
            menu.classList.add("active");
        }
    }

    const removeActivation = (items : any) => {
        let activeItems = items.filter((x : any) => x.classList.contains("active"));
        activeItems.forEach((item : any) => {
            if (item.classList.contains("menu-link")) {
                if (!item.classList.contains("active")) {
                    item.setAttribute("aria-expanded", false);
                }
                item.nextElementSibling.classList.remove("show");
            }
            if (item.classList.contains("nav-link")) {
                if (item.nextElementSibling) {
                    item.nextElementSibling.classList.remove("show");
                }
                item.setAttribute("aria-expanded", false);
            }
            item.classList.remove("active");
        });

        const ul = document.getElementById("two-column-menu") as HTMLElement;
        const iconItems : any = ul.getElementsByTagName("a");
        let itemsArray = [...iconItems];
        let activeIconItems = itemsArray.filter((x) => x.classList.contains("active"));
        activeIconItems.forEach((item:any) => {
            item.classList.remove("active");
            var id = item.getAttribute("sub-items");
            var getId = document.getElementById(id) as HTMLElement;
            if (getId)
                getId.classList.remove("show");
        });
    };

    // Resize sidebar
    const [isMenu, setIsMenu] = useState("twocolumn");
    const windowResizeHover = () => {
        initMenu();
        var windowSize = document.documentElement.clientWidth;
        if (windowSize < 767) {
            document.documentElement.setAttribute("data-layout", "vertical");
            setIsMenu('vertical');
        }
        else {
            document.documentElement.setAttribute("data-layout", "twocolumn");
            setIsMenu('twocolumn');
        }
    };

    useEffect(function setupListener() {
        if (props.layoutType === 'twocolumn') {
            window.addEventListener('resize', windowResizeHover);

            // remove classname when component will unmount
            return function cleanupListener() {
                window.removeEventListener('resize', windowResizeHover);
            };
        }
    });
    return (
        <React.Fragment>
            {isMenu === "twocolumn" ?
                <div id="scrollbar">
                    <Container fluid>
                        <div id="two-column-menu">
                            <SimpleBar className="twocolumn-iconview">
                                <Link to="#" className="logo">
                                    <img src={logoSm} alt="" height="22" />
                                </Link>
                                {(navData || []).map((item : any, key : number) => (
                                    <React.Fragment key={key}>
                                        {item.icon && (
                                            item.subItems ? (
                                                <li>
                                                    <Link
                                                        onClick={item.click}
                                                        to="#"
                                                        sub-items={item.id}
                                                        className="nav-icon"
                                                        data-bs-toggle="collapse">
                                                        <i className={item.icon}></i>
                                                    </Link>
                                                </li>

                                            ) : (
                                                <>
                                                    <Link
                                                        onClick={item.click}
                                                        to={item.link ? item.link : "/#"}
                                                        sub-items={item.id}
                                                        className="nav-icon"
                                                        data-bs-toggle="collapse">
                                                        <i className={item.icon}></i>
                                                    </Link>
                                                </>
                                            )
                                        )}
                                    </React.Fragment>
                                ))}

                            </SimpleBar>
                        </div>
                        <SimpleBar id="navbar-nav" className="navbar-nav">
                            {(navData || []).map((item : any, key : number) => (
                                <React.Fragment key={key}>
                                    {item.subItems ? (
                                        <li className="nav-item">
                                            <Collapse
                                                className="menu-dropdown"
                                                isOpen={item.stateVariables}
                                                id={item.id}>
                                                <ul className="nav nav-sm flex-column test">
                                                    {/* subItms  */}
                                                    {item.subItems && ((item.subItems || []).map((subItem : any, key : number) => (
                                                        <React.Fragment key={key}>
                                                            {!subItem.isChildItem ? (
                                                                <li className="nav-item">
                                                                    <Link
                                                                        to={subItem.link ? subItem.link : "/#"}
                                                                        className="nav-link"
                                                                    >
                                                                        {props.t(subItem.label)}
                                                                        {subItem.badgeName ?
                                                                            <span className={"badge badge-pill bg-" + subItem.badgeColor} data-key="t-new">{subItem.badgeName}</span>
                                                                            : null}
                                                                    </Link>
                                                                </li>
                                                            ) : (
                                                                <li className="nav-item">
                                                                    <Link
                                                                        onClick={subItem.click}
                                                                        className="nav-link"
                                                                        to="/#"
                                                                        data-bs-toggle="collapse"
                                                                    > {props.t(subItem.label)}
                                                                        {subItem.badgeName ?
                                                                            <span className={"badge badge-pill bg-" + subItem.badgeColor} data-key="t-new">{subItem.badgeName}</span>
                                                                            : null}
                                                                    </Link>
                                                                    <Collapse className="menu-dropdown" isOpen={subItem.stateVariables} id={item.id}>
                                                                        <ul className="nav nav-sm flex-column">
                                                                            {/* child subItms  */}
                                                                            {subItem.childItems && (
                                                                                (subItem.childItems || []).map((childItem : any, key : number) => (
                                                                                    <li className="nav-item" key={key}>
                                                                                        <Link
                                                                                            to={childItem.link ? childItem.link : "/#"}
                                                                                            onClick={childItem.click}
                                                                                            className="nav-link" >
                                                                                            {props.t(childItem.label)}

                                                                                        </Link>
                                                                                        <Collapse className="menu-dropdown" isOpen={childItem.stateVariables} id={item.id}>
                                                                                            <ul className="nav nav-sm flex-column">
                                                                                                {/* child subChildItems  */}
                                                                                                {childItem.isChildItem && (
                                                                                                    (childItem.childItems || []).map((childItem : any, key : number) => (
                                                                                                        <li className="nav-item" key={key} >
                                                                                                            <Link
                                                                                                                to={childItem.link ? childItem.link : "/#"}
                                                                                                                className="nav-link">
                                                                                                                {props.t(childItem.label)}
                                                                                                            </Link>
                                                                                                        </li>
                                                                                                    ))
                                                                                                )}
                                                                                            </ul>
                                                                                        </Collapse>
                                                                                    </li>
                                                                                ))
                                                                            )}
                                                                        </ul>
                                                                    </Collapse>
                                                                </li>
                                                            )}
                                                        </React.Fragment>
                                                    ))
                                                    )}
                                                </ul>

                                            </Collapse>
                                        </li>
                                    ) : null
                                    }
                                </React.Fragment>
                            ))}
                        </SimpleBar>
                    </Container>
                </div>
                :
                <SimpleBar id="scrollbar" className="h-100">
                    <Container fluid>
                        <div id="two-column-menu"></div>
                        <ul className="navbar-nav" id="navbar-nav">
                            <VerticalLayout />
                        </ul>
                    </Container>
                </SimpleBar>
            }
        </React.Fragment >
    );
};

TwoColumnLayout.propTypes = {
    location: PropTypes.object,
    t: PropTypes.any,
};

export default withRouter(withTranslation()(TwoColumnLayout));

// Svelte/galaxy/src/Layouts/TwoColumnLayout.svelte
<script>
	import { onMount } from "svelte";
	import { Container } from "sveltestrap";
	import data from "./LayoutMenuData";
	import Link from "svelte-link";
	import logoSm from "../assets/images/logo-sm.png";
	import { _ } from "svelte-i18n";
	import { browser } from "$app/environment";
	import { page } from "$app/stores";
	import VerticalLayout from "./VerticalLayout.svelte";

	const navData = data.Navdata;

	var pathName = "";

	let current = "";
	let current_child = "";
	let current_subchild = "";
	let current_sub_subchild = "";

	const removeActivation = (items, target = null) => {
		let activeItems = items.filter((x) => x.classList.contains("active"));
		activeItems.forEach((item) => {
			if (item.classList.contains("menu-link")) {
				if (!item.classList.contains("active")) {
					item.setAttribute("aria-expanded", false);
				}
				item.nextElementSibling.classList.remove("show");
			}
			if (item.classList.contains("nav-link")) {
				if (item.nextElementSibling) {
					item.nextElementSibling.classList.remove("show");
				}
				item.setAttribute("aria-expanded", false);
			}
			item.classList.remove("active");
		});
		if (browser) {
			const ul = document.getElementById("two-column-menu");
			const iconItems = ul.getElementsByTagName("a");
			let itemsArray = [...iconItems];
			let activeIconItems = itemsArray.filter((x) =>
				x.classList.contains("active")
			);
			activeIconItems.forEach((item) => {
				item.classList.remove("active");
				var id = item.getAttribute("subitems");
				if (document.getElementById(id))
					document.getElementById(id).classList.remove("show");
			});
		}

		// setTimeout(() => {
		if (target && typeof target != undefined) {
			if (target.getAttribute("subitems")) {
				var subitem = target.getAttribute("subitems");
				target.classList.add("active");
				document.getElementById(subitem)
					? document.getElementById(subitem).classList.add("show")
					: "";
			} else {
				activateParentDropdown(target);
				target.nextElementSibling
					? target.nextElementSibling.classList.add("show")
					: "";
			}
		}
		// }, 0);
	};

	function activateParentDropdown(item) {
		item.classList.add("active");
		let parentCollapseDiv = item.closest(".collapse.menu-dropdown");

		if (parentCollapseDiv) {
			// to set aria expand true remaining
			parentCollapseDiv.classList.add("show"); // 1st parent
			var parent = parentCollapseDiv.parentElement;
			var children = parentCollapseDiv.getAttribute("childitem");
			if(children) {
				document.getElementById(children).classList.add("active");
				document.getElementById(children).setAttribute("aria-expanded", "true");
			} else {
				(parentCollapseDiv.parentElement.children[0]) ? parentCollapseDiv.parentElement.children[0].classList.add("active") : "";
				(parentCollapseDiv.parentElement.children[0]) ? parentCollapseDiv.parentElement.children[0].setAttribute("aria-expanded", "true") : "";
				
			}
			if (parent.closest(".collapse.menu-dropdown")) {
				parent.closest(".collapse.menu-dropdown").classList.add("show"); // 2nd parent
				parent.closest(".collapse.menu-dropdown").setAttribute("aria-expanded", "true");
				var parentElementDiv = parent.closest(".collapse.menu-dropdown");
				if (parentElementDiv) {
					parentElementDiv.classList.add("show");
					parentElementDiv.parentElement.children[0].setAttribute("aria-expanded", "true");
					parentElementDiv.parentElement.children[0].classList.add("active");
					if(parentElementDiv.parentElement.closest(".collapse.menu-dropdown")) {
						var parentParent = parentElementDiv.parentElement.closest(".collapse.menu-dropdown");
						parentParent.classList.add("show");
						var id = parentParent.getAttribute("id");
						activateIconSidebarActive(id);
					} else {
						var id = parentElementDiv.getAttribute("id");
						activateIconSidebarActive(id);	
					}
				} else {
					var id = parent.getAttribute("id");
					activateIconSidebarActive(id);
				}
			} else {
				var id = parentCollapseDiv.getAttribute("id");
				activateIconSidebarActive(id);
			}
			return false;
		}
		return false;
	}

	var pathName = "";

	function activateIconSidebarActive(id) {
		if (browser) {
			var menu = document.querySelector("#two-column-menu a[subitems='" + id + "'].nav-icon");
			if (menu !== null) {
				menu.classList.add("active");
			}
		}
	}

	const initialMenu = () => {
		if (browser) {
			pathName = $page.url.pathname;
			if (pathName === "/Widgets/widget") {
				document.body.classList.add("twocolumn-panel");
			} else {
				document.body.classList.remove("twocolumn-panel");
			}
			const ul = document.getElementById("navbar-nav");
			const items = ul.getElementsByTagName("a");
			let itemsArray = [...items]; // converts NodeList to Array
			removeActivation(itemsArray);

			let matchingMenuItem = itemsArray.find((x) => {
				return x.pathname === pathName;
			});

			if (matchingMenuItem) {
				activateParentDropdown(matchingMenuItem);
			} else {
				activateIconSidebarActive(pathName);
			}
		}
	};

	onMount(async () => {
		const initMenu = () => {
			if (browser) {
				pathName = $page.url.pathname;
				if (pathName === "/Widgets/widget") {
					document.body.classList.add("twocolumn-panel");
				} else {
					document.body.classList.remove("twocolumn-panel");
				}
				const ul = document.getElementById("navbar-nav");
				const items = ul.getElementsByTagName("a");
				let itemsArray = [...items]; // converts NodeList to Array
				removeActivation(itemsArray);

				let matchingMenuItem = itemsArray.find((x) => {
					return x.pathname === pathName;
				});

				if (matchingMenuItem) {
					activateParentDropdown(matchingMenuItem);
				} else {
					activateIconSidebarActive(pathName);
				}
			}
		};

		initMenu();
	});

	function changeClassAttribute(e, attribute, child = null, subchild = null, subsubchild = null) {
		document.body.classList.remove("twocolumn-panel");
		e ? e.preventDefault() : "";
		if (!e) {
			if (subchild && subchild === current_subchild && subsubchild == null) {
				current_subchild = null;
			} else if ( attribute === current && child === null && subchild === null ) {
				current = null;
				current_child = null;
				current_subchild = null;
			} else if ( attribute === current && child === current_child && subchild !== null ) {
				current = attribute;
				current_child = child;
				current_subchild = subchild;
			} else {
				current = attribute;
				current_child = child;
				current_subchild = subchild;
				current_sub_subchild = subsubchild;
			}
			if(subsubchild != null) {
				current_sub_subchild = subsubchild;
			}

			if(attribute === 'widgets'){
				document.body.classList.add("twocolumn-panel");
			}

			setTimeout(() => {
				// add active class to the menu
				document.querySelector(
					"#navbar-nav a[id='" + current_child + "'].nav-link"
				)
					? document
							.querySelector(
								"#navbar-nav a[id='" +
									current_child +
									"'].nav-link"
							)
							.classList.add("active")
					: "";
				// add active class to the submenu
				if (current_subchild)
					document.querySelector(
						"#navbar-nav a[id='" + current_subchild + "'].nav-link"
					)
						? document
								.querySelector(
									"#navbar-nav a[id='" +
										current_subchild +
										"'].nav-link"
								)
								.classList.add("active")
						: "";
				// add the active class to the icon sidebar
				activateIconSidebarActive(current);
				document.getElementById(current)
					? document.getElementById(current).classList.add("show")
					: "";
			}, 0);
			return false;
		} else {
			const ul = document.getElementById("navbar-nav");
			const items = ul.getElementsByTagName("a");
			let itemsArray = [...items]; // converts NodeList to Array
			removeActivation(itemsArray, e.target);
		}
	}

	var menu = "twocolumn";

	const setIsMenu = (newmenu) => {
		menu = newmenu;
	};

	const windowResizeHover = () => {
		setTimeout(initialMenu, 500);
		var windowSize = document.documentElement.clientWidth;
		if (windowSize < 767) {
			document.documentElement.setAttribute("data-layout", "vertical");
			setIsMenu("vertical");
		} else {
			document.documentElement.setAttribute("data-layout", "twocolumn");
			setIsMenu("twocolumn");
		}
	};

	onMount(() => {
		window.addEventListener("resize", windowResizeHover);

		return () => {
			window.removeEventListener("resize", windowResizeHover);
		};
	});
</script>

<svelte:head>
	<script src="//unpkg.com/simplebar@latest/dist/simplebar.min.js"></script>
	<script src="//cdn.jsdelivr.net/npm/simplebar@latest/dist/simplebar.min.js"></script>
</svelte:head>

{#if menu == "twocolumn"}
	<div id="scrollbar">
		<Container fluid>
			<div id="two-column-menu">
				<div data-simplebar class="twocolumn-iconview">
					<Link href="{null}" class="logo">
						<img src={logoSm} alt="" height="22" />
					</Link>
					{#each navData as item}
						{#if item.icon}
							{#if item.subItems}
								<li>
									<a
										href="{null}"
										subitems={item.id}
										class={current === item.id
											? "nav-icon active"
											: "nav-icon"}
										id={item.stateVariables}
										on:click={(e) =>
											changeClassAttribute(e, item.id)}
									>
										<i class={item.icon} />
									</a>
								</li>
							{:else}
								<a
									href={item.link}
									subitems={item.id}
									class={current === item.id
										? "nav-icon active"
										: "nav-icon"}
									id={item.stateVariables}
									on:click={(e) => {
										changeClassAttribute("", item.id);
									}}
								>
									<i class={item.icon} />
								</a>
							{/if}
						{/if}
					{/each}
				</div>
			</div>
			<div data-simplebar id="navbar-nav" class="navbar-nav">
				{#each navData as item}
					{#if item.subItems}
						<li class="nav-item">
							<div
								class={current === item.id
									? "collapse menu-dropdown show"
									: "collapse menu-dropdown"}
								id={item.id}
							>
								<ul class="nav nav-sm flex-column">
									{#each item.subItems as subItem}
										{#if !subItem.isChildItem}
											<li class="nav-item">
												<Link
													id={subItem.id}
													class={current_child === subItem.id ? "nav-link active" : "nav-link"}
													href={subItem.link}
													on:click={() => changeClassAttribute("", item.id, subItem.id)}>
													{$_(subItem.label)}
													{#if subItem.badgeName}
														<span class={"badge badge-pill bg-" + subItem.badgeColor} data-key="t-new">
															{$_( subItem.badgeName )}
														</span>
													{/if}
												</Link>
											</li>
										{:else}
											<li class="nav-item">
												<Link
													class={current_child === subItem.id ? "nav-link active" : "nav-link"}
													href="{null}"
													data-bs-toggle="collapse"
													aria-expanded={current_child === subItem.id ? "true" : "false"}
													id={subItem.id}
													on:click={(e) =>
														changeClassAttribute(e, item.id, subItem.id )}
												>
													{$_(subItem.label)}
													{#if subItem.badgeName}
														<span class={"badge badge-pill bg-" + subItem.badgeColor} data-key="t-new">
															{$_( subItem.badgeName )}
														</span>
														{/if}
												</Link>
												<div
													class={current_child === subItem.id ? "collapse menu-dropdown show" : "collapse menu-dropdown"}
													id={subItem.stateVariables}
													istrue={current_child === subItem.id}
												>
													<ul class="nav nav-sm flex-column">
														{#if subItem.childItems}
															{#each subItem.childItems as childItem}
															{#if !childItem.childItems}
																<li class="nav-item">
																	<a
																		on:click={(e) => changeClassAttribute("",item.id, subItem.id, childItem.id )}
																		class={current_subchild === childItem.id ? "nav-link active" : "nav-link"}
																		href={childItem.link}
																		id={childItem.id}
																	>
																		{$_(childItem.label)}
																		{#if childItem.isChildItem}
																			<span class="badge badge-pill bg-danger" data-key="t-new">New</span>
																		{/if}
																	</a>
																	</li>
																{:else}
																<span class={current_subchild === childItem.id ? "nav-link active" : "nav-link"}
																	id={childItem.id}
																	data-bs-toggle="collapse"
																	aria-expanded={current_subchild === childItem.id ? "true" : "false"}
																	on:click={(e) => changeClassAttribute(e,item.id, subItem.id, childItem.id)}>
																		{$_(childItem.label)}
																	</span>
																		<div
																			class="collapse menu-dropdown {current_subchild === childItem.id ? 'show' : ''}"
																			id={item.id}
																			childItem={childItem.id}
																		>
																			<ul class="nav nav-sm flex-column">
																				{#each childItem.childItems as subChildItem}
																					<li class="nav-item">
																						<a
																							class={current_sub_subchild === subChildItem.id ? "nav-link active here" : "nav-link else"}
																							href={subChildItem.link}
																							on:click={(e) => changeClassAttribute("",item.id, subItem.id, childItem.id, subChildItem.id )}
																						>
																							{$_( subChildItem.label )}
																						</a>
																					</li>
																				{/each}
																			</ul>
																		</div>
																{/if}
															{/each}
														{/if}
													</ul>
												</div>
											</li>
										{/if}
									{/each}
								</ul>
							</div>
						</li>
					{/if}
				{/each}
			</div>
		</Container>
	</div>
{:else}
	<div id="scrollbar" data-simplebar class="h-100">
		<Container fluid>
			<div id="two-column-menu" />
			<ul class="navbar-nav" id="navbar-nav">
				<VerticalLayout />
			</ul>
		</Container>
	</div>
{/if}
