// React+Inertia/Minimal/resources/js/Pages/DashboardProject/UpcomingSchedules.tsx
import React from 'react';
import Flatpickr from "react-flatpickr";
import { Button } from 'react-bootstrap';

const UpcomingSchedules = () => {
    return (
        <React.Fragment>
            <div className="col-xxl-4">
                <div className="card card-height-100">
                    <div className="card-header border-0">
                        <h4 className="card-title mb-0">Upcoming Schedules</h4>
                    </div>
                    <div className="card-body pt-0">
                        <div className="upcoming-scheduled">
                            <Flatpickr
                                className="form-control"
                                options={{
                                    dateFormat: "d M, Y",
                                    inline: true
                                }}
                            />
                        </div>

                        <h6 className="text-uppercase fw-semibold mt-4 mb-3 text-muted">Events:</h6>
                        <div className="mini-stats-wid d-flex align-items-center mt-3">
                            <div className="flex-shrink-0 avatar-sm">
                                <span className="mini-stat-icon avatar-title rounded-circle text-primary bg-primary-subtle fs-4">
                                    09
                                </span>
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Development planning</h6>
                                <p className="text-muted mb-0">iTest Factory </p>
                            </div>
                            <div className="flex-shrink-0">
                                <p className="text-muted mb-0">9:20 <span className="text-uppercase">am</span></p>
                            </div>
                        </div>
                        <div className="mini-stats-wid d-flex align-items-center mt-3">
                            <div className="flex-shrink-0 avatar-sm">
                                <span className="mini-stat-icon avatar-title rounded-circle text-primary bg-primary-subtle fs-4">
                                    12
                                </span>
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Design new UI and check sales</h6>
                                <p className="text-muted mb-0">Meta4Systems</p>
                            </div>
                            <div className="flex-shrink-0">
                                <p className="text-muted mb-0">11:30 <span className="text-uppercase">am</span></p>
                            </div>
                        </div>
                        <div className="mini-stats-wid d-flex align-items-center mt-3">
                            <div className="flex-shrink-0 avatar-sm">
                                <span className="mini-stat-icon avatar-title rounded-circle text-primary bg-primary-subtle fs-4">
                                    25
                                </span>
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">Weekly catch-up </h6>
                                <p className="text-muted mb-0">Nesta Technologies</p>
                            </div>
                            <div className="flex-shrink-0">
                                <p className="text-muted mb-0">02:00 <span className="text-uppercase">pm</span></p>
                            </div>
                        </div>
                        <div className="mini-stats-wid d-flex align-items-center mt-3">
                            <div className="flex-shrink-0 avatar-sm">
                                <span className="mini-stat-icon avatar-title rounded-circle text-primary bg-primary-subtle fs-4">
                                    27
                                </span>
                            </div>
                            <div className="flex-grow-1 ms-3">
                                <h6 className="mb-1">James Bangs (Client) Meeting</h6>
                                <p className="text-muted mb-0">Nesta Technologies</p>
                            </div>
                            <div className="flex-shrink-0">
                                <p className="text-muted mb-0">03:45 <span className="text-uppercase">pm</span></p>
                            </div>
                        </div>

                        <div className="mt-3 text-center">
                        <Button variant='link' className="text-muted text-decoration-underline">View all Events</Button>
                        </div>

                    </div>
                </div>
            </div>
        </React.Fragment>
    );
};

export default UpcomingSchedules;

// Svelte/minimal/src/routes/dashboard-projects/UpcomingSchedules.svelte
<script>
    import Flatpickr from 'svelte-flatpickr';
</script>
<div class="col-xxl-4">
    <div class="card">
        <div class="card-header border-0">
            <h4 class="card-title mb-0">Upcoming Schedules</h4>
        </div>
        <div class="card-body pt-0">
            <div class="upcoming-scheduled">
                <Flatpickr class="form-control" options={{ dateFormat: "d M, Y" , inline: true }} />
            </div>

            <h6 class="text-uppercase fw-semibold mt-4 mb-3 text-muted">Events:</h6>
            <div class="mini-stats-wid d-flex align-items-center mt-3">
                <div class="flex-shrink-0 avatar-sm">
                    <span class="mini-stat-icon avatar-title rounded-circle text-primary bg-primary-subtle fs-4">
                        09
                    </span>
                </div>
                <div class="flex-grow-1 ms-3">
                    <h6 class="mb-1">Development planning</h6>
                    <p class="text-muted mb-0">iTest Factory </p>
                </div>
                <div class="flex-shrink-0">
                    <p class="text-muted mb-0">9:20 <span class="text-uppercase">am</span></p>
                </div>
            </div>
            <div class="mini-stats-wid d-flex align-items-center mt-3">
                <div class="flex-shrink-0 avatar-sm">
                    <span class="mini-stat-icon avatar-title rounded-circle text-primary bg-primary-subtle fs-4">
                        12
                    </span>
                </div>
                <div class="flex-grow-1 ms-3">
                    <h6 class="mb-1">Design new UI and check sales</h6>
                    <p class="text-muted mb-0">Meta4Systems</p>
                </div>
                <div class="flex-shrink-0">
                    <p class="text-muted mb-0">11:30 <span class="text-uppercase">am</span></p>
                </div>
            </div>
            <div class="mini-stats-wid d-flex align-items-center mt-3">
                <div class="flex-shrink-0 avatar-sm">
                    <span class="mini-stat-icon avatar-title rounded-circle text-success bg-success-subtle fs-4">
                        25
                    </span>
                </div>
                <div class="flex-grow-1 ms-3">
                    <h6 class="mb-1">Weekly catch-up </h6>
                    <p class="text-muted mb-0">Nesta Technologies</p>
                </div>
                <div class="flex-shrink-0">
                    <p class="text-muted mb-0">02:00 <span class="text-uppercase">pm</span></p>
                </div>
            </div>
            <div class="mini-stats-wid d-flex align-items-center mt-3">
                <div class="flex-shrink-0 avatar-sm">
                    <span class="mini-stat-icon avatar-title rounded-circle text-primary bg-primary-subtle fs-4">
                        27
                    </span>
                </div>
                <div class="flex-grow-1 ms-3">
                    <h6 class="mb-1">James Bangs (Client) Meeting</h6>
                    <p class="text-muted mb-0">Nesta Technologies</p>
                </div>
                <div class="flex-shrink-0">
                    <p class="text-muted mb-0">03:45 <span class="text-uppercase">pm</span></p>
                </div>
            </div>

            <div class="mt-3 text-center">
                <a href="{null}" class="text-muted text-decoration-underline">View all Events</a>
            </div>

        </div>
    </div>
</div>
