// React+Inertia/Interactive/resources/js/Pages/DashboardCrypto/RecentActivity.tsx
import React from 'react';
import { Card, Col, Dropdown } from 'react-bootstrap';

//Import Icons
import FeatherIcon from "feather-icons-react";

//SimpleBar
import SimpleBar from "simplebar-react";
import { Link } from '@inertiajs/react';

const RecentActivity = () => {
    return (
        <React.Fragment>
            <Col xxl={4} lg={5}>
                <Card className="card-height-100">
                    <Card.Header className="card-header align-items-center d-flex">
                        <h4 className="card-title mb-0 flex-grow-1">Recent Activity</h4>
                        <div className="flex-shrink-0">
                            <Dropdown className="card-header-dropdown">
                                <Dropdown.Toggle as="a" className="text-reset dropdown-btn arrow-none" role="button">
                                    <span className="fw-semibold text-uppercase fs-12">Sort by: </span><span className="text-muted">Current Week<i className="mdi mdi-chevron-down ms-1"></i></span>
                                </Dropdown.Toggle>
                                <Dropdown.Menu className="dropdown-menu-end">
                                    <Dropdown.Item>Today</Dropdown.Item>
                                    <Dropdown.Item>Last Week</Dropdown.Item>
                                    <Dropdown.Item>Last Month</Dropdown.Item>
                                    <Dropdown.Item>Current Year</Dropdown.Item>
                                </Dropdown.Menu>
                            </Dropdown>
                        </div>
                    </Card.Header>
                    <Card.Body className="p-0">
                        <SimpleBar style={{ height: "390px" }}>
                            <div className="p-3">
                                <h6 className="text-muted text-uppercase mb-3 fs-11">25 Dec 2021</h6>
                                <div className="d-flex align-items-center">
                                    <div className="avatar-xs flex-shrink-0">
                                        <span className="avatar-title bg-light rounded-circle">
                                            <FeatherIcon
                                                icon="arrow-down-circle"
                                                className="icon-dual-success icon-sm"
                                            />
                                        </span>
                                    </div>
                                    <div className="flex-grow-1 ms-3">
                                        <h6 className="fs-14 mb-1">Bought Bitcoin</h6>
                                        <p className="text-muted fs-12 mb-0">
                                            <i className="mdi mdi-circle-medium text-success fs-15 align-middle"></i>{" "}
                                            Visa Debit Card ***6
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 text-end">
                                        <h6 className="mb-1 text-success">+0.04025745<span className="text-uppercase ms-1">Btc</span></h6>
                                        <p className="text-muted fs-13 mb-0">+878.52 USD</p>
                                    </div>
                                </div>
                                <div className="d-flex align-items-center mt-3">
                                    <div className="avatar-xs flex-shrink-0">
                                        <span className="avatar-title bg-light rounded-circle">
                                            <FeatherIcon
                                                icon="send"
                                                className="icon-dual-warning icon-sm"
                                            />
                                        </span>
                                    </div>
                                    <div className="flex-grow-1 ms-3">
                                        <h6 className="fs-14 mb-1">Sent Ethereum</h6>
                                        <p className="text-muted fs-12 mb-0">
                                            <i className="mdi mdi-circle-medium text-warning fs-15 align-middle"></i>{" "}
                                            Sofia Cunha
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 text-end">
                                        <h6 className="mb-1 text-muted">-0.09025182<span className="text-uppercase ms-1">Eth</span></h6>
                                        <p className="text-muted fs-13 mb-0">-659.35 USD</p>
                                    </div>
                                </div>

                                <h6 className="text-muted text-uppercase mb-3 mt-4 fs-11">24 Dec 2021</h6>
                                <div className="d-flex align-items-center">
                                    <div className="avatar-xs flex-shrink-0">
                                        <span className="avatar-title bg-light rounded-circle">
                                            <FeatherIcon
                                                icon="arrow-up-circle"
                                                className="icon-dual-danger icon-sm"
                                            />
                                        </span>
                                    </div>
                                    <div className="flex-grow-1 ms-3">
                                        <h6 className="fs-14 mb-1">Sell Dash</h6>
                                        <p className="text-muted fs-12 mb-0">
                                            <i className="mdi mdi-circle-medium text-danger fs-15 align-middle"></i>{" "}
                                            www.cryptomarket.com
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 text-end">
                                        <h6 className="mb-1 text-danger">-98.6025422<span className="text-uppercase ms-1">Dash</span></h6>
                                        <p className="text-muted fs-13 mb-0">-1508.98 USD</p>
                                    </div>
                                </div>
                                <div className="d-flex align-items-center mt-3">
                                    <div className="avatar-xs flex-shrink-0">
                                        <span className="avatar-title bg-light rounded-circle">
                                            <FeatherIcon
                                                icon="arrow-up-circle"
                                                className="icon-dual-danger icon-sm"
                                            />
                                        </span>
                                    </div>
                                    <div className="flex-grow-1 ms-3">
                                        <h6 className="fs-14 mb-1">Sell Dogecoin</h6>
                                        <p className="text-muted fs-12 mb-0">
                                            <i className="mdi mdi-circle-medium text-success fs-15 align-middle"></i>{" "}
                                            www.coinmarket.com
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 text-end">
                                        <h6 className="mb-1 text-danger">-1058.08025142<span className="text-uppercase ms-1">Doge</span></h6>
                                        <p className="text-muted fs-13 mb-0">-89.36 USD</p>
                                    </div>
                                </div>
                                <div className="d-flex align-items-center mt-3">
                                    <div className="avatar-xs flex-shrink-0">
                                        <span className="avatar-title bg-light rounded-circle">
                                            <FeatherIcon
                                                icon="arrow-up-circle"
                                                className="icon-dual-success icon-sm"
                                            />
                                        </span>
                                    </div>
                                    <div className="flex-grow-1 ms-3">
                                        <h6 className="fs-14 mb-1">Bought Litecoin</h6>
                                        <p className="text-muted fs-12 mb-0">
                                            <i className="mdi mdi-circle-medium text-warning fs-15 align-middle"></i>{" "}
                                            Payment via Wallet
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 text-end">
                                        <h6 className="mb-1 text-success">+0.07225912<span className="text-uppercase ms-1">Ltc</span></h6>
                                        <p className="text-muted fs-13 mb-0">+759.45 USD</p>
                                    </div>
                                </div>

                                <h6 className="text-muted text-uppercase mb-3 mt-4 fs-11">20 Dec 2021</h6>
                                <div className="d-flex align-items-center">
                                    <div className="avatar-xs flex-shrink-0">
                                        <span className="avatar-title bg-light rounded-circle">
                                            <FeatherIcon
                                                icon="send"
                                                className="icon-dual-warning icon-sm"
                                            />
                                        </span>
                                    </div>
                                    <div className="flex-grow-1 ms-3">
                                        <h6 className="fs-14 mb-1">Sent Ethereum</h6>
                                        <p className="text-muted fs-12 mb-0">
                                            <i className="mdi mdi-circle-medium text-warning fs-15 align-middle"></i>{" "}
                                            Sofia Cunha
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 text-end">
                                        <h6 className="mb-1 text-muted">-0.09025182<span className="text-uppercase ms-1">Eth</span></h6>
                                        <p className="text-muted fs-13 mb-0">-659.35 USD</p>
                                    </div>
                                </div>

                                <div className="d-flex align-items-center mt-3">
                                    <div className="avatar-xs flex-shrink-0">
                                        <span className="avatar-title bg-light rounded-circle">
                                            <FeatherIcon
                                                icon="arrow-down-circle"
                                                className="icon-dual-success icon-sm"
                                            />
                                        </span>
                                    </div>
                                    <div className="flex-grow-1 ms-3">
                                        <h6 className="fs-14 mb-1">Bought Bitcoin</h6>
                                        <p className="text-muted fs-12 mb-0">
                                            <i className="mdi mdi-circle-medium text-success fs-15 align-middle"></i>{" "}
                                            Visa Debit Card ***6
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 text-end">
                                        <h6 className="mb-1 text-success">+0.04025745<span className="text-uppercase ms-1">Btc</span></h6>
                                        <p className="text-muted fs-13 mb-0">+878.52 USD</p>
                                    </div>
                                </div>

                                <div className="mt-3 text-center">
                                    <Link href="#" className="text-muted text-decoration-underline">Load More</Link>
                                </div>

                            </div>

                        </SimpleBar>
                    </Card.Body>
                </Card>
            </Col>
        </React.Fragment>
    );
};

export default RecentActivity;

// Svelte/corporate/src/routes/dashboard-crypto/RecentActivity.svelte
<script>

	import {
		Card,
		CardBody,
		CardHeader,
		Col,
		DropdownItem,
		DropdownMenu,
		DropdownToggle,
		Dropdown
	} from 'sveltestrap';
	import { ArrowDownCircleIcon, SendIcon, ArrowUpCircleIcon } from 'svelte-feather-icons';

</script>

<Col xxl={4} lg={5}>
	<Card class="card-height-100">
		<CardHeader class="card-header align-items-center d-flex">
			<h4 class="card-title mb-0 flex-grow-1">Recent Activity</h4>
			<div class="flex-shrink-0">
				<Dropdown class="card-header-dropdown">
					<DropdownToggle tag="a" class="text-reset dropdown-btn p-0" color="" role="button">
						<span class="fw-semibold text-uppercase fs-12">Sort by: </span><span class="text-muted">Current Week<i class="mdi mdi-chevron-down ms-1" /></span
						>
					</DropdownToggle>
					<DropdownMenu class="dropdown-menu-end" end>
						<DropdownItem>Today</DropdownItem>
						<DropdownItem>Last Week</DropdownItem>
						<DropdownItem>Last Month</DropdownItem>
						<DropdownItem>Current Year</DropdownItem>
					</DropdownMenu>
				</Dropdown>
			</div>
		</CardHeader>
		<CardBody class="p-0">
			<div data-simplebar style="height: 390px;">
				<div class="p-3">
					<h6 class="text-muted text-uppercase mb-3 fs-11">25 Dec 2021</h6>
					<div class="d-flex align-items-center">
						<div class="avatar-xs flex-shrink-0">
							<span class="avatar-title bg-light rounded-circle">
								<ArrowDownCircleIcon class="icon-dual-success icon-sm" />
							</span>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">Bought Bitcoin</h6>
							<p class="text-muted fs-12 mb-0">
								<i class="mdi mdi-circle-medium text-success fs-15 align-middle" />
								Visa Debit Card ***6
							</p>
						</div>
						<div class="flex-shrink-0 text-end">
							<h6 class="mb-1 text-success">
								+0.04025745<span class="text-uppercase ms-1">Btc</span>
							</h6>
							<p class="text-muted fs-13 mb-0">+878.52 USD</p>
						</div>
					</div>
					<div class="d-flex align-items-center mt-3">
						<div class="avatar-xs flex-shrink-0">
							<span class="avatar-title bg-light rounded-circle">
								<SendIcon class="icon-dual-warning icon-sm" />
							</span>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">Sent Ethereum</h6>
							<p class="text-muted fs-12 mb-0">
								<i class="mdi mdi-circle-medium text-warning fs-15 align-middle" />
								Sofia Cunha
							</p>
						</div>
						<div class="flex-shrink-0 text-end">
							<h6 class="mb-1 text-muted">
								-0.09025182<span class="text-uppercase ms-1">Eth</span>
							</h6>
							<p class="text-muted fs-13 mb-0">-659.35 USD</p>
						</div>
					</div>

					<h6 class="text-muted text-uppercase mb-3 mt-4 fs-11">24 Dec 2021</h6>
					<div class="d-flex align-items-center">
						<div class="avatar-xs flex-shrink-0">
							<span class="avatar-title bg-light rounded-circle">
								<ArrowUpCircleIcon class="icon-dual-danger icon-sm" />
							</span>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">Sell Dash</h6>
							<p class="text-muted fs-12 mb-0">
								<i class="mdi mdi-circle-medium text-danger fs-15 align-middle" />
								www.cryptomarket.com
							</p>
						</div>
						<div class="flex-shrink-0 text-end">
							<h6 class="mb-1 text-danger">
								-98.6025422<span class="text-uppercase ms-1">Dash</span>
							</h6>
							<p class="text-muted fs-13 mb-0">-1508.98 USD</p>
						</div>
					</div>
					<div class="d-flex align-items-center mt-3">
						<div class="avatar-xs flex-shrink-0">
							<span class="avatar-title bg-light rounded-circle">
								<ArrowUpCircleIcon class="icon-dual-danger icon-sm" />
							</span>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">Sell Dogecoin</h6>
							<p class="text-muted fs-12 mb-0">
								<i class="mdi mdi-circle-medium text-success fs-15 align-middle" />
								www.coinmarket.com
							</p>
						</div>
						<div class="flex-shrink-0 text-end">
							<h6 class="mb-1 text-danger">
								-1058.08025142<span class="text-uppercase ms-1">Doge</span>
							</h6>
							<p class="text-muted fs-13 mb-0">-89.36 USD</p>
						</div>
					</div>
					<div class="d-flex align-items-center mt-3">
						<div class="avatar-xs flex-shrink-0">
							<span class="avatar-title bg-light rounded-circle">
								<ArrowUpCircleIcon class="icon-dual-success icon-sm" />
							</span>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">Bought Litecoin</h6>
							<p class="text-muted fs-12 mb-0">
								<i class="mdi mdi-circle-medium text-warning fs-15 align-middle" />
								Payment via Wallet
							</p>
						</div>
						<div class="flex-shrink-0 text-end">
							<h6 class="mb-1 text-success">
								+0.07225912<span class="text-uppercase ms-1">Ltc</span>
							</h6>
							<p class="text-muted fs-13 mb-0">+759.45 USD</p>
						</div>
					</div>

					<h6 class="text-muted text-uppercase mb-3 mt-4 fs-11">20 Dec 2021</h6>
					<div class="d-flex align-items-center">
						<div class="avatar-xs flex-shrink-0">
							<span class="avatar-title bg-light rounded-circle">
								<SendIcon class="icon-dual-warning icon-sm" />
							</span>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">Sent Ethereum</h6>
							<p class="text-muted fs-12 mb-0">
								<i class="mdi mdi-circle-medium text-warning fs-15 align-middle" />
								Sofia Cunha
							</p>
						</div>
						<div class="flex-shrink-0 text-end">
							<h6 class="mb-1 text-muted">
								-0.09025182<span class="text-uppercase ms-1">Eth</span>
							</h6>
							<p class="text-muted fs-13 mb-0">-659.35 USD</p>
						</div>
					</div>

					<div class="d-flex align-items-center mt-3">
						<div class="avatar-xs flex-shrink-0">
							<span class="avatar-title bg-light rounded-circle">
								<ArrowDownCircleIcon class="icon-dual-success icon-sm" />
							</span>
						</div>
						<div class="flex-grow-1 ms-3">
							<h6 class="fs-14 mb-1">Bought Bitcoin</h6>
							<p class="text-muted fs-12 mb-0">
								<i class="mdi mdi-circle-medium text-success fs-15 align-middle" />
								Visa Debit Card ***6
							</p>
						</div>
						<div class="flex-shrink-0 text-end">
							<h6 class="mb-1 text-success">
								+0.04025745<span class="text-uppercase ms-1">Btc</span>
							</h6>
							<p class="text-muted fs-13 mb-0">+878.52 USD</p>
						</div>
					</div>

					<div class="mt-3 text-center">
						<a href="{null}" class="text-muted text-decoration-underline">Load More</a>
					</div>
				</div>
			</div>
		</CardBody>
	</Card>
</Col>
