// Svelte/interactive/src/Components/Common/ProfileDropdown.svelte
<script>
    import {
        Dropdown,
        DropdownToggle,
        DropdownMenu,
        DropdownItem,
    } from "sveltestrap";
    import avatar1 from '../../assets/images/users/avatar-1.jpg';
	import { goto,invalidateAll } from '$app/navigation';

const logout = async  function () {
    await invalidateAll();
    localStorage.removeItem('authUser');
    goto('/authentication/login');
}
</script>

<Dropdown class="ms-sm-3 header-item topbar-user">
    <DropdownToggle type="button" color="" class="btn" id="page-header-user-dropdown p-0">
        <span class="d-flex align-items-center">
            <img class="rounded-circle header-profile-user" src={avatar1} alt="Header Avatar" />
            <span class="text-start ms-xl-2">
                <span class="d-none d-xl-inline-block ms-1 fw-medium user-name-text">Anna Adame</span>
                <span class="d-none d-xl-block ms-1 fs-13  user-name-sub-text">Founder</span>
            </span>
        </span>
    </DropdownToggle>
    <DropdownMenu class="dropdown-menu-end" end>
        <!-- item-->
        <h6 class="dropdown-header">Welcome Anna!</h6>
        <DropdownItem href="/pages/profile/simple"><i
                class="mdi mdi-account-circle text-muted fs-16 align-middle me-1" /> <span
                class="align-middle">Profile</span></DropdownItem>
        <DropdownItem href="/apps-chat"><i class="mdi mdi-message-text-outline text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Messages</span>
        </DropdownItem>
        <DropdownItem href="/tasks/apps-tasks-kanban"><i
                class="mdi mdi-calendar-check-outline text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Taskboard</span>
        </DropdownItem>
        <DropdownItem href="/pages/faqs"><i class="mdi mdi-lifebuoy text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Help</span>
        </DropdownItem>
        <div class="dropdown-divider" />
        <DropdownItem href="/pages/profile/simple"><i class="mdi mdi-wallet text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Balance : <b>$5971.67</b></span>
        </DropdownItem>
        <DropdownItem href="/pages/profile/simple"><span
                class="badge bg-success-subtle text-success mt-1 float-end">New</span><i
                class="mdi mdi-cog-outline text-muted fs-16 align-middle me-1" /> <span
                class="align-middle">Settings</span></DropdownItem>
        <DropdownItem href="/authenticationInner/lockscreen/auth-lockscreen-basic"><i
                class="mdi mdi-lock text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Lock screen</span>
        </DropdownItem>
        <DropdownItem href={null} on:click={logout}><i
                class="mdi mdi-logout text-muted fs-16 align-middle me-1" />
            <span class="align-middle" data-key="t-logout">Logout</span>
        </DropdownItem>
    </DropdownMenu>
</Dropdown>

// React+Inertia/Corporate/resources/js/Components/Common/ProfileDropdown.tsx
import React, { useState } from 'react';
import { Dropdown } from 'react-bootstrap';
import { Link, usePage } from '@inertiajs/react';
//import images
import avatar1 from "../../../images/users/avatar-1.jpg";

const ProfileDropdown = () => {

    const user = usePage().props.auth.user;

    //Dropdown Toggle
    const [isProfileDropdown, setIsProfileDropdown] = useState<boolean>(false);
    const toggleProfileDropdown = () => {
        setIsProfileDropdown(!isProfileDropdown);
    };
    return (
        <React.Fragment>
            <Dropdown
                show={isProfileDropdown}
                onClick={toggleProfileDropdown}
                className="ms-sm-3 header-item topbar-user">
                <Dropdown.Toggle as="button" type="button" className="arrow-none btn">
                    <span className="d-flex align-items-center">
                        <img className="rounded-circle header-profile-user" src={avatar1}
                            alt="Header Avatar" />
                        <span className="text-start ms-xl-2">
                            <span className="d-none d-xl-inline-block ms-1 fw-medium user-name-text">{user.name}</span>
                            <span className="d-none d-xl-block ms-1 fs-12 text-muted user-name-sub-text">Founder</span>
                        </span>
                    </span>
                </Dropdown.Toggle>
                <Dropdown.Menu className="dropdown-menu-end">
                    <h6 className="dropdown-header">Welcome {user.name}!</h6>

                    <Dropdown.Item href={route('profile.edit')} className="dropdown-item">
                        <i className="mdi mdi-account-circle text-muted fs-16 align-middle me-1"></i>
                        <span className="align-middle">Edit Profile</span>
                    </Dropdown.Item>

                    <Dropdown.Item href="/apps-chat" className="dropdown-item">
                        <i className="mdi mdi-message-text-outline text-muted fs-16 align-middle me-1"></i> <span
                            className="align-middle">Messages</span>
                    </Dropdown.Item>
                    <Dropdown.Item href={"#"} className="dropdown-item">
                        <i className="mdi mdi-calendar-check-outline text-muted fs-16 align-middle me-1"></i> <span
                            className="align-middle">Taskboard</span>
                    </Dropdown.Item>

                    <Dropdown.Item href="/pages-faqs" className="dropdown-item">
                        <i
                            className="mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"></i> <span
                                className="align-middle">Help</span>
                    </Dropdown.Item>

                    <div className="dropdown-divider"></div>

                    <Dropdown.Item href="/pages-profile" className="dropdown-item">
                        <i
                            className="mdi mdi-wallet text-muted fs-16 align-middle me-1"></i> <span
                                className="align-middle">Balance : <b>$5971.67</b></span>
                    </Dropdown.Item >

                    <Dropdown.Item href="/pages-profile-settings" className="dropdown-item">
                        <span
                            className="badge bg-success-subtle text-success mt-1 float-end">New</span><i
                                className="mdi mdi-cog-outline text-muted fs-16 align-middle me-1"></i> <span
                                    className="align-middle">Settings</span>
                    </Dropdown.Item>

                    <Dropdown.Item href="/auth-lockscreen-basic" className="dropdown-item">
                        <i className="mdi mdi-lock text-muted fs-16 align-middle me-1"></i> <span className="align-middle">Lock screen</span>
                    </Dropdown.Item>
                    <Link className="dropdown-item" as="button" method="post" href={route('logout')}><i
                        className="mdi mdi-logout text-muted fs-16 align-middle me-1"></i> <span
                            className="align-middle" data-key="t-logout">Logout</span></Link>
                </Dropdown.Menu>
            </Dropdown>
        </React.Fragment>
    );
};

export default ProfileDropdown;
