// Svelte/creative/src/routes/landing/NFTLanding/navbar.svelte
<script>
    import { Collapse, Container, NavbarToggler, NavLink } from "sveltestrap";
    import Link from "svelte-link";
    import { browser } from "$app/environment"

    // Import Images
    import logodark from "../../../assets/images/logo-dark.png";
    import logolight from "../../../assets/images/logo-light.png";
    import { onMount } from "svelte";
    
    let navClass = '';
    let isOpen = true
    onMount(() => {
        if (browser) {
            window.addEventListener("scroll", scrollNavigation, true);
        }
    });
    const toggle = () => {isOpen = !isOpen};

const scrollNavigation = () => {
    var scrollup = document.documentElement.scrollTop;
    if (scrollup > 50) {
        navClass = "is-sticky";
    } else {
        navClass = '';
    }
}
</script>
<nav class={"navbar navbar-expand-lg navbar-landing navbar-light fixed-top " + navClass} id="navbar">
    <Container>
        <Link class="navbar-brand" href="/dashboard">
            <img src={logodark} class="card-logo card-logo-dark" alt="logo dark" height="17" />
            <img src={logolight} class="card-logo card-logo-light" alt="logo light" height="17" />
        </Link>

        <NavbarToggler class="navbar-toggler py-0 fs-20 text-body" on:click={toggle} type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <i class="mdi mdi-menu"></i>
        </NavbarToggler>

        <Collapse
            class="navbar-collapse"
            id="navbarSupportedContent"
            {isOpen}
        >
            <div
                class="navbar-nav mx-auto mt-2 mt-lg-0 active"
                id="navbar-example"
            >
                <li class="nav-item">
                    <NavLink href="#hero" class="fs-15">Home</NavLink>
                </li>
                <li class="nav-item">
                    <NavLink href="#wallet" class="fs-15">Wallet</NavLink>
                </li>
                <li class="nav-item">
                    <NavLink href="#marketplace" class="fs-15">Marketplace</NavLink>
                </li>
                <li class="nav-item">
                    <NavLink href="#categories" class="fs-15">Categories</NavLink>
                </li>
                <li class="nav-item">
                    <NavLink href="#creators" class="fs-15">Creators</NavLink>
                </li>
            </div>

            <div class="">
                <Link href="//crypto/mywallet" class="btn btn-success">Wallet Connect </Link>
            </div>
        </Collapse>
    </Container>
</nav>
<div class="bg-overlay bg-overlay-pattern"></div>

// React+Inertia/Interactive/resources/js/Pages/Landing/NFTLanding/Navbar.tsx
import React, { useState, useEffect } from 'react';
import { Collapse, Container, NavbarToggle, NavLink } from 'react-bootstrap';
import Scrollspy from "react-scrollspy";


//import Images
import logodark from "../../../../images/logo-dark.png";
import logolight from "../../../../images/logo-light.png";
import { Link } from '@inertiajs/react';

const Navbar = () => {
    const [isOpenMenu, setisOpenMenu] = useState<boolean>(false);
    const [navClass, setnavClass] = useState("");

    const toggle = () => setisOpenMenu(!isOpenMenu);

    useEffect(() => {
        window.addEventListener("scroll", scrollNavigation, true);
    });

    const scrollNavigation = () => {
        var scrollup = document.documentElement.scrollTop;
        if (scrollup > 50) {
            setnavClass("is-sticky");
        } else {
            setnavClass("");
        }
    };

    const [activeLink, setActiveLink] = useState<any>();
    useEffect(() => {
        const activation = (event: any) => {
            const target: any = event.target;
            if (target) {
                target.classList.add('active');
                setActiveLink(target);
                if (activeLink && activeLink !== target) {
                    activeLink.classList.remove('active');
                }
            }
        };
        const defaultLink: any = document.querySelector('.navbar li.a.active');
        if (defaultLink) {
            defaultLink?.classList.add("active")
            setActiveLink(defaultLink)
        }
        const links = document.querySelectorAll('.navbar a');
        links.forEach((link) => {
            link.addEventListener('click', activation);
        });
        return () => {
            links.forEach((link) => {
                link.removeEventListener('click', activation);
            });
        };
    }, [activeLink]);

    return (
        <React.Fragment>
            <nav className={"navbar navbar-expand-lg navbar-landing navbar-light fixed-top " + navClass} id="navbar">
                <Container>
                    <Link className="navbar-brand" href="/dashboard">
                        <img src={logodark} className="card-logo card-logo-dark" alt="logo dark" height="17" />
                        <img src={logolight} className="card-logo card-logo-light" alt="logo light" height="17" />
                    </Link>

                    <NavbarToggle className="navbar-toggler py-0 fs-20 text-body" onClick={toggle} type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <i className="mdi mdi-menu"></i>
                    </NavbarToggle>

                    <Collapse
                        className="navbar-collapse"
                        in={isOpenMenu}
                    >
                        <>
                            <Scrollspy
                                offset={-18}
                                items={[
                                    "hero",
                                    "wallet",
                                    "marketplace",
                                    "categories",
                                    "creators",
                                ]}
                                currentClassName="active"
                                className="navbar-nav mx-auto mt-2 mt-lg-0"
                                id="navbar-example"
                            >
                                 <li className="nav-item">
                                <NavLink href="#hero">Home</NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink href="#wallet">Wallet</NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink href="#marketplace">Marketplace</NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink href="#categories">Categories</NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink href="#creators">Creators</NavLink>
                            </li>
                            </Scrollspy>

                            <div className="">
                                <Link href="/apps-nft-wallet" className="btn btn-success">Wallet Connect </Link>
                            </div>
                            </>
                        </Collapse>
                </Container>
            </nav>
            <div className="bg-overlay bg-overlay-pattern"></div>
        </React.Fragment>
    );
};

export default Navbar;
