// React+TS/Corporate/src/Components/Common/ProfileDropdown.tsx
import React, { useState, useEffect } from 'react';
import { useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { Dropdown, DropdownItem, DropdownMenu, DropdownToggle } from 'reactstrap';

//import images
import avatar1 from "../../assets/images/users/avatar-1.jpg";
import { createSelector } from 'reselect';

const ProfileDropdown = () => {

    const profiledropdownData = createSelector(
        (state: any) => state.Profile,
        (user) => user.user
    );
    // Inside your component
    const user = useSelector(profiledropdownData);

    const [userName, setUserName] = useState("Admin");

    useEffect(() => {
        const authUSer: any = sessionStorage.getItem("authUser");
        if (authUSer) {
            const obj: any = JSON.parse(authUSer);
            setUserName(process.env.REACT_APP_DEFAULTAUTH === "fake" ? obj.username === undefined ? user.first_name ? user.first_name : obj.data.first_name : "Admin" || "Admin" :
                process.env.REACT_APP_DEFAULTAUTH === "firebase" ? obj.email && obj.email : "Admin"
            );
        }
    }, [userName, user]);

    //Dropdown Toggle
    const [isProfileDropdown, setIsProfileDropdown] = useState(false);
    const toggleProfileDropdown = () => {
        setIsProfileDropdown(!isProfileDropdown);
    };
    return (
        <React.Fragment>
            <Dropdown isOpen={isProfileDropdown} toggle={toggleProfileDropdown} className="ms-sm-3 header-item topbar-user">
                <DropdownToggle tag="button" type="button" className="btn">
                    <span className="d-flex align-items-center">
                        <img className="rounded-circle header-profile-user" src={avatar1}
                            alt="Header Avatar" />
                        <span className="text-start ms-xl-2">
                            <span className="d-none d-xl-inline-block ms-1 fw-medium user-name-text">{userName}</span>
                            <span className="d-none d-xl-block ms-1 fs-12 text-muted user-name-sub-text">Founder</span>
                        </span>
                    </span>
                </DropdownToggle>
                <DropdownMenu className="dropdown-menu-end">
                    <h6 className="dropdown-header">Welcome {userName}!</h6>
                    <DropdownItem className='p-0'>
                        <Link to="/profile" className="dropdown-item">
                            <i className="mdi mdi-account-circle text-muted fs-16 align-middle me-1"></i>
                            <span className="align-middle">Profile</span>
                        </Link>
                    </DropdownItem>
                    <DropdownItem className='p-0'>
                        <Link to="/apps-chat" className="dropdown-item">
                            <i className="mdi mdi-message-text-outline text-muted fs-16 align-middle me-1"></i> <span
                                className="align-middle">Messages</span>
                        </Link>
                    </DropdownItem>
                    <DropdownItem className='p-0'>
                        <Link to={"#"} className="dropdown-item">
                            <i className="mdi mdi-calendar-check-outline text-muted fs-16 align-middle me-1"></i> <span
                                className="align-middle">Taskboard</span>
                        </Link>
                    </DropdownItem>
                    <DropdownItem className='p-0'>
                        <Link to="/pages-faqs" className="dropdown-item">
                            <i
                                className="mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"></i> <span
                                    className="align-middle">Help</span>
                        </Link>
                    </DropdownItem>
                    <div className="dropdown-divider"></div>
                    <DropdownItem className='p-0'>
                        <Link to="/pages-profile" className="dropdown-item">
                            <i
                                className="mdi mdi-wallet text-muted fs-16 align-middle me-1"></i> <span
                                    className="align-middle">Balance : <b>$5971.67</b></span>
                        </Link>
                    </DropdownItem >
                    <DropdownItem className='p-0'>
                        <Link to="/pages-profile-settings" className="dropdown-item">
                            <span
                                className="badge bg-success-subtle text-success mt-1 float-end">New</span><i
                                    className="mdi mdi-cog-outline text-muted fs-16 align-middle me-1"></i> <span
                                        className="align-middle">Settings</span>
                        </Link>
                    </DropdownItem>
                    <DropdownItem className='p-0'>
                        <Link to="/auth-lockscreen-basic" className="dropdown-item">
                            <i
                                className="mdi mdi-lock text-muted fs-16 align-middle me-1"></i> <span className="align-middle">Lock screen</span>
                        </Link>
                    </DropdownItem>
                    <DropdownItem className='p-0'>
                        <Link to="/logout" className="dropdown-item">
                            <i
                                className="mdi mdi-logout text-muted fs-16 align-middle me-1"></i> <span
                                    className="align-middle" data-key="t-logout">Logout</span>
                        </Link>
                    </DropdownItem>
                </DropdownMenu>
            </Dropdown>
        </React.Fragment>
    );
};

export default ProfileDropdown;

// Svelte/corporate/src/Components/Common/ProfileDropdown.svelte
<script>
    import {
        Dropdown,
        DropdownToggle,
        DropdownMenu,
        DropdownItem,
    } from "sveltestrap";
    import avatar1 from '../../assets/images/users/avatar-1.jpg';
	import { goto,invalidateAll } from '$app/navigation';

const logout = async  function () {
    await invalidateAll();
    localStorage.removeItem('authUser');
    goto('/authentication/login');
}
</script>

<Dropdown class="ms-sm-3 header-item topbar-user">
    <DropdownToggle type="button" color="" class="btn" id="page-header-user-dropdown p-0">
        <span class="d-flex align-items-center">
            <img class="rounded-circle header-profile-user" src={avatar1} alt="Header Avatar" />
            <span class="text-start ms-xl-2">
                <span class="d-none d-xl-inline-block ms-1 fw-medium user-name-text">Anna Adame</span>
                <span class="d-none d-xl-block ms-1 fs-12 text-muted user-name-sub-text">Founder</span>
            </span>
        </span>
    </DropdownToggle>
    <DropdownMenu class="dropdown-menu-end" end>
        <!-- item-->
        <h6 class="dropdown-header">Welcome Anna!</h6>
        <DropdownItem href="/pages/profile/simple"><i
                class="mdi mdi-account-circle text-muted fs-16 align-middle me-1" /> <span
                class="align-middle">Profile</span></DropdownItem>
        <DropdownItem href="/apps-chat"><i class="mdi mdi-message-text-outline text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Messages</span>
        </DropdownItem>
        <DropdownItem href="/tasks/apps-tasks-kanban"><i
                class="mdi mdi-calendar-check-outline text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Taskboard</span>
        </DropdownItem>
        <DropdownItem href="/pages/faqs"><i class="mdi mdi-lifebuoy text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Help</span>
        </DropdownItem>
        <div class="dropdown-divider" />
        <DropdownItem href="/pages/profile/simple"><i class="mdi mdi-wallet text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Balance : <b>$5971.67</b></span>
        </DropdownItem>
        <DropdownItem href="/pages/profile/simple"><span
                class="badge bg-success-subtle text-success mt-1 float-end">New</span><i
                class="mdi mdi-cog-outline text-muted fs-16 align-middle me-1" /> <span
                class="align-middle">Settings</span></DropdownItem>
        <DropdownItem href="/authenticationInner/lockscreen/auth-lockscreen-basic"><i
                class="mdi mdi-lock text-muted fs-16 align-middle me-1" />
            <span class="align-middle">Lock screen</span>
        </DropdownItem>
        <DropdownItem href={null} on:click={logout}><i
                class="mdi mdi-logout text-muted fs-16 align-middle me-1" />
            <span class="align-middle" data-key="t-logout">Logout</span>
        </DropdownItem>
    </DropdownMenu>
</Dropdown>
